//! Auto-generated wgpu bindings for `effects/mode.wgsl`.
//!
//! This file is a thin `include!` bridge: the actual Rust source is generated
//! by `wgsl_bindgen` at build time and written into `OUT_DIR/mode_generated.rs`.
//! Nothing in this file should be edited by hand — the generated content is the
//! authoritative source of truth for the Mode bind-group layout.
//!
//! The generated module `mode` exposes:
//! - `ModeUniforms` — `#[repr(C)] Pod + Zeroable` uniform struct (32 bytes).
//! - `WgpuBindGroup0` / `WgpuBindGroup0Entries` — typed bind-group helpers.
//! - `ModeUniforms::new` — pad-free constructor (zero-fills `_pad*` automatically).
//!
//! ## `#import blend_helpers`
//!
//! `mode.wgsl` carries `#import blend_helpers::{…}`.  `wgsl_bindgen` resolves it
//! at codegen time (via the `shaders/` import scan dir set in `build.rs`) so it
//! can parse the shader and emit the bindings.  The blend-helper functions
//! themselves generate nothing — only the uniform struct and bind group do.
//! The runtime pipeline still composes the shader module via `compose_wgsl_shader`.
//!
//! ## Byte-identity guarantee (GO/NO-GO gate)
//!
//! The generated `ModeUniforms` struct MUST be layout-identical to the former
//! hand-written `ModeUniform` that it replaces:
//!
//! | Byte offset | Size | Field        |
//! |-------------|------|--------------|
//! | 0           | 16   | `color`      |
//! | 16          | 4    | `blend_mode` |
//! | 20          | 12   | `_pad*`      |
//!
//! Total = 32 bytes.  The `const` assertions in `pipeline.rs` enforce this at
//! compile time.

// JUSTIFICATION: all lints below apply to code generated by wgsl_bindgen 0.22.
// Names, derives, and patterns are controlled by the codegen tool, not by this
// crate.  Suppressing them here keeps the diagnostic surface clean without
// requiring changes to the generated content.  (Same rationale as
// `blur/generated.rs` — see that file for the per-lint breakdown.)
#[allow(
    missing_docs,
    missing_debug_implementations,
    unsafe_code,
    unused,
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    elided_lifetimes_in_paths,
    unused_doc_comments,
    clippy::all,
    clippy::pedantic
)]
pub(super) mod mode_gen {
    include!(concat!(env!("OUT_DIR"), "/mode_generated.rs"));
}

/// Re-export the generated `mode` submodule at the path callers use.
pub(super) use mode_gen::mode;
