//! Bundled font assets: offline inventory, provenance, notice, and
//! deterministic-fixture checks.
//!
//! Every font `flui-painting` distributes is recorded in
//! `assets/fonts/inventory.toml` with its SHA-256, provenance and license
//! notices; generated fixtures must reproduce byte for byte from their
//! first-party generator; and the restricted Arial fixture must never come
//! back. `--package-list` additionally checks Cargo's file selection for the
//! crate — evidence about selection only, not a successful archive or build.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

use anyhow::Context;
use serde::Deserialize;

use crate::util::{ScratchDir, repo_root};

const ASSETS: &str = "crates/flui-painting/assets/fonts";
const GENERATOR: &str = "tools/decoy-face/generate.py";
const RESTRICTED_SHA256: &str = "74d696e666f696e93db685a85c94bfbfcc0796dfcf8a2e2e2c908a54e82949";
const FONT_SUFFIXES: [&str; 4] = ["ttf", "otf", "woff", "woff2"];
/// Top-level directories searched for fonts outside the inventory owner.
const SEARCHED: [&str; 4] = ["crates", "examples", "tools", "assets"];
const PRUNED: [&str; 3] = ["target", ".git", ".claude"];

/// Arguments for `cargo xtask font-assets`.
#[derive(Debug, clap::Args)]
pub(crate) struct FontAssetsArgs {
    /// Repository root to check (default: this repository).
    #[arg(long)]
    root: Option<PathBuf>,
    /// Also check Cargo file selection, without creating archives.
    #[arg(long)]
    package_list: bool,
}

/// `cargo xtask font-assets`: check or list the bundled font assets.
pub(crate) fn font_assets(args: &FontAssetsArgs) -> anyhow::Result<ExitCode> {
    let root = args.root.clone().unwrap_or_else(repo_root);
    let mut errors = check(&root)?;
    if errors.is_empty() {
        errors.extend(reproduce(&root)?);
    }
    if errors.is_empty() && args.package_list {
        errors.extend(package_listing(&root)?);
    }
    for error in &errors {
        eprintln!("font-assets: {error}");
    }
    if !errors.is_empty() {
        return Ok(ExitCode::FAILURE);
    }
    println!(
        "font-assets: inventory, provenance, notices and generated bytes verified{}",
        if args.package_list {
            "; Cargo package listing verified (not archive/build evidence)"
        } else {
            ""
        }
    );
    Ok(ExitCode::SUCCESS)
}

/// `assets/fonts/inventory.toml`.
#[derive(Debug, Deserialize)]
struct Inventory {
    #[serde(default)]
    notice: Vec<Notice>,
    #[serde(default)]
    font: Vec<Font>,
}

/// A license or attribution file shipped next to the fonts.
#[derive(Debug, Deserialize)]
struct Notice {
    file: String,
    sha256: Option<String>,
    source: Option<String>,
}

/// One distributed font and where it came from.
#[derive(Debug, Deserialize)]
struct Font {
    file: String,
    sha256: Option<String>,
    kind: Option<String>,
    source: Option<String>,
    license: Option<String>,
    notices: Option<Vec<String>>,
    revision: Option<String>,
    archive_sha256: Option<String>,
    generator: Option<String>,
}

/// A present, non-empty field.
fn given(field: Option<&String>) -> bool {
    field.is_some_and(|value| !value.is_empty())
}

fn is_font(path: &Path) -> bool {
    path.extension()
        .and_then(|ext| ext.to_str())
        .is_some_and(|ext| FONT_SUFFIXES.contains(&ext.to_ascii_lowercase().as_str()))
}

/// `path` relative to `base`, with `/` separators.
fn relative(path: &Path, base: &Path) -> String {
    path.strip_prefix(base)
        .expect("BUG: walked paths sit under their root")
        .components()
        .map(|part| part.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn digest_file(path: &Path) -> anyhow::Result<String> {
    let bytes = std::fs::read(path).with_context(|| format!("reading {}", path.display()))?;
    Ok(sha256_hex(&bytes))
}

fn read_inventory(assets: &Path) -> anyhow::Result<Inventory> {
    let path = assets.join("inventory.toml");
    let text =
        std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    toml::from_str(&text).with_context(|| format!("parsing {}", path.display()))
}

/// The inventory, provenance and notice findings for the tree at `root`.
fn check(root: &Path) -> anyhow::Result<Vec<String>> {
    let assets = root.join(ASSETS);
    let mut errors = Vec::new();

    let mut discovered = BTreeMap::new();
    for entry in walkdir::WalkDir::new(&assets)
        .into_iter()
        .filter_map(Result::ok)
    {
        if entry.file_type().is_file() && is_font(entry.path()) {
            discovered.insert(relative(entry.path(), &assets), entry.path().to_path_buf());
        }
    }
    for (name, path) in &discovered {
        let file_name = path.file_name().map(|n| n.to_string_lossy().to_lowercase());
        if file_name.as_deref() == Some("arial.ttf") || digest_file(path)? == RESTRICTED_SHA256 {
            errors.push(format!(
                "{name}: restricted Arial fixture must not be distributed"
            ));
        }
    }

    for directory in SEARCHED {
        let walk = walkdir::WalkDir::new(root.join(directory))
            .sort_by_file_name()
            .into_iter()
            .filter_entry(|entry| {
                !(entry.depth() > 0
                    && entry.file_type().is_dir()
                    && PRUNED.contains(&entry.file_name().to_string_lossy().as_ref()))
            });
        for entry in walk.filter_map(Result::ok) {
            let path = entry.path();
            if entry.file_type().is_file() && is_font(path) && !path.starts_with(&assets) {
                errors.push(format!(
                    "{}: unlisted font outside the inventory owner",
                    relative(path, root)
                ));
            }
        }
    }

    if !assets.join("inventory.toml").exists() {
        errors.push("font provenance inventory and license notice records are missing".to_owned());
        return Ok(errors);
    }
    let inventory = read_inventory(&assets)?;

    let mut notices = BTreeSet::new();
    for notice in &inventory.notice {
        let name = &notice.file;
        if !notices.insert(name.as_str()) {
            errors.push(format!("{name}: duplicate notice record"));
        }
        let path = assets.join(name);
        if !path.is_file() {
            errors.push(format!("{name}: missing license/notice file"));
        } else if Some(&digest_file(&path)?) != notice.sha256.as_ref() {
            errors.push(format!("{name}: notice hash mismatch"));
        }
        if !given(notice.source.as_ref()) {
            errors.push(format!("{name}: missing notice provenance"));
        }
    }

    let mut records = BTreeSet::new();
    for font in &inventory.font {
        let name = &font.file;
        if !records.insert(name.as_str()) {
            errors.push(format!("{name}: duplicate font record"));
        }
        match discovered.get(name) {
            None => errors.push(format!("{name}: recorded font is missing")),
            Some(path) => {
                if Some(&digest_file(path)?) != font.sha256.as_ref() {
                    errors.push(format!("{name}: font hash mismatch"));
                }
            }
        }
        if !given(font.source.as_ref()) || !given(font.license.as_ref()) {
            errors.push(format!("{name}: missing source or license provenance"));
        }
        let kind = font.kind.as_deref();
        if !matches!(kind, Some("generated" | "upstream")) {
            errors.push(format!("{name}: invalid provenance kind"));
        }
        let associated = font.notices.as_ref().is_some_and(|list| {
            !list.is_empty() && list.iter().all(|notice| notices.contains(notice.as_str()))
        });
        if !associated {
            errors.push(format!(
                "{name}: missing recorded license/notice association"
            ));
        }
        if kind == Some("upstream")
            && !(given(font.revision.as_ref()) || given(font.archive_sha256.as_ref()))
        {
            errors.push(format!(
                "{name}: upstream source must pin revision or archive checksum"
            ));
        }
        if kind == Some("generated")
            && !root
                .join(font.generator.as_deref().unwrap_or_default())
                .is_file()
        {
            errors.push(format!("{name}: missing first-party generator"));
        }
    }
    for name in discovered.keys() {
        if !records.contains(name.as_str()) {
            errors.push(format!("{name}: unlisted font asset"));
        }
    }
    Ok(errors)
}

/// Regenerates every generated fixture into a scratch directory and compares
/// it byte for byte with the committed file; the committed assets are never
/// written.
fn reproduce(root: &Path) -> anyhow::Result<Vec<String>> {
    let assets = root.join(ASSETS);
    let inventory = read_inventory(&assets)?;
    let generated: BTreeSet<&str> = inventory
        .font
        .iter()
        .filter(|font| font.kind.as_deref() == Some("generated"))
        .map(|font| font.file.as_str())
        .collect();

    let Some(python) = find_python() else {
        return Ok(vec![format!(
            "fixture generation needs Python >= 3.10 for {GENERATOR}; none found on PATH"
        )]);
    };
    let scratch = ScratchDir::new("font-assets")?;
    let result = Command::new(&python)
        .arg("-B")
        .arg(root.join(GENERATOR))
        .arg("--output-dir")
        .arg(scratch.path())
        .output()
        .with_context(|| format!("spawning `{python}`"))?;
    if !result.status.success() {
        return Ok(vec![format!(
            "fixture generation failed: {}",
            String::from_utf8_lossy(&result.stderr)
        )]);
    }

    let mut outputs = BTreeSet::new();
    for entry in std::fs::read_dir(scratch.path())? {
        let name = entry?.file_name().to_string_lossy().into_owned();
        // Exactly `*.ttf`, as the generator names its outputs.
        if Path::new(&name).extension().is_some_and(|ext| ext == "ttf") {
            outputs.insert(name);
        }
    }
    let mut errors = Vec::new();
    let differing: Vec<&str> = outputs
        .iter()
        .map(String::as_str)
        .filter(|name| !generated.contains(name))
        .chain(
            generated
                .iter()
                .copied()
                .filter(|name| !outputs.contains(*name)),
        )
        .collect();
    if !differing.is_empty() {
        errors.push(format!(
            "generated inventory differs from generator outputs: {differing:?}"
        ));
    }
    for name in outputs
        .iter()
        .filter(|name| generated.contains(name.as_str()))
    {
        let fresh = std::fs::read(scratch.path().join(name))?;
        let committed =
            std::fs::read(assets.join(name)).with_context(|| format!("reading {ASSETS}/{name}"))?;
        if fresh != committed {
            errors.push(format!("{name}: generated bytes are not reproducible"));
        }
    }
    Ok(errors)
}

/// Evidence about Cargo's file selection for `flui-painting`, not a
/// successful archive or build.
fn package_listing(root: &Path) -> anyhow::Result<Vec<String>> {
    let inventory = read_inventory(&root.join(ASSETS))?;
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = Command::new(cargo)
        .args([
            "package",
            "-p",
            "flui-painting",
            "--list",
            "--offline",
            "--allow-dirty",
        ])
        .current_dir(root)
        .output()
        .context("spawning `cargo package`")?;
    if !output.status.success() {
        return Ok(vec![format!(
            "Cargo package listing failed: {}",
            String::from_utf8_lossy(&output.stderr)
        )]);
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    let included: BTreeSet<String> = stdout
        .lines()
        .map(|line| line.trim_end().replace('\\', "/"))
        .collect();
    Ok(listing_errors(&inventory, &included))
}

fn listing_errors(inventory: &Inventory, included: &BTreeSet<String>) -> Vec<String> {
    let mut required = BTreeSet::from(["assets/fonts/inventory.toml".to_owned()]);
    required.extend(
        inventory
            .font
            .iter()
            .map(|f| format!("assets/fonts/{}", f.file)),
    );
    required.extend(
        inventory
            .notice
            .iter()
            .map(|n| format!("assets/fonts/{}", n.file)),
    );
    let mut errors: Vec<String> = required
        .difference(included)
        .map(|name| format!("package listing excludes {name}"))
        .collect();
    if included.iter().any(|name| {
        name.rsplit('/')
            .next()
            .is_some_and(|file| file.eq_ignore_ascii_case("arial.ttf"))
    }) {
        errors.push("package listing includes restricted Arial fixture".to_owned());
    }
    errors
}

/// A Python interpreter able to run the font generator (it needs >= 3.10),
/// probed by running it: on Windows `python3` can be a Store stub that exists
/// on PATH and fails.
pub(crate) fn find_python() -> Option<String> {
    [
        "python3",
        "python3.14",
        "python3.13",
        "python3.12",
        "python3.11",
        "python3.10",
        "python",
    ]
    .into_iter()
    .find(|candidate| {
        Command::new(candidate)
            .args(["-c", "import sys; sys.exit(sys.version_info < (3, 10))"])
            .output()
            .is_ok_and(|out| out.status.success())
    })
    .map(str::to_owned)
}

/// Lowercase hex SHA-256 (FIPS 180-4) of `data`. Kept in-module because the
/// check needs only this one digest and no hashing crate is a dependency.
fn sha256_hex(data: &[u8]) -> String {
    const K: [u32; 64] = [
        0x428a_2f98,
        0x7137_4491,
        0xb5c0_fbcf,
        0xe9b5_dba5,
        0x3956_c25b,
        0x59f1_11f1,
        0x923f_82a4,
        0xab1c_5ed5,
        0xd807_aa98,
        0x1283_5b01,
        0x2431_85be,
        0x550c_7dc3,
        0x72be_5d74,
        0x80de_b1fe,
        0x9bdc_06a7,
        0xc19b_f174,
        0xe49b_69c1,
        0xefbe_4786,
        0x0fc1_9dc6,
        0x240c_a1cc,
        0x2de9_2c6f,
        0x4a74_84aa,
        0x5cb0_a9dc,
        0x76f9_88da,
        0x983e_5152,
        0xa831_c66d,
        0xb003_27c8,
        0xbf59_7fc7,
        0xc6e0_0bf3,
        0xd5a7_9147,
        0x06ca_6351,
        0x1429_2967,
        0x27b7_0a85,
        0x2e1b_2138,
        0x4d2c_6dfc,
        0x5338_0d13,
        0x650a_7354,
        0x766a_0abb,
        0x81c2_c92e,
        0x9272_2c85,
        0xa2bf_e8a1,
        0xa81a_664b,
        0xc24b_8b70,
        0xc76c_51a3,
        0xd192_e819,
        0xd699_0624,
        0xf40e_3585,
        0x106a_a070,
        0x19a4_c116,
        0x1e37_6c08,
        0x2748_774c,
        0x34b0_bcb5,
        0x391c_0cb3,
        0x4ed8_aa4a,
        0x5b9c_ca4f,
        0x682e_6ff3,
        0x748f_82ee,
        0x78a5_636f,
        0x84c8_7814,
        0x8cc7_0208,
        0x90be_fffa,
        0xa450_6ceb,
        0xbef9_a3f7,
        0xc671_78f2,
    ];
    let mut state: [u32; 8] = [
        0x6a09_e667,
        0xbb67_ae85,
        0x3c6e_f372,
        0xa54f_f53a,
        0x510e_527f,
        0x9b05_688c,
        0x1f83_d9ab,
        0x5be0_cd19,
    ];
    let bit_len = u64::try_from(data.len())
        .expect("BUG: a slice length fits in u64")
        .wrapping_mul(8);
    let mut message = data.to_vec();
    message.push(0x80);
    while message.len() % 64 != 56 {
        message.push(0);
    }
    message.extend_from_slice(&bit_len.to_be_bytes());

    for block in message.as_chunks::<64>().0 {
        let mut w = [0_u32; 64];
        for (word, bytes) in w.iter_mut().zip(block.as_chunks::<4>().0) {
            *word = u32::from_be_bytes(*bytes);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        // Working variables a..h as one array, shifted down each round.
        let mut v = state;
        for (k, word) in K.iter().zip(w) {
            let s1 = v[4].rotate_right(6) ^ v[4].rotate_right(11) ^ v[4].rotate_right(25);
            let ch = (v[4] & v[5]) ^ (!v[4] & v[6]);
            let t1 = v[7]
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(*k)
                .wrapping_add(word);
            let s0 = v[0].rotate_right(2) ^ v[0].rotate_right(13) ^ v[0].rotate_right(22);
            let maj = (v[0] & v[1]) ^ (v[0] & v[2]) ^ (v[1] & v[2]);
            let t2 = s0.wrapping_add(maj);
            v = [
                t1.wrapping_add(t2),
                v[0],
                v[1],
                v[2],
                v[3].wrapping_add(t1),
                v[4],
                v[5],
                v[6],
            ];
        }
        for (slot, value) in state.iter_mut().zip(v) {
            *slot = slot.wrapping_add(value);
        }
    }
    state
        .iter()
        .fold(String::with_capacity(64), |mut hex, word| {
            write!(hex, "{word:08x}").expect("BUG: writing to a String cannot fail");
            hex
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sha256_matches_the_fips_vectors() {
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            sha256_hex(b"abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        assert_eq!(
            sha256_hex(b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
            "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
        );
    }

    /// A scratch copy of the font assets and their generator: the only parts
    /// of the tree the checks read.
    struct Fixture {
        scratch: ScratchDir,
    }

    impl Fixture {
        fn new() -> Self {
            let scratch = ScratchDir::new("font-assets-test").expect("scratch dir");
            let real = repo_root();
            for dir in [ASSETS, "tools/decoy-face"] {
                copy_dir(&real.join(dir), &scratch.path().join(dir));
            }
            Self { scratch }
        }

        fn root(&self) -> &Path {
            self.scratch.path()
        }

        fn assets(&self) -> PathBuf {
            self.root().join(ASSETS)
        }

        fn check(&self) -> String {
            check(self.root()).expect("check runs").join("\n")
        }
    }

    fn copy_dir(from: &Path, to: &Path) {
        for entry in walkdir::WalkDir::new(from) {
            let entry = entry.expect("walk");
            let target = to.join(entry.path().strip_prefix(from).expect("under root"));
            if entry.file_type().is_dir() {
                std::fs::create_dir_all(&target).expect("mkdir");
            } else {
                std::fs::copy(entry.path(), &target).expect("copy");
            }
        }
    }

    #[test]
    fn inventory_and_every_generated_file_reproduce_offline() {
        let fixture = Fixture::new();
        assert_eq!(fixture.check(), "");
        assert_eq!(
            reproduce(fixture.root()).expect("reproduce runs"),
            Vec::<String>::new()
        );
    }

    #[test]
    fn existing_four_generated_fixtures_are_byte_unchanged() {
        // Historical controls: extending coverage must not alter other probes.
        let assets = repo_root().join(ASSETS);
        for (name, digest) in [
            (
                "decoy-wide-space.ttf",
                "a6fc5cabe4943b7ee032651bd7d7c0bef614f0b5a40bd1dfab62db5e516e0888",
            ),
            (
                "probe-mono-100.ttf",
                "8b8b0fd14500faba32b7b9e1bdd1dedca42c89c0bd43451ae183b8cf391e1221",
            ),
            (
                "probe-mono-600.ttf",
                "c06729a30262f8b541d33f9c8744885f937cb688834b68fb8f1e0b8b1651f996",
            ),
            (
                "probe-variable-wght.ttf",
                "9e3e800de59a6b850039e240192dce3ebecbd6625f222e57e22d1abc2b57acb5",
            ),
        ] {
            assert_eq!(
                digest_file(&assets.join(name)).expect("readable"),
                digest,
                "{name}"
            );
        }
    }

    #[test]
    fn changed_font_bytes_fail() {
        let fixture = Fixture::new();
        std::fs::write(fixture.assets().join("Roboto-Regular.ttf"), b"changed").expect("write");
        assert!(
            fixture
                .check()
                .contains("Roboto-Regular.ttf: font hash mismatch")
        );
    }

    #[test]
    fn missing_and_modified_license_fail() {
        let fixture = Fixture::new();
        let notice = fixture.assets().join("licenses/Roboto-Apache-2.0.txt");
        std::fs::write(&notice, "not the complete license").expect("write");
        assert!(fixture.check().contains("notice hash mismatch"));
        std::fs::remove_file(&notice).expect("remove");
        assert!(fixture.check().contains("missing license/notice"));
    }

    #[test]
    fn unlisted_font_fails_inside_and_outside_current_owner() {
        let fixture = Fixture::new();
        std::fs::write(fixture.assets().join("surprise.otf"), b"font").expect("write");
        let elsewhere = fixture.root().join("crates/new-owner/assets");
        std::fs::create_dir_all(&elsewhere).expect("mkdir");
        std::fs::write(elsewhere.join("surprise.woff2"), b"font").expect("write");
        let errors = fixture.check();
        assert!(
            errors.contains("surprise.otf: unlisted font asset"),
            "{errors}"
        );
        assert!(
            errors.contains(
                "crates/new-owner/assets/surprise.woff2: unlisted font outside the inventory owner"
            ),
            "{errors}"
        );
    }

    #[test]
    fn fonts_under_pruned_directories_are_ignored() {
        let fixture = Fixture::new();
        let build = fixture.root().join("crates/x/target/debug");
        std::fs::create_dir_all(&build).expect("mkdir");
        std::fs::write(build.join("copied.ttf"), b"font").expect("write");
        assert_eq!(fixture.check(), "");
    }

    #[test]
    fn reintroduced_arial_name_is_rejected() {
        let fixture = Fixture::new();
        let assets = fixture.assets();
        std::fs::copy(assets.join("probe-sans-400.ttf"), assets.join("Arial.ttf")).expect("copy");
        assert!(fixture.check().contains("Arial.ttf: restricted Arial"));
    }

    #[test]
    fn missing_provenance_and_notice_association_fail() {
        let fixture = Fixture::new();
        let inventory = fixture.assets().join("inventory.toml");
        let source = std::fs::read_to_string(&inventory).expect("read");
        let stripped: Vec<&str> = source
            .lines()
            .filter(|line| !line.starts_with("source =") && !line.starts_with("notices ="))
            .collect();
        std::fs::write(&inventory, stripped.join("\n")).expect("write");
        let errors = fixture.check();
        assert!(
            errors.contains("missing source or license provenance"),
            "{errors}"
        );
        assert!(
            errors.contains("missing recorded license/notice association"),
            "{errors}"
        );
        assert!(errors.contains("missing notice provenance"), "{errors}");
    }

    #[test]
    fn missing_inventory_is_reported() {
        let fixture = Fixture::new();
        std::fs::remove_file(fixture.assets().join("inventory.toml")).expect("remove");
        assert!(fixture.check().contains("records are missing"));
    }

    #[test]
    fn modified_generator_is_detected_without_overwriting_assets() {
        let fixture = Fixture::new();
        let generator = fixture.root().join(GENERATOR);
        let source = std::fs::read_to_string(&generator).expect("read");
        assert!(source.contains("space_advance=500"), "fixture anchor moved");
        std::fs::write(
            &generator,
            source.replace("space_advance=500", "space_advance=501"),
        )
        .expect("write");
        let committed = fixture.assets().join("probe-sans-400.ttf");
        let before = std::fs::read(&committed).expect("read");
        let errors = reproduce(fixture.root())
            .expect("reproduce runs")
            .join("\n");
        assert!(errors.contains("not reproducible"), "{errors}");
        assert_eq!(std::fs::read(&committed).expect("read"), before);
    }

    #[test]
    fn package_listing_requires_every_recorded_file() {
        let inventory: Inventory =
            toml::from_str("[[notice]]\nfile = \"licenses/A.txt\"\n[[font]]\nfile = \"A.ttf\"\n")
                .expect("parses");
        let complete: BTreeSet<String> = [
            "Cargo.toml",
            "assets/fonts/inventory.toml",
            "assets/fonts/A.ttf",
            "assets/fonts/licenses/A.txt",
        ]
        .map(str::to_owned)
        .into();
        assert!(listing_errors(&inventory, &complete).is_empty());
        let mut broken = complete.clone();
        broken.remove("assets/fonts/A.ttf");
        broken.insert("assets/fonts/ARIAL.TTF".to_owned());
        assert_eq!(
            listing_errors(&inventory, &broken),
            [
                "package listing excludes assets/fonts/A.ttf",
                "package listing includes restricted Arial fixture"
            ]
        );
    }
}
