//! Pipeline for the separable Gaussian blur filter pass.
//!
//! [`BlurPipeline`] owns the `wgpu::RenderPipeline` used by
//! [`super::apply_blur`].  It is format-parametric so the same pipeline
//! serves both the windowed surface format and any pooled offscreen target format.
//!
//! ## Bind-group layout (group 0)
//!
//! Generated by `wgsl_bindgen` from `blur.wgsl` — see `super::generated`.
//! The layout is auto-verified at build time against the WGSL struct definition.
//!
//! | Binding | Stage  | Type                     | Content                          |
//! |---------|--------|--------------------------|----------------------------------|
//! | 0       | VS+FS  | Uniform buffer           | `BlurUniforms` (32 bytes)        |
//! | 1       | VS+FS  | 2D float texture         | Source (premultiplied RGBA)      |
//! | 2       | VS+FS  | Linear-filtering sampler | Bilinear + ClampToEdge           |
//!
//! ## Uniform layout
//!
//! `BlurUniforms` (generated) matches `BlurUniforms` in `blur.wgsl` exactly:
//!
//! | Byte offset | Size | Field              | WGSL member    |
//! |-------------|------|--------------------|----------------|
//! | 0           | 8    | `texture_size`     | `vec2<f32>`    |
//! | 8           | 4    | `sigma`            | `f32`          |
//! | 12          | 4    | `direction`        | `f32`          |
//! | 16          | 16   | `content_rect_uv`  | `vec4<f32>`    |
//!
//! Total = 32 bytes (multiple of 16 ✓).
//!
//! ## Sampler
//!
//! Blur uses `FilterMode::Linear` + `SamplerBindingType::Filtering`
//! with `TextureSampleType::Float { filterable: true }`.  Bilinear filtering
//! is valid for Gaussian blurs because the continuous kernel composes cleanly
//! with bilinear interpolation and does not produce artefacts.

use super::generated::blur;

// ── Byte-identity gate ────────────────────────────────────────────────────────
//
// These const assertions are the GO/NO-GO check.  If wgsl_bindgen generates a
// struct whose layout differs from the hand-written `BlurUniform`, this file
// will fail to compile — which is the correct signal to stop and report BLOCKED.

/// The generated `BlurUniforms` must be exactly 32 bytes — matching the WGSL
/// `BlurUniforms` struct and the former hand-written `BlurUniform`.
const _GENERATED_BLUR_UNIFORMS_SIZE_CHECK: () = {
    assert!(std::mem::size_of::<blur::BlurUniforms>() == 32);
};

/// `texture_size` must be at byte offset 0.
const _GENERATED_BLUR_TEXTURE_SIZE_OFFSET_CHECK: () = {
    assert!(std::mem::offset_of!(blur::BlurUniforms, texture_size) == 0);
};

/// `sigma` must be at byte offset 8.
const _GENERATED_BLUR_SIGMA_OFFSET_CHECK: () = {
    assert!(std::mem::offset_of!(blur::BlurUniforms, sigma) == 8);
};

/// `direction` must be at byte offset 12.
const _GENERATED_BLUR_DIRECTION_OFFSET_CHECK: () = {
    assert!(std::mem::offset_of!(blur::BlurUniforms, direction) == 12);
};

/// `content_rect_uv` must be at byte offset 16.
const _GENERATED_BLUR_CONTENT_RECT_UV_OFFSET_CHECK: () = {
    assert!(std::mem::offset_of!(blur::BlurUniforms, content_rect_uv) == 16);
};

// ── Pipeline ──────────────────────────────────────────────────────────────────

/// Render pipeline for the Gaussian blur filter pass.
///
/// The bind-group layout is created from the generated `blur::WgpuBindGroup0`
/// and is not stored here — callers use `blur::WgpuBindGroup0::from_bindings`
/// at draw time, which creates a compatible bind group internally.
///
/// ## Blend state
///
/// `REPLACE` (no fixed-function blending): the fragment shader emits the full
/// premultiplied result directly.
///
/// ## Sampler distinction from morphology and color_matrix
///
/// Morphology and color_matrix use `NonFiltering` (nearest) — the per-channel
/// max/min and matrix operations are exact on texel-aligned samples.  Blur uses
/// `Filtering` (bilinear): the Gaussian kernel naturally composes with bilinear
/// interpolation without artefact.
#[allow(missing_debug_implementations)]
pub(crate) struct BlurPipeline {
    /// The single render pipeline (format-parametric at construction time).
    pub(crate) pipeline: wgpu::RenderPipeline,
}

impl BlurPipeline {
    /// Build the pipeline for `surface_format`.
    ///
    /// WGSL shader compilation happens here; a wgpu validation error surfaces
    /// at this call site, which the GPU construction test exercises.
    pub(crate) fn new(device: &wgpu::Device, surface_format: wgpu::TextureFormat) -> Self {
        // The bind-group layout is sourced from the generated bindings, which derive
        // it directly from the WGSL source — no hand-maintained descriptor.
        let bind_group_layout = blur::WgpuBindGroup0::get_bind_group_layout(device);
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Blur Pipeline Layout"),
            bind_group_layouts: &[Some(&bind_group_layout)],
            immediate_size: 0,
        });

        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Blur Shader"),
            source: wgpu::ShaderSource::Wgsl(include_str!("../shaders/effects/blur.wgsl").into()),
        });

        let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("Blur Pipeline"),
            layout: Some(&pipeline_layout),
            vertex: wgpu::VertexState {
                module: &shader,
                entry_point: Some("vs_main"),
                // No vertex buffers: the VS synthesises 6 vertices from
                // `@builtin(vertex_index)`, forming a full-viewport quad.
                buffers: &[],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &shader,
                entry_point: Some("fs_main"),
                targets: &[Some(wgpu::ColorTargetState {
                    format: surface_format,
                    // REPLACE: the shader emits the full premultiplied result.
                    blend: Some(wgpu::BlendState::REPLACE),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                strip_index_format: None,
                front_face: wgpu::FrontFace::Ccw,
                cull_mode: None,
                polygon_mode: wgpu::PolygonMode::Fill,
                unclipped_depth: false,
                conservative: false,
            },
            depth_stencil: None,
            multisample: wgpu::MultisampleState {
                count: 1,
                mask: !0,
                alpha_to_coverage_enabled: false,
            },
            multiview_mask: None,
            cache: None,
        });

        Self { pipeline }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod cpu_tests {
    use super::blur;

    /// The generated `BlurUniforms` struct must be 32 bytes to match the WGSL
    /// `BlurUniforms` block and the former hand-written `BlurUniform`.
    /// The `const` asserts above fire at compile time; this test makes the
    /// requirement visible in test output.
    #[test]
    fn blur_uniforms_size_is_32_bytes() {
        assert_eq!(
            std::mem::size_of::<blur::BlurUniforms>(),
            32,
            "BlurUniforms must be 32 bytes to match BlurUniforms in blur.wgsl"
        );
    }

    /// Field offsets must match the WGSL uniform-block layout exactly.
    #[test]
    fn blur_uniforms_field_offsets_match_wgsl() {
        assert_eq!(
            std::mem::offset_of!(blur::BlurUniforms, texture_size),
            0,
            "texture_size must be at offset 0"
        );
        assert_eq!(
            std::mem::offset_of!(blur::BlurUniforms, sigma),
            8,
            "sigma must be at offset 8"
        );
        assert_eq!(
            std::mem::offset_of!(blur::BlurUniforms, direction),
            12,
            "direction must be at offset 12"
        );
        assert_eq!(
            std::mem::offset_of!(blur::BlurUniforms, content_rect_uv),
            16,
            "content_rect_uv must be at offset 16"
        );
    }

    /// Round-trip: values written into the struct are readable from the same
    /// byte positions — proves the generated layout has no hidden reordering.
    #[allow(
        clippy::float_cmp,
        reason = "comparing floats we just assigned from exact literals — bit identity is the invariant"
    )]
    #[test]
    fn blur_uniforms_field_round_trips() {
        let u = blur::BlurUniforms::new([640.0, 480.0], 4.0, 1.0, [0.1, 0.2, 0.9, 0.8]);
        assert_eq!(u.texture_size, [640.0, 480.0]);
        assert_eq!(u.sigma, 4.0);
        assert_eq!(u.direction, 1.0);
        assert_eq!(u.content_rect_uv, [0.1, 0.2, 0.9, 0.8]);
    }
}

#[cfg(all(test, feature = "enable-wgpu-tests"))]
mod gpu_construction_tests {
    use super::BlurPipeline;

    fn test_device() -> wgpu::Device {
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::new_without_display_handle());
        let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::LowPower,
            force_fallback_adapter: false,
            compatible_surface: None,
        }))
        .expect("a GPU adapter must be available on a GPU-enabled test host");
        let (device, _queue) =
            pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
                label: Some("BlurPipeline Test Device"),
                ..Default::default()
            }))
            .expect("GPU device creation succeeded when adapter was found");
        device
    }

    /// `BlurPipeline::new` completes without a wgpu validation error for
    /// `Rgba8Unorm`, proving the WGSL parses and the generated bind-group
    /// layout is valid.
    #[test]
    fn pipeline_construction_succeeds_for_rgba8unorm() {
        let device = test_device();
        let _pipeline = BlurPipeline::new(&device, wgpu::TextureFormat::Rgba8Unorm);
    }
}
