# Rustfmt configuration for FLUI workspace
# https://rust-lang.github.io/rustfmt

# Edition
edition = "2024"

# Line width
max_width = 100

# Imports
reorder_imports = true

# Whitespace
use_small_heuristics = "Default"
newline_style = "Auto"

# Functions
fn_params_layout = "Tall"

# Control flow
match_arm_leading_pipes = "Never"

# Miscellaneous
remove_nested_parens = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
