//! Pipeline for the per-pixel color-matrix filter pass.
//!
//! [`ColorMatrixPipeline`] owns the `wgpu::RenderPipeline` used by
//! [`super::apply_color_matrix`].  It is format-parametric so the same pipeline
//! serves both the windowed surface format and any pooled offscreen target format.
//!
//! ## Matrix upload format
//!
//! The CPU-side color matrix is stored row-major as `[f32; 20]`:
//!
//! ```text
//!   [r0, r1, r2, r3, offset_r,   // row 0: R output weights + bias
//!    g0, g1, g2, g3, offset_g,   // row 1: G output weights + bias
//!    b0, b1, b2, b3, offset_b,   // row 2: B output weights + bias
//!    a0, a1, a2, a3, offset_a]   // row 3: A output weights + bias
//! ```
//!
//! [`color_matrix_uniform_from_values`] splits this into a 4×4 weight matrix
//! (stored column-major for WGSL) and a vec4 offset, uploaded as a single
//! 80-byte uniform block.
//!
//! ## Bind-group layout (group 0)
//!
//! Generated by `wgsl_bindgen` from `color_matrix.wgsl` — see `super::generated`.
//! The layout is auto-verified at build time against the WGSL struct definition.
//!
//! | Binding | Stage  | Type                  | Content                      |
//! |---------|--------|-----------------------|------------------------------|
//! | 0       | VS+FS  | Uniform buffer        | `ColorMatrixUniforms`        |
//! | 1       | VS+FS  | 2D float texture      | Source layer (premultiplied) |
//! | 2       | VS+FS  | Non-filtering sampler | Nearest + ClampToEdge        |
//!
//! ## Uniform layout
//!
//! `ColorMatrixUniforms` (generated) matches `ColorMatrixUniforms` in `color_matrix.wgsl`:
//!
//! | Byte offset | Size | Field    | WGSL member   |
//! |-------------|------|----------|---------------|
//! | 0           | 64   | `m`      | `mat4x4<f32>` |
//! | 64          | 16   | `offset` | `vec4<f32>`   |
//!
//! Total = 80 bytes (multiple of 16 ✓).
//!
//! ## WGSL column-major layout — critical correctness note
//!
//! WGSL `mat4x4<f32>` is column-major; `[[f32; 4]; 4]` in Rust matches it
//! exactly.  `mat * vec` in WGSL is the standard column-major product:
//! `result[i] = dot(column_i, vec)`.  We want row dot-products, so
//! [`color_matrix_uniform_from_values`] packs **columns** of M into `m[i]`:
//!
//! ```text
//!   m[0] = [r0, g0, b0, a0]  column 0 of M: first  weight of every row
//!   m[1] = [r1, g1, b1, a1]  column 1 of M: second weight of every row
//!   m[2] = [r2, g2, b2, a2]  column 2 of M: third  weight of every row
//!   m[3] = [r3, g3, b3, a3]  column 3 of M: fourth weight of every row
//! ```

use super::generated::color_matrix;

// ── Byte-identity gate ────────────────────────────────────────────────────────
//
// These const assertions are the layout gate.  If wgsl_bindgen generates a
// struct whose layout differs from the hand-written `ColorMatrixUniform`, this
// file will fail to compile — which is the correct signal to stop and report
// BLOCKED rather than silently absorb a layout divergence.

/// The generated `ColorMatrixUniforms` must be exactly 80 bytes — matching the
/// WGSL `ColorMatrixUniforms` struct and the former hand-written `ColorMatrixUniform`.
const _GENERATED_COLOR_MATRIX_UNIFORMS_SIZE_CHECK: () = {
    assert!(std::mem::size_of::<color_matrix::ColorMatrixUniforms>() == 80);
};

/// `m` (the 4×4 column-major weight matrix) must be at byte offset 0.
const _GENERATED_COLOR_MATRIX_M_OFFSET_CHECK: () = {
    assert!(std::mem::offset_of!(color_matrix::ColorMatrixUniforms, m) == 0);
};

/// `offset` (the additive bias) must be at byte offset 64.
const _GENERATED_COLOR_MATRIX_OFFSET_OFFSET_CHECK: () = {
    assert!(std::mem::offset_of!(color_matrix::ColorMatrixUniforms, offset) == 64);
};

// ── Uniform constructor ───────────────────────────────────────────────────────

/// Build a [`color_matrix::ColorMatrixUniforms`] from the flat `[f32; 20]`
/// row-major color-matrix layout.
///
/// Input layout: `[r0, r1, r2, r3, off_r,  g0..off_g,  b0..off_b,  a0..off_a]`.
///
/// Each `m[i]` is stored as **column `i`** of the 4×4 weight matrix so that
/// WGSL's column-major `mat4x4<f32>` reads `u.m` as M (not Mᵀ).  The mapping:
///
/// ```text
///   m[0] = [r0, g0, b0, a0]  column 0: first  weight of every row
///   m[1] = [r1, g1, b1, a1]  column 1: second weight of every row
///   m[2] = [r2, g2, b2, a2]  column 2: third  weight of every row
///   m[3] = [r3, g3, b3, a3]  column 3: fourth weight of every row
/// ```
pub(crate) fn color_matrix_uniform_from_values(
    values: [f32; 20],
) -> color_matrix::ColorMatrixUniforms {
    color_matrix::ColorMatrixUniforms::new(
        [
            // Column 0: the first RGBA weight of each output channel.
            [values[0], values[5], values[10], values[15]],
            // Column 1: the second RGBA weight of each output channel.
            [values[1], values[6], values[11], values[16]],
            // Column 2: the third RGBA weight of each output channel.
            [values[2], values[7], values[12], values[17]],
            // Column 3: the fourth RGBA weight of each output channel.
            [values[3], values[8], values[13], values[18]],
        ],
        [values[4], values[9], values[14], values[19]],
    )
}

// ── Pipeline ──────────────────────────────────────────────────────────────────

/// Render pipeline for the color-matrix filter pass.
///
/// The bind-group layout is created from the generated `color_matrix::WgpuBindGroup0`
/// and is not stored here — callers use `color_matrix::WgpuBindGroup0::from_bindings`
/// at draw time, which creates a compatible bind group internally.
///
/// ## Blend state
///
/// `REPLACE` (no fixed-function blending): the fragment shader emits the full
/// premultiplied filtered texel directly.
pub(crate) struct ColorMatrixPipeline {
    /// The single render pipeline (format-parametric at construction time).
    pub(crate) pipeline: wgpu::RenderPipeline,
}

impl ColorMatrixPipeline {
    /// Build the pipeline for `surface_format`.
    ///
    /// WGSL shader compilation happens here; a wgpu validation error surfaces
    /// at this call site, which the GPU construction test exercises.
    pub(crate) fn new(device: &wgpu::Device, surface_format: wgpu::TextureFormat) -> Self {
        // The bind-group layout is sourced from the generated bindings, which derive
        // it directly from the WGSL source — no hand-maintained descriptor.
        let bind_group_layout = color_matrix::WgpuBindGroup0::get_bind_group_layout(device);
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Color Matrix Pipeline Layout"),
            bind_group_layouts: &[Some(&bind_group_layout)],
            immediate_size: 0,
        });

        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Color Matrix Shader"),
            source: wgpu::ShaderSource::Wgsl(
                include_str!("../shaders/effects/color_matrix.wgsl").into(),
            ),
        });

        let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("Color Matrix Pipeline"),
            layout: Some(&pipeline_layout),
            vertex: wgpu::VertexState {
                module: &shader,
                entry_point: Some("vs_main"),
                // No vertex buffers: the VS synthesises 6 vertices from
                // `@builtin(vertex_index)`, forming a full-viewport quad.
                buffers: &[],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &shader,
                entry_point: Some("fs_main"),
                targets: &[Some(wgpu::ColorTargetState {
                    format: surface_format,
                    // REPLACE: the shader emits the full premultiplied result.
                    blend: Some(wgpu::BlendState::REPLACE),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                strip_index_format: None,
                front_face: wgpu::FrontFace::Ccw,
                cull_mode: None,
                polygon_mode: wgpu::PolygonMode::Fill,
                unclipped_depth: false,
                conservative: false,
            },
            depth_stencil: None,
            multisample: wgpu::MultisampleState {
                count: 1,
                mask: !0,
                alpha_to_coverage_enabled: false,
            },
            multiview_mask: None,
            cache: None,
        });

        Self { pipeline }
    }
}
