//! Auto-generated wgpu bindings for `gamma.wgsl`.
//!
//! This file is a thin `include!` bridge: the actual Rust source is generated
//! by `wgsl_bindgen` at build time and written into `OUT_DIR/gamma_generated.rs`.
//! Nothing in this file should be edited by hand — the generated content is the
//! authoritative source of truth for the gamma bind-group layout.
//!
//! The generated module `gamma` exposes:
//! - `GammaUniforms` — `#[repr(C, align(4))] Pod + Zeroable` uniform struct (16 bytes).
//! - `WgpuBindGroup0` / `WgpuBindGroup0Entries` — typed bind-group helpers.
//! - `GammaUniformsInit` — pad-free constructor (zero-fills `_pad*` automatically).
//! - `layout_asserts::GAMMA_GAMMA_UNIFORMS_ASSERTS` — compile-time size/offset checks.
//!
//! ## Byte-identity guarantee (GO/NO-GO gate)
//!
//! The generated `GammaUniforms` struct MUST be layout-identical to the
//! former hand-written `GammaUniform` that it replaces:
//!
//! | Byte offset | Size | Field       |
//! |-------------|------|-------------|
//! | 0           | 4    | `direction` |
//! | 4           | 12   | `_pad*`     |
//!
//! Total = 16 bytes.  The layout asserts in the generated code enforce this at
//! compile time; the additional `const` assertions in `pipeline.rs` make the
//! requirement explicit in this crate's own code.

// JUSTIFICATION: all lints below apply to code generated by wgsl_bindgen 0.22.
// Names, derives, and patterns are controlled by the codegen tool, not by this
// crate.  Suppressing them here keeps the diagnostic surface clean without
// requiring changes to the generated content.
//
// - missing_docs / missing_debug_implementations: generated pub items lack docs
// - unsafe_code: bytemuck_impls emits `unsafe impl Pod + Zeroable`
// - unused / dead_code: wgsl_bindgen generates more items than this crate uses
//   (shader-module helpers, pipeline-layout helpers, WgpuBindGroups, etc.)
// - non_snake_case / non_camel_case_types / non_upper_case_globals:
//   generated identifiers follow WGSL naming conventions, not Rust conventions
// - elided_lifetimes_in_paths: from_bindings(…, WgpuBindGroup0Entries) elides lifetime
// - unused_doc_comments: #[doc = "..."] on const exprs inside a const block
// - rust_2018_idioms: implied -W flag that fires on elided lifetimes in the generated file
#[allow(
    missing_docs,
    missing_debug_implementations,
    unsafe_code,
    unused,
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    elided_lifetimes_in_paths,
    unused_doc_comments,
    clippy::all,
    clippy::pedantic
)]
pub(super) mod gamma_gen {
    include!(concat!(env!("OUT_DIR"), "/gamma_generated.rs"));
}

/// Re-export the generated `gamma` submodule at the path callers use.
pub(super) use gamma_gen::gamma;
