//! Pipeline for the per-pixel gamma transfer filter pass.
//!
//! [`GammaPipeline`] owns the `wgpu::RenderPipeline` used by
//! [`super::apply_gamma`].  It is format-parametric so the same pipeline
//! serves both windowed surface format and pooled offscreen target format.
//!
//! ## Bind-group layout (group 0)
//!
//! Generated by `wgsl_bindgen` from `gamma.wgsl` — see `super::generated`.
//! The layout is auto-verified at build time against the WGSL struct definition.
//!
//! | Binding | Stage | Type                  | Content                      |
//! |---------|-------|-----------------------|------------------------------|
//! | 0       | FS    | Uniform buffer        | `GammaUniforms`              |
//! | 1       | FS    | 2D float texture      | Source layer (premultiplied) |
//! | 2       | FS    | Non-filtering sampler | Nearest + ClampToEdge        |
//!
//! ## Uniform layout
//!
//! `GammaUniforms` (generated) packs a direction flag into a 16-byte
//! WGSL-compatible block:
//!
//! | Byte offset | Size | Field       | WGSL member |
//! |-------------|------|-------------|-------------|
//! | 0           | 4    | `direction` | `u32`       |
//! | 4           | 12   | `_pad*`     | `u32` × 3   |
//!
//! Total = 16 bytes (multiple of 16 ✓).
//!
//! ## Direction encoding
//!
//! `direction`:
//! - `0` → `GammaDirection::SrgbToLinear` (sRGB → linear light)
//! - `1` → `GammaDirection::LinearToSrgb` (linear light → sRGB)
//!
//! Must stay in sync with the `if u.direction == 0u` branch in `gamma.wgsl`.

use std::mem;

use super::super::command_ir::GammaDirection;
use super::generated::gamma;

// ── Byte-identity gate ────────────────────────────────────────────────────────
//
// These const assertions are the GO/NO-GO check for the pilot.  If wgsl_bindgen
// generates a struct whose layout differs from the hand-written `GammaUniform`,
// this file will fail to compile — which is the correct signal to stop and report
// BLOCKED rather than silently absorb a layout divergence.

/// The generated `GammaUniforms` must be exactly 16 bytes — matching the WGSL
/// `GammaUniforms` struct and the former hand-written `GammaUniform`.
const _GENERATED_GAMMA_UNIFORMS_SIZE_CHECK: () = {
    assert!(mem::size_of::<gamma::GammaUniforms>() == 16);
};

/// The `direction` field must be at byte offset 0 — matching the WGSL layout
/// and the hand-written struct.
const _GENERATED_GAMMA_DIRECTION_OFFSET_CHECK: () = {
    assert!(mem::offset_of!(gamma::GammaUniforms, direction) == 0);
};

// ── Direction mapping ─────────────────────────────────────────────────────────

/// Map a [`GammaDirection`] to its WGSL `u.direction` integer.
///
/// **Must match the `if u.direction == …` constants in `gamma.wgsl`.**
/// This is an exhaustive match — adding a new variant without updating the
/// WGSL const block is a compile error (no `_` fallthrough).
pub(crate) fn gamma_direction_to_u32(dir: GammaDirection) -> u32 {
    match dir {
        GammaDirection::SrgbToLinear => 0,
        GammaDirection::LinearToSrgb => 1,
    }
}

// ── Pipeline ──────────────────────────────────────────────────────────────────

/// Render pipeline for the gamma transfer filter pass.
///
/// The bind-group layout is created from the generated `gamma::WgpuBindGroup0`
/// and is not stored here — callers use `gamma::WgpuBindGroup0::from_bindings`
/// at draw time, which creates a compatible bind group internally.
///
/// ## Blend state
///
/// `REPLACE` (no fixed-function blending): the fragment shader emits the full
/// premultiplied filtered texel directly.
#[allow(missing_debug_implementations)]
pub(crate) struct GammaPipeline {
    /// The single render pipeline (format-parametric at construction time).
    pub(crate) pipeline: wgpu::RenderPipeline,
}

impl GammaPipeline {
    /// Build the pipeline for `surface_format`.
    ///
    /// WGSL shader compilation happens here; a wgpu validation error surfaces
    /// at this call site, which the GPU construction test exercises.
    pub(crate) fn new(device: &wgpu::Device, surface_format: wgpu::TextureFormat) -> Self {
        // The bind-group layout is sourced from the generated bindings, which derive
        // it directly from the WGSL source — no hand-maintained descriptor.
        let bind_group_layout = gamma::WgpuBindGroup0::get_bind_group_layout(device);
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Gamma Pipeline Layout"),
            bind_group_layouts: &[Some(&bind_group_layout)],
            immediate_size: 0,
        });

        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Gamma Shader"),
            source: wgpu::ShaderSource::Wgsl(include_str!("../shaders/effects/gamma.wgsl").into()),
        });

        let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("Gamma Pipeline"),
            layout: Some(&pipeline_layout),
            vertex: wgpu::VertexState {
                module: &shader,
                entry_point: Some("vs_main"),
                // No vertex buffers: the VS synthesises 6 vertices from
                // `@builtin(vertex_index)`, forming a full-viewport quad.
                buffers: &[],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &shader,
                entry_point: Some("fs_main"),
                targets: &[Some(wgpu::ColorTargetState {
                    format: surface_format,
                    // REPLACE: the shader emits the full premultiplied result.
                    blend: Some(wgpu::BlendState::REPLACE),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                strip_index_format: None,
                front_face: wgpu::FrontFace::Ccw,
                cull_mode: None,
                polygon_mode: wgpu::PolygonMode::Fill,
                unclipped_depth: false,
                conservative: false,
            },
            depth_stencil: None,
            multisample: wgpu::MultisampleState {
                count: 1,
                mask: !0,
                alpha_to_coverage_enabled: false,
            },
            multiview_mask: None,
            cache: None,
        });

        Self { pipeline }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod cpu_tests {
    use super::{gamma, gamma_direction_to_u32};
    use crate::wgpu::command_ir::GammaDirection;

    /// The generated `GammaUniforms` struct must be 16 bytes to match the WGSL
    /// `GammaUniforms` block.  The `const` assert above already fires at compile
    /// time; this test makes the requirement visible in test output.
    #[test]
    fn gamma_uniforms_size_is_16_bytes() {
        assert_eq!(
            std::mem::size_of::<gamma::GammaUniforms>(),
            16,
            "GammaUniforms must be 16 bytes to match the WGSL GammaUniforms struct"
        );
    }

    /// The `direction` field must be at byte offset 0 — matching the WGSL layout.
    #[test]
    fn gamma_uniforms_direction_at_offset_0() {
        assert_eq!(
            std::mem::offset_of!(gamma::GammaUniforms, direction),
            0,
            "GammaUniforms::direction must be at offset 0"
        );
    }

    /// `gamma_direction_to_u32` maps each variant to a unique u32.
    #[test]
    fn direction_mapping_is_injective() {
        let srgb_to_linear = gamma_direction_to_u32(GammaDirection::SrgbToLinear);
        let linear_to_srgb = gamma_direction_to_u32(GammaDirection::LinearToSrgb);
        assert_ne!(
            srgb_to_linear, linear_to_srgb,
            "SrgbToLinear and LinearToSrgb must map to different integers"
        );
        assert_eq!(srgb_to_linear, 0, "SrgbToLinear must map to 0");
        assert_eq!(linear_to_srgb, 1, "LinearToSrgb must map to 1");
    }
}

#[cfg(all(test, feature = "enable-wgpu-tests"))]
mod gpu_construction_tests {
    use super::GammaPipeline;

    fn test_device() -> wgpu::Device {
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::new_without_display_handle());
        let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::LowPower,
            force_fallback_adapter: false,
            compatible_surface: None,
        }))
        .expect("a GPU adapter must be available on a GPU-enabled test host");
        let (device, _queue) =
            pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
                label: Some("GammaPipeline Test Device"),
                ..Default::default()
            }))
            .expect("GPU device creation succeeded when adapter was found");
        device
    }

    /// `GammaPipeline::new` completes without a wgpu validation error for
    /// `Rgba8Unorm`, proving the WGSL parses and the generated bind-group
    /// layout is valid.
    #[test]
    fn pipeline_construction_succeeds_for_rgba8unorm() {
        let device = test_device();
        let _pipeline = GammaPipeline::new(&device, wgpu::TextureFormat::Rgba8Unorm);
    }
}
