//! Auto-generated wgpu bindings for `morphology.wgsl`.
//!
//! This file is a thin `include!` bridge: the actual Rust source is generated
//! by `wgsl_bindgen` at build time and written into `OUT_DIR/morphology_generated.rs`.
//! Nothing in this file should be edited by hand — the generated content is the
//! authoritative source of truth for the morphology bind-group layout.
//!
//! The generated module `morphology` exposes:
//! - `MorphUniforms` — `#[repr(C, align(...))] Pod + Zeroable` uniform struct (48 bytes).
//! - `WgpuBindGroup0` / `WgpuBindGroup0Entries` — typed bind-group helpers.
//! - `MorphUniformsInit` — pad-free constructor (zero-fills `_pad*` automatically).
//!
//! ## Byte-identity guarantee (GO/NO-GO gate)
//!
//! The generated `MorphUniforms` struct MUST be layout-identical to the
//! former hand-written `MorphUniform` that it replaces:
//!
//! | Byte offset | Size | Field              |
//! |-------------|------|--------------------|
//! | 0           | 8    | `texture_size`     |
//! | 8           | 4    | `radius`           |
//! | 12          | 4    | `direction`        |
//! | 16          | 16   | `content_rect_uv`  |
//! | 32          | 4    | `op`               |
//! | 36          | 12   | `_pad*`            |
//!
//! Total = 48 bytes.  The `const` assertions in `pipeline.rs` enforce this at
//! compile time.

// JUSTIFICATION: all lints below apply to code generated by wgsl_bindgen 0.22.
// Names, derives, and patterns are controlled by the codegen tool, not by this
// crate.  Suppressing them here keeps the diagnostic surface clean without
// requiring changes to the generated content.
//
// - missing_docs / missing_debug_implementations: generated pub items lack docs
// - unsafe_code: bytemuck_impls emits `unsafe impl Pod + Zeroable`
// - unused / dead_code: wgsl_bindgen generates more items than this crate uses
// - non_snake_case / non_camel_case_types / non_upper_case_globals:
//   generated identifiers follow WGSL naming conventions, not Rust conventions
// - elided_lifetimes_in_paths: from_bindings(…) elides lifetime
// - unused_doc_comments: #[doc = "..."] on const exprs inside a const block
// - rust_2018_idioms: implied -W flag that fires on elided lifetimes
#[allow(
    missing_docs,
    missing_debug_implementations,
    unsafe_code,
    unused,
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    elided_lifetimes_in_paths,
    unused_doc_comments,
    clippy::all,
    clippy::pedantic
)]
pub(super) mod morphology_gen {
    include!(concat!(env!("OUT_DIR"), "/morphology_generated.rs"));
}

/// Re-export the generated `morphology` submodule at the path callers use.
pub(super) use morphology_gen::morphology;
