//! Wheel and trackpad scrolling.

use super::PointerInfo;
use super::value::{InputValueError, PointerPosition, Quantity, finite};
use crate::EventTime;
use crate::keyboard::Modifiers;

/// The unit a scroll distance is in, as the device reported it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ScrollUnit {
    /// Raw wheel rotation: one conventional detent is `1.0`; fractional
    /// rotation is preserved. The consumer applies the system notch policy.
    Detents,
    /// Already translated line distances. System lines-per-detent preferences
    /// have already been applied by the producer and must not be applied again.
    Lines,
    /// Logical pixels.
    Pixels,
    /// Pages: one page is the receiving viewport's extent.
    Pages,
}

/// How far one scroll event asks to scroll, in the unit the device reported.
///
/// The unit is kept to the consumer: translated lines use its authored distance,
/// pages use its viewport, and raw detents use the system notch preference
/// together with those distances. Positive values scroll down and right, so the scroll offset
/// grows: the W3C `WheelEvent` convention, whatever the platform's own sign.
///
/// # Examples
///
/// ```
/// use flui_platform_api::pointer::{ScrollDelta, ScrollUnit};
///
/// let notch = ScrollDelta::try_new(ScrollUnit::Detents, 0.0, 1.0)?;
/// assert_eq!((notch.unit(), notch.x(), notch.y()), (ScrollUnit::Detents, 0.0, 1.0));
/// assert!(ScrollDelta::try_new(ScrollUnit::Pixels, f64::NAN, 0.0).is_err());
/// # Ok::<(), flui_platform_api::pointer::InputValueError>(())
/// ```
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ScrollDelta {
    unit: ScrollUnit,
    x: f64,
    y: f64,
}

impl ScrollDelta {
    /// A distance of `x` right and `y` down, in `unit`.
    ///
    /// # Errors
    ///
    /// [`InputValueError::NonFinite`] when either component is NaN or infinite. A producer
    /// whose event carries a phase still delivers it, with [`ScrollDelta::zero`].
    pub fn try_new(unit: ScrollUnit, x: f64, y: f64) -> Result<Self, InputValueError> {
        Ok(Self {
            unit,
            x: finite(Quantity::ScrollDelta, x)?,
            y: finite(Quantity::ScrollDelta, y)?,
        })
    }

    /// No distance, in `unit`.
    #[must_use]
    pub const fn zero(unit: ScrollUnit) -> Self {
        Self {
            unit,
            x: 0.0,
            y: 0.0,
        }
    }

    /// The unit the device reported.
    #[must_use]
    pub const fn unit(self) -> ScrollUnit {
        self.unit
    }

    /// The distance to the right, in [`unit`](Self::unit).
    #[must_use]
    pub const fn x(self) -> f64 {
        self.x
    }

    /// The distance down, in [`unit`](Self::unit).
    #[must_use]
    pub const fn y(self) -> f64 {
        self.y
    }
}

/// Whether the device scrolls in discrete notches or continuously.
///
/// A notched wheel's tick is a jump a scrollable may animate; a precise device (a trackpad, a
/// free-spinning or high-resolution wheel) already moves smoothly, and its delta is applied as
/// is.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[non_exhaustive]
pub enum ScrollPrecision {
    /// The platform does not say.
    #[default]
    Unknown,
    /// Discrete notches.
    Notched,
    /// Continuous, pixel-precise input.
    Precise,
}

/// Where a scroll event sits in a scroll gesture.
///
/// A trackpad or touch-driven scroll is a gesture: the fingers begin, move and lift, and the
/// platform may then continue with momentum of its own. Gesture and momentum are one enum, so
/// "fingers down" and "momentum" cannot both be claimed. A wheel tick outside any gesture has
/// no phase ([`ScrollEvent::phase`] is `None`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ScrollPhase {
    /// The fingers touched down and scrolling began.
    Began,
    /// The fingers moved.
    Changed,
    /// The fingers lifted.
    Ended,
    /// The platform took the gesture back; a consumer ends it without a fling.
    Cancelled,
    /// The platform started scrolling on with momentum after the fingers lifted.
    MomentumBegan,
    /// A momentum step generated by the platform, not by the user's fingers.
    MomentumChanged,
    /// The platform's momentum ran out or was stopped.
    MomentumEnded,
}

/// A wheel or trackpad scroll over a point in the window.
///
/// Built with [`ScrollEvent::new`] and the `with_*` methods.
///
/// # Examples
///
/// ```
/// use flui_foundation::geometry::Point;
/// use flui_platform_api::EventTime;
/// use flui_platform_api::pointer::{
///     PointerId, PointerInfo, PointerKind, PointerPosition, ScrollDelta, ScrollEvent,
///     ScrollPhase, ScrollPrecision, ScrollUnit,
/// };
///
/// let trackpad = PointerInfo::new(PointerId::try_from(1_u64)?, PointerKind::Mouse);
/// let at = PointerPosition::try_new(Point::new(100.0, 40.0))?;
/// let scroll = ScrollEvent::new(
///     trackpad,
///     EventTime::from_nanos(5),
///     at,
///     ScrollDelta::try_new(ScrollUnit::Pixels, 0.0, 12.5)?,
/// )
/// .with_precision(ScrollPrecision::Precise)
/// .with_phase(ScrollPhase::Changed);
/// assert_eq!(scroll.delta.unit(), ScrollUnit::Pixels);
/// # Ok::<(), Box<dyn std::error::Error>>(())
/// ```
#[derive(Debug, Clone, Copy, PartialEq)]
#[non_exhaustive]
pub struct ScrollEvent {
    /// The device that scrolled. A wheel scroll reports the mouse pointer it came from.
    pub pointer: PointerInfo,
    /// When the platform observed the scroll.
    pub time: EventTime,
    /// Where the pointer was: what the scroll is hit-tested at.
    pub position: PointerPosition,
    /// How far to scroll, in the unit the device reported.
    pub delta: ScrollDelta,
    /// Notched or precise input.
    pub precision: ScrollPrecision,
    /// Where the event sits in a scroll gesture; `None` for a wheel tick outside one.
    pub phase: Option<ScrollPhase>,
    /// The modifiers held.
    pub modifiers: Modifiers,
}

impl ScrollEvent {
    /// A scroll of `delta` at `position`, with unknown precision, no phase and no modifiers.
    #[must_use]
    pub const fn new(
        pointer: PointerInfo,
        time: EventTime,
        position: PointerPosition,
        delta: ScrollDelta,
    ) -> Self {
        Self {
            pointer,
            time,
            position,
            delta,
            precision: ScrollPrecision::Unknown,
            phase: None,
            modifiers: Modifiers::NONE,
        }
    }

    /// This event with `precision`.
    #[must_use]
    pub const fn with_precision(self, precision: ScrollPrecision) -> Self {
        Self { precision, ..self }
    }

    /// This event at `phase` of a scroll gesture.
    #[must_use]
    pub const fn with_phase(self, phase: ScrollPhase) -> Self {
        Self {
            phase: Some(phase),
            ..self
        }
    }

    /// This event with `modifiers` held.
    #[must_use]
    pub const fn with_modifiers(self, modifiers: Modifiers) -> Self {
        Self { modifiers, ..self }
    }
}
