//! Auto-generated wgpu bindings for `color_matrix.wgsl`.
//!
//! This file is a thin `include!` bridge: the actual Rust source is generated
//! by `wgsl_bindgen` at build time and written into `OUT_DIR/color_matrix_generated.rs`.
//! Nothing in this file should be edited by hand — the generated content is the
//! authoritative source of truth for the color_matrix bind-group layout.
//!
//! The generated module `color_matrix` exposes:
//! - `ColorMatrixUniforms` — `#[repr(C, align(16))] Pod + Zeroable` uniform struct (80 bytes).
//! - `WgpuBindGroup0` / `WgpuBindGroup0Entries` — typed bind-group helpers.
//! - `ColorMatrixUniformsInit` — pad-free constructor.
//!
//! ## Type mapping: `mat4x4<f32>` → `glam::Mat4`
//!
//! `wgsl_bindgen` with `GlamWgslTypeMap` maps the WGSL `mat4x4<f32>` to
//! `glam::Mat4`.  `glam::Mat4` is `#[repr(C)]` and stores four `Vec4` columns
//! in declaration order — identical memory layout to `[[f32; 4]; 4]` (64 bytes,
//! align 4).  The byte-identity assertions in `pipeline.rs` enforce this.
//!
//! ## Byte-identity guarantee (GO/NO-GO gate)
//!
//! The generated `ColorMatrixUniforms` struct MUST be layout-identical to the
//! former hand-written `ColorMatrixUniform` that it replaces:
//!
//! | Byte offset | Size | Field    | WGSL member   |
//! |-------------|------|----------|---------------|
//! | 0           | 64   | `m`      | `mat4x4<f32>` |
//! | 64          | 16   | `offset` | `vec4<f32>`   |
//!
//! Total = 80 bytes.  The `const` assertions in `pipeline.rs` enforce this at
//! compile time.

// JUSTIFICATION: all lints below apply to code generated by wgsl_bindgen 0.22.
// Names, derives, and patterns are controlled by the codegen tool, not by this
// crate.  Suppressing them here keeps the diagnostic surface clean without
// requiring changes to the generated content.
//
// - missing_docs / missing_debug_implementations: generated pub items lack docs
// - unsafe_code: bytemuck_impls emits `unsafe impl Pod + Zeroable`
// - unused / dead_code: wgsl_bindgen generates more items than this crate uses
// - non_snake_case / non_camel_case_types / non_upper_case_globals:
//   generated identifiers follow WGSL naming conventions, not Rust conventions
// - elided_lifetimes_in_paths: from_bindings(…) elides lifetime
// - unused_doc_comments: #[doc = "..."] on const exprs inside a const block
// - rust_2018_idioms: implied -W flag that fires on elided lifetimes
#[allow(
    missing_docs,
    missing_debug_implementations,
    unsafe_code,
    unused,
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    elided_lifetimes_in_paths,
    unused_doc_comments,
    clippy::all,
    clippy::pedantic
)]
pub(super) mod color_matrix_gen {
    include!(concat!(env!("OUT_DIR"), "/color_matrix_generated.rs"));
}

/// Re-export the generated `color_matrix` submodule at the path callers use.
pub(super) use color_matrix_gen::color_matrix;
