//! Host-side scene plugin loader.
//!
//! Loads a scene plugin shared library at runtime. Supports two symbol
//! conventions:
//!
//! - **App plugin** (`flui_app_build` / `flui_app_version` / `flui_app_drop`) —
//!   generated by `app_plugin!`, runs full widget pipeline inside the plugin
//! - **Scene plugin** (`flui_scene_build` / `flui_scene_version` /
//!   `flui_scene_drop`) — generated by `scene_plugin!`, raw scene-building
//!   function
//!
//! The loader tries `flui_app_build` first and falls back to
//! `flui_scene_build`.
//!
//! Cross-platform: uses [`DynLib`] for loading (dlopen on Unix, LoadLibraryW on
//! Windows).

use std::path::Path;

use flui_layer::Scene;

use crate::dynlib::{self, DynLib};

/// Function pointer: `flui_scene_build(width, height) -> *mut c_void`
type BuildSceneFn = unsafe extern "C" fn(f32, f32) -> *mut std::ffi::c_void;

/// Function pointer: `flui_scene_version() -> u32`
type SceneVersionFn = extern "C" fn() -> u32;

/// Function pointer: `flui_scene_drop(ptr)`
type SceneDropFn = unsafe extern "C" fn(*mut std::ffi::c_void);

/// Function pointer: `flui_scene_free(ptr)` — deallocate without dropping.
type SceneFreeFn = unsafe extern "C" fn(*mut std::ffi::c_void);

/// Function pointer: `flui_scene_abi_token() -> u64`
type AbiTokenFn = extern "C" fn() -> u64;

/// One resolved symbol family (`flui_app_*` or `flui_scene_*`), token-checked.
struct ResolvedSceneFamily {
    build_fn: BuildSceneFn,
    free_fn: SceneFreeFn,
    drop_fn: Option<SceneDropFn>,
    version: u32,
}

/// Which symbol convention the loaded plugin uses.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PluginKind {
    /// `flui_app_build` — widget-based plugin (from `app_plugin!`)
    App,
    /// `flui_scene_build` — raw scene plugin (from `scene_plugin!`)
    Scene,
}

/// A loaded scene plugin that can build `Scene` objects via dynamic loading.
///
/// Supports both symbol conventions:
/// - `app_plugin!` symbols: `flui_app_build` / `flui_app_version` /
///   `flui_app_drop`
/// - `scene_plugin!` symbols: `flui_scene_build` / `flui_scene_version` /
///   `flui_scene_drop`
///
/// The loader tries `flui_app_build` first and falls back to
/// `flui_scene_build`.
///
/// # Lifecycle
///
/// ```text
/// ScenePlugin::load(path)
///     ↓
/// plugin.build_scene(w, h) → Option<Scene>   (can call many times;
///                                              None = skip this frame)
///     ↓
/// plugin.has_update()  →  true when library file changed on disk
///     ↓
/// plugin.unload()  —or—  drop(plugin)
/// ```
#[allow(missing_debug_implementations)]
pub struct ScenePlugin {
    lib: DynLib,
    build_fn: BuildSceneFn,
    /// The deallocate-only entry (`flui_*_free`): releases the box a build
    /// call returned after the host has moved the `Scene` value out, so the
    /// memory is freed by the image that allocated it. Mandatory — `load`
    /// refuses a plugin without it.
    free_fn: SceneFreeFn,
    /// The drop-and-deallocate entry (`flui_*_drop`), for a scene the host
    /// decides not to consume. Currently every host path consumes, so this is
    /// resolved-but-idle; kept because it is the correct disposal for an
    /// unconsumed pointer.
    #[allow(dead_code)]
    drop_fn: Option<SceneDropFn>,
    kind: PluginKind,
    version: u32,
    mtime: u64,
}

impl ScenePlugin {
    /// Try to load a plugin from the given shared library path.
    ///
    /// Tries `flui_app_build` symbols first (widget-based `app_plugin!`),
    /// then falls back to `flui_scene_build` (raw `scene_plugin!`).
    ///
    /// Returns `None` if the file doesn't exist, loading fails, or neither
    /// symbol set is found.
    pub fn load(lib_path: impl AsRef<Path>) -> Option<Self> {
        let lib_path = lib_path.as_ref();
        let lib = DynLib::open(lib_path)?;

        // SAFETY: `lib` was just opened and stays alive for this block, which
        // is `try_resolve`'s stated requirement. The symbol-name/type pairs
        // below are the plugin ABI this crate defines, so a library built by
        // the matching macro exports them with these signatures.
        #[allow(unsafe_code)]
        unsafe {
            // Try app_plugin! symbols first (flui_app_build)
            if let Some(resolved) = Self::try_resolve(&lib, "flui_app") {
                let mtime = dynlib::file_mtime(lib_path);
                tracing::info!(
                    "App plugin loaded (version {}) from {}",
                    resolved.version,
                    lib_path.display()
                );
                return Some(ScenePlugin {
                    lib,
                    build_fn: resolved.build_fn,
                    free_fn: resolved.free_fn,
                    drop_fn: resolved.drop_fn,
                    kind: PluginKind::App,
                    version: resolved.version,
                    mtime,
                });
            }

            // Fall back to scene_plugin! symbols (flui_scene_build)
            if let Some(resolved) = Self::try_resolve(&lib, "flui_scene") {
                let mtime = dynlib::file_mtime(lib_path);
                tracing::info!(
                    "Scene plugin loaded (version {}) from {}",
                    resolved.version,
                    lib_path.display()
                );
                return Some(ScenePlugin {
                    lib,
                    build_fn: resolved.build_fn,
                    free_fn: resolved.free_fn,
                    drop_fn: resolved.drop_fn,
                    kind: PluginKind::Scene,
                    version: resolved.version,
                    mtime,
                });
            }

            tracing::trace!("No plugin symbols found in {}", lib_path.display());
            None
        }
    }

    /// Try to resolve one symbol family (`flui_app` / `flui_scene`) from the
    /// library, enforcing the ABI handshake.
    ///
    /// Refuses (returns `None`, with a log) when the family's `_free` or
    /// `_abi_token` symbol is missing — a library that predates them cannot
    /// discharge the ownership contract — or when the plugin's token differs
    /// from the host's (different compiler, source revision, or crate
    /// version: `repr(Rust)` layout agreement is then unestablished).
    ///
    /// # Safety
    ///
    /// Caller must ensure `lib` is a valid loaded library.
    #[allow(unsafe_code)]
    unsafe fn try_resolve(lib: &DynLib, family: &str) -> Option<ResolvedSceneFamily> {
        // SAFETY: edition 2024 makes unsafe-fn bodies safe by default, so the
        // calls still need their own block. The caller guarantees `lib` is a
        // live library, and each symbol/type pair is the ABI this crate
        // declares for that name.
        //
        // On null: only `build_ptr` is checked at its use site. The other
        // transmutes come straight out of `lib.symbol(..)` — sound because
        // `get_symbol` maps a null `dlsym` result to `None`, so a `Some` is
        // already non-null.
        unsafe {
            let build_ptr = lib.symbol(&format!("{family}_build"))?;
            if build_ptr.is_null() {
                return None;
            }
            let build_fn: BuildSceneFn = std::mem::transmute(build_ptr);

            // ABI handshake FIRST: nothing else about the library may be
            // trusted (not even calling its version fn is interesting) until
            // the layout premise is established.
            let Some(token_ptr) = lib.symbol(&format!("{family}_abi_token")) else {
                tracing::error!(
                    family,
                    path = %lib.path().display(),
                    "plugin refused: no ABI-token symbol — rebuild it against \
                     this tree (the ownership-safe plugin ABI requires it)"
                );
                return None;
            };
            let token_fn: AbiTokenFn = std::mem::transmute(token_ptr);
            let plugin_token = token_fn();
            let host_token = crate::abi_token();
            if plugin_token != host_token {
                tracing::error!(
                    family,
                    plugin_token,
                    host_token,
                    path = %lib.path().display(),
                    "plugin refused: ABI token mismatch — host and plugin \
                     were built by different compilers or source revisions; \
                     rebuild both from one worktree with one toolchain"
                );
                return None;
            }

            let Some(free_ptr) = lib.symbol(&format!("{family}_free")) else {
                tracing::error!(
                    family,
                    path = %lib.path().display(),
                    "plugin refused: no deallocate-only symbol — rebuild it \
                     against this tree"
                );
                return None;
            };
            let free_fn: SceneFreeFn = std::mem::transmute(free_ptr);

            let drop_fn: Option<SceneDropFn> = lib
                .symbol(&format!("{family}_drop"))
                .map(|ptr| std::mem::transmute::<*mut std::ffi::c_void, SceneDropFn>(ptr));

            let version = lib.symbol(&format!("{family}_version")).map_or(0, |ptr| {
                let version_fn: SceneVersionFn = std::mem::transmute(ptr);
                version_fn()
            });

            Some(ResolvedSceneFamily {
                build_fn,
                free_fn,
                drop_fn,
                version,
            })
        }
    }

    /// Build a scene by calling the plugin's build function.
    ///
    /// The plugin allocates a `Box<Scene>` and returns it raw; this method
    /// moves the `Scene` value out with `ptr::read` and hands the emptied box
    /// back to the plugin's `flui_*_free`, so allocation and deallocation
    /// both happen inside the plugin image. Layout agreement between the two
    /// `repr(Rust)` compilations is established at `load` by the ABI-token
    /// handshake (same compiler, same crate revision — see [`crate::abi_token`]).
    ///
    /// Returns `None` when this is a [`PluginKind::App`] plugin and the
    /// build function refused the call — the wrong-thread case
    /// `app_plugin!`'s generated `flui_app_build` documents (see its
    /// "Thread affinity" docs): the pipeline is pinned to whichever thread
    /// first drove it, and every other thread gets a null pointer back
    /// instead of a Scene. Treat that exactly like "no plugin loaded": skip
    /// this frame, keep the plugin, try again later — never as a caller
    /// error. A [`PluginKind::Scene`] plugin has no such refusal path, so a
    /// null return there stays a hard contract violation (`assert!`s below).
    ///
    /// # Safety
    ///
    /// One obligation remains with the caller, and it is why this stays an
    /// `unsafe fn`: the returned `Scene` holds `Box<dyn FnOnce>` and
    /// `Arc<dyn Any>` whose vtables live in the plugin image, so the caller
    /// must drop it BEFORE the library is unloaded. No lifetime ties the
    /// scene to the [`DynLib`]; dropping it after `dlclose` is a
    /// use-after-free of code. Development-only tooling either way. This
    /// obligation applies only to a `Some` return — a `None` (skipped frame)
    /// owns nothing.
    #[allow(unsafe_code)]
    pub unsafe fn build_scene(&self, width: f32, height: f32) -> Option<Scene> {
        // SAFETY: `build_fn`/`free_fn` were resolved from the `DynLib` this
        // struct owns, which outlives the call. The plugin macro returns
        // `Box::into_raw(Box::new(scene))`, so a non-null `ptr` addresses one
        // live, initialized `Scene`; the load-time token handshake establishes
        // that both compilations agree on `Scene`'s layout, making the
        // `ptr::read` a valid move. After the read the box's contents are
        // logically moved out, and `free_fn` deallocates without dropping (it
        // reads the slot as `MaybeUninit<Scene>`), in the image that
        // allocated it — no cross-image allocator or drop-glue mismatch
        // remains. A null `ptr` never reaches `ptr::read`/`free_fn` at all.
        #[allow(unsafe_code)]
        unsafe {
            let ptr = (self.build_fn)(width, height);
            if ptr.is_null() {
                let build_symbol = match self.kind {
                    PluginKind::App => "flui_app_build",
                    PluginKind::Scene => "flui_scene_build",
                };
                assert!(
                    self.kind == PluginKind::App,
                    "{build_symbol} returned null — scene_plugin! has no \
                     legitimate null path (only app_plugin!'s wrong-thread \
                     refusal does)"
                );
                return None;
            }
            let scene = std::ptr::read(ptr.cast::<Scene>());
            (self.free_fn)(ptr);
            Some(scene)
        }
    }

    /// Check if the shared library file on disk has been modified since it was
    /// loaded.
    pub fn has_update(&self) -> bool {
        let current = dynlib::file_mtime(self.lib.path());
        current != self.mtime
    }

    /// Unload the plugin library.
    ///
    /// This is equivalent to dropping the `ScenePlugin`, but logs the unload
    /// for diagnostics.
    pub fn unload(self) {
        let label = match self.kind {
            PluginKind::App => "App",
            PluginKind::Scene => "Scene",
        };
        tracing::info!("{} plugin unloaded (was version {})", label, self.version);
        // DynLib::drop handles the actual library close
    }

    /// The file path this plugin was loaded from.
    pub fn path(&self) -> &Path {
        self.lib.path()
    }

    /// The version reported by the plugin's version function.
    pub fn version(&self) -> u32 {
        self.version
    }

    /// Which symbol convention this plugin uses.
    pub fn kind(&self) -> PluginKind {
        self.kind
    }
}
