//! Host-side scene plugin loader.
//!
//! Loads a scene plugin shared library at runtime. Supports two symbol
//! conventions:
//!
//! - **App plugin** (`flui_app_build` / `flui_app_version` / `flui_app_drop`) —
//!   generated by [`app_plugin!`], runs full widget pipeline inside the plugin
//! - **Scene plugin** (`flui_scene_build` / `flui_scene_version` /
//!   `flui_scene_drop`) — generated by [`scene_plugin!`], raw scene-building
//!   function
//!
//! The loader tries `flui_app_build` first and falls back to
//! `flui_scene_build`.
//!
//! Cross-platform: uses [`DynLib`] for loading (dlopen on Unix, LoadLibraryW on
//! Windows).

use std::path::Path;

use flui_layer::Scene;

use crate::dynlib::{self, DynLib};

/// Function pointer: `flui_scene_build(width, height) -> *mut c_void`
type BuildSceneFn = unsafe extern "C" fn(f32, f32) -> *mut std::ffi::c_void;

/// Function pointer: `flui_scene_version() -> u32`
type SceneVersionFn = extern "C" fn() -> u32;

/// Function pointer: `flui_scene_drop(ptr)`
type SceneDropFn = unsafe extern "C" fn(*mut std::ffi::c_void);

/// Which symbol convention the loaded plugin uses.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PluginKind {
    /// `flui_app_build` — widget-based plugin (from `app_plugin!`)
    App,
    /// `flui_scene_build` — raw scene plugin (from `scene_plugin!`)
    Scene,
}

/// A loaded scene plugin that can build `Scene` objects via dynamic loading.
///
/// Supports both symbol conventions:
/// - `app_plugin!` symbols: `flui_app_build` / `flui_app_version` /
///   `flui_app_drop`
/// - `scene_plugin!` symbols: `flui_scene_build` / `flui_scene_version` /
///   `flui_scene_drop`
///
/// The loader tries `flui_app_build` first and falls back to
/// `flui_scene_build`.
///
/// # Lifecycle
///
/// ```text
/// ScenePlugin::load(path)
///     ↓
/// plugin.build_scene(w, h) → Scene   (can call many times)
///     ↓
/// plugin.has_update()  →  true when library file changed on disk
///     ↓
/// plugin.unload()  —or—  drop(plugin)
/// ```
#[allow(missing_debug_implementations)]
pub struct ScenePlugin {
    lib: DynLib,
    build_fn: BuildSceneFn,
    #[allow(dead_code)]
    drop_fn: Option<SceneDropFn>,
    kind: PluginKind,
    version: u32,
    mtime: u64,
}

impl ScenePlugin {
    /// Try to load a plugin from the given shared library path.
    ///
    /// Tries `flui_app_build` symbols first (widget-based `app_plugin!`),
    /// then falls back to `flui_scene_build` (raw `scene_plugin!`).
    ///
    /// Returns `None` if the file doesn't exist, loading fails, or neither
    /// symbol set is found.
    pub fn load(lib_path: impl AsRef<Path>) -> Option<Self> {
        let lib_path = lib_path.as_ref();
        let lib = DynLib::open(lib_path)?;

        #[allow(unsafe_code)]
        unsafe {
            // Try app_plugin! symbols first (flui_app_build)
            if let Some(result) =
                Self::try_resolve(&lib, "flui_app_build", "flui_app_version", "flui_app_drop")
            {
                let mtime = dynlib::file_mtime(lib_path);
                tracing::info!(
                    "App plugin loaded (version {}) from {}",
                    result.2,
                    lib_path.display()
                );
                return Some(ScenePlugin {
                    lib,
                    build_fn: result.0,
                    drop_fn: result.1,
                    kind: PluginKind::App,
                    version: result.2,
                    mtime,
                });
            }

            // Fall back to scene_plugin! symbols (flui_scene_build)
            if let Some(result) = Self::try_resolve(
                &lib,
                "flui_scene_build",
                "flui_scene_version",
                "flui_scene_drop",
            ) {
                let mtime = dynlib::file_mtime(lib_path);
                tracing::info!(
                    "Scene plugin loaded (version {}) from {}",
                    result.2,
                    lib_path.display()
                );
                return Some(ScenePlugin {
                    lib,
                    build_fn: result.0,
                    drop_fn: result.1,
                    kind: PluginKind::Scene,
                    version: result.2,
                    mtime,
                });
            }

            tracing::trace!("No plugin symbols found in {}", lib_path.display());
            None
        }
    }

    /// Try to resolve a set of build/version/drop symbols from the library.
    ///
    /// Returns `(build_fn, drop_fn, version)` if the build symbol is found.
    ///
    /// # Safety
    ///
    /// Caller must ensure `lib` is a valid loaded library.
    #[allow(unsafe_code)]
    unsafe fn try_resolve(
        lib: &DynLib,
        build_sym: &str,
        version_sym: &str,
        drop_sym: &str,
    ) -> Option<(BuildSceneFn, Option<SceneDropFn>, u32)> {
        unsafe {
            let build_ptr = lib.symbol(build_sym)?;
            if build_ptr.is_null() {
                return None;
            }
            let build_fn: BuildSceneFn = std::mem::transmute(build_ptr);

            let drop_fn: Option<SceneDropFn> =
                lib.symbol(drop_sym).map(|ptr| std::mem::transmute(ptr));

            let version = lib.symbol(version_sym).map_or(0, |ptr| {
                let version_fn: SceneVersionFn = std::mem::transmute(ptr);
                version_fn()
            });

            Some((build_fn, drop_fn, version))
        }
    }

    /// Build a scene by calling the plugin's `flui_scene_build` function.
    ///
    /// The plugin allocates a `Box<Scene>` and returns it as a raw pointer.
    /// This method takes ownership back via `Box::from_raw`.
    pub fn build_scene(&self, width: f32, height: f32) -> Scene {
        #[allow(unsafe_code)]
        unsafe {
            let ptr = (self.build_fn)(width, height);
            assert!(!ptr.is_null(), "flui_scene_build returned null");
            *Box::from_raw(ptr.cast::<Scene>())
        }
    }

    /// Check if the shared library file on disk has been modified since it was
    /// loaded.
    pub fn has_update(&self) -> bool {
        let current = dynlib::file_mtime(self.lib.path());
        current != self.mtime
    }

    /// Unload the plugin library.
    ///
    /// This is equivalent to dropping the `ScenePlugin`, but logs the unload
    /// for diagnostics.
    pub fn unload(self) {
        let label = match self.kind {
            PluginKind::App => "App",
            PluginKind::Scene => "Scene",
        };
        tracing::info!("{} plugin unloaded (was version {})", label, self.version);
        // DynLib::drop handles the actual library close
    }

    /// The file path this plugin was loaded from.
    pub fn path(&self) -> &Path {
        self.lib.path()
    }

    /// The version reported by the plugin's version function.
    pub fn version(&self) -> u32 {
        self.version
    }

    /// Which symbol convention this plugin uses.
    pub fn kind(&self) -> PluginKind {
        self.kind
    }
}
