//! Auto-generated wgpu bindings for `advanced_blend.wgsl`.
//!
//! This file is a thin `include!` bridge: the actual Rust source is generated
//! by `wgsl_bindgen` at build time and written into
//! `OUT_DIR/advanced_blend_generated.rs`.  Nothing in this file should be edited
//! by hand — the generated content is the authoritative source of truth for the
//! advanced-blend bind-group layout.
//!
//! The generated module `advanced_blend` exposes:
//! - `BlendUniforms` — `#[repr(C)] Pod + Zeroable` uniform struct (80 bytes).
//! - `WgpuBindGroup0` / `WgpuBindGroup0Entries` — typed bind-group helpers.
//! - `BlendUniforms::new` — pad-free constructor (zero-fills `_pad*` automatically).
//!
//! ## `#import blend_helpers`
//!
//! `advanced_blend.wgsl` carries `#import blend_helpers::{…}`.  `wgsl_bindgen`
//! resolves it at codegen time (`blend_helpers.wgsl` is co-located in `shaders/`,
//! which is this shader's workspace root) so it can parse the shader and emit
//! the bindings.  The runtime pipeline still composes the shader module via
//! `compose_wgsl_shader`.
//!
//! ## Byte-identity guarantee (GO/NO-GO gate)
//!
//! The generated `BlendUniforms` struct MUST be layout-identical to the former
//! hand-written `BlendUniformData` that it replaces:
//!
//! | Byte offset | Size | Field           |
//! |-------------|------|-----------------|
//! | 0           | 16   | `op_bounds`     |
//! | 16          | 8    | `viewport_size` |
//! | 24          | 8    | `copy_origin`   |
//! | 32          | 8    | `copy_extent`   |
//! | 40          | 4    | `opacity`       |
//! | 44          | 4    | `_pad0`         |
//! | 48          | 12   | `tint_rgb`      |
//! | 60          | 4    | `mode`          |
//! | 64          | 8    | `src_uv_min`    |
//! | 72          | 8    | `src_uv_max`    |
//!
//! Total = 80 bytes.  The `const` assertions in `pipeline.rs` enforce this at
//! compile time.

// JUSTIFICATION: all lints below apply to code generated by wgsl_bindgen 0.22.
// Names, derives, and patterns are controlled by the codegen tool, not by this
// crate.  Suppressing them here keeps the diagnostic surface clean without
// requiring changes to the generated content.  (Same rationale as
// `blur/generated.rs` — see that file for the per-lint breakdown.)
#[allow(
    missing_docs,
    missing_debug_implementations,
    unsafe_code,
    unused,
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    elided_lifetimes_in_paths,
    unused_doc_comments,
    clippy::all,
    clippy::pedantic
)]
pub(super) mod advanced_blend_gen {
    include!(concat!(env!("OUT_DIR"), "/advanced_blend_generated.rs"));
}

/// Re-export the generated `advanced_blend` submodule at the path callers use.
pub(super) use advanced_blend_gen::advanced_blend;
