//! Flutter-parity hot-reload project template.
//!
//! Emits the three-crate host/worker/types layout the reload protocol requires
//! (see `docs/designs/2026-06-28-flutter-parity-hot-reload.md` §5): the host
//! binary owns the element tree — and therefore every `State` — while the
//! reloadable worker `cdylib` holds only the `build()` implementations, so a
//! code change to the worker preserves state across a reload.
//!
//! The generated project is a workspace because cargo must be able to build the
//! worker and the host independently: `flui run` watches the worker crate and
//! rebuilds only it, leaving the running host untouched.

use crate::error::{CliResult, ResultExt};
use std::fs;
use std::path::Path;

/// A `flui-*` dependency line pointing at the local source tree or a version.
///
/// `members_deep` is how many directories the depending manifest sits below the
/// repository root. The hot-reload sub-crates are one level below the generated
/// workspace root, which itself sits one level below the repo root (the
/// `target/<name>` layout `flui create --local` documents), so they pass `3`.
/// A plain template's manifest is `target/<name>` itself and passes `2`.
fn workspace_dep(crate_name: &str, local: bool, members_deep: usize) -> String {
    if local {
        let up = "../".repeat(members_deep);
        format!("{{ path = \"{up}crates/{crate_name}\" }}")
    } else {
        // FLUI is not published to crates.io; the version branch is the shape
        // for when it is, matching the other templates.
        let version = env!("CARGO_PKG_VERSION");
        format!("{{ version = \"{version}\" }}")
    }
}

/// A dependency on a sibling crate inside the generated workspace.
///
/// Unlike `workspace_dep`, these crates are not published and are not under the
/// FLUI repo's `crates/` — they are workspace members named by their directory,
/// so the `--local` path is the sibling itself and the published branch is the
/// workspace's own `0.1.0` version.
fn member_dep(sibling: &str) -> String {
    format!("{{ path = \"../{sibling}\" }}")
}

/// Append a feature list to a dependency inline-table string.
fn with_features(dep: &str, features: &[&str]) -> String {
    let list = features
        .iter()
        .map(|f| format!("\"{f}\""))
        .collect::<Vec<_>>()
        .join(", ");
    // `{ path = "..." }` → `{ path = "...", features = ["..."] }`
    let trimmed = dep.trim_end();
    if let Some(stripped) = trimmed.strip_suffix('}') {
        format!("{}, features = [{list}] }}", stripped.trim_end())
    } else {
        dep.to_string()
    }
}

pub fn generate(dir: &Path, name: &str, org: &str, local: bool) -> CliResult<()> {
    let lib_name = name.replace('-', "_");
    let types_package = format!("{name}-types");
    let worker_package = format!("{name}-logic");
    let host_package = format!("{name}-host");
    let worker_lib = format!("{lib_name}_logic");

    generate_root_workspace(dir, &types_package, &worker_package, &host_package)?;
    generate_flui_config(dir, name, org, &host_package, &worker_package, &worker_lib)?;
    generate_types(dir, &types_package, local)?;
    generate_logic(dir, &types_package, &worker_package, &worker_lib, local)?;
    generate_host(
        dir,
        name,
        &types_package,
        &host_package,
        &worker_package,
        &worker_lib,
        local,
    )?;
    generate_readme(dir, name, &types_package, &worker_package, &host_package)?;

    Ok(())
}

fn generate_root_workspace(
    dir: &Path,
    types_package: &str,
    worker_package: &str,
    host_package: &str,
) -> CliResult<()> {
    let version = env!("CARGO_PKG_VERSION");
    let content = format!(
        r#"# FLUI hot-reload workspace (generated by `flui create --hot-reload` v{version}).
#
# Three crates, one workspace:
#   {types_package}/  — shared types + persistent State (linked into host + worker)
#   {worker_package}/ — reloadable build() code (cdylib; the reload target)
#   {host_package}/   — window, GPU, element tree; loads the worker (bin)
[workspace]
resolver = "3"
members = ["{types_package}", "{worker_package}", "{host_package}"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"

[workspace.dependencies]
tracing = "0.1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "debuginfo"
"#
    );
    fs::write(dir.join("Cargo.toml"), content).context("Failed to create workspace Cargo.toml")?;
    Ok(())
}

fn generate_flui_config(
    dir: &Path,
    name: &str,
    org: &str,
    host_package: &str,
    worker_package: &str,
    worker_lib: &str,
) -> CliResult<()> {
    // `logic_watch` / `types_watch` are relative to this `flui.toml`, and name
    // the directories whose edits trigger a worker rebuild (hot reload) versus
    // a host restart (hot restart, because the type layout changed).
    let types_package = format!("{name}-types");
    let content = format!(
        r#"[app]
name = "{name}"
version = "0.1.0"
organization = "{org}"

[build]
target_platforms = ["windows", "linux", "macos"]

[assets]
directories = ["assets"]

# `flui run` reads this section and drives the worker rebuild loop. Deleting it
# degrades `flui run` to a process-restart watcher (no state preservation).
[hot_reload]
host_package = "{host_package}"
worker_package = "{worker_package}"
worker_lib = "{worker_lib}"
logic_watch = "{worker_package}/src"
types_watch = "{types_package}/src"
"#
    );
    fs::write(dir.join("flui.toml"), content).context("Failed to create flui.toml")?;
    Ok(())
}

fn generate_types(dir: &Path, types_package: &str, local: bool) -> CliResult<()> {
    let types_dir = dir.join(types_package);
    let src = types_dir.join("src");
    fs::create_dir_all(&src)?;

    let view_dep = workspace_dep("flui-view", local, 3);
    let hot_dep = workspace_dep("flui-hot-reload", local, 3);

    let cargo = format!(
        r#"[package]
name = "{types_package}"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
description = "Shared types and persistent State for the hot-reload app"

[dependencies]
flui-view = {view_dep}
flui-hot-reload = {hot_dep}
"#
    );
    fs::write(types_dir.join("Cargo.toml"), cargo).context("Failed to create types/Cargo.toml")?;

    fs::write(src.join("lib.rs"), TYPES_LIB).context("Failed to create types/lib.rs")?;
    Ok(())
}

fn generate_logic(
    dir: &Path,
    types_package: &str,
    worker_package: &str,
    worker_lib: &str,
    local: bool,
) -> CliResult<()> {
    let logic_dir = dir.join(worker_package);
    let src = logic_dir.join("src");
    fs::create_dir_all(&src)?;

    let hot_dep = with_features(&workspace_dep("flui-hot-reload", local, 3), &["app-plugin"]);
    let types_dep = member_dep(types_package);
    let view_dep = workspace_dep("flui-view", local, 3);
    let widgets_dep = workspace_dep("flui-widgets", local, 3);
    let types_geom_dep = workspace_dep("flui-types", local, 3);
    let types_crate = types_package.replace('-', "_");

    let cargo = format!(
        r#"[package]
name = "{worker_package}"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
description = "Reloadable UI logic (cdylib) — the hot-reload target"

[lib]
crate-type = ["cdylib"]
name = "{worker_lib}"

[dependencies]
flui-hot-reload = {hot_dep}
flui-types = {types_geom_dep}
flui-view = {view_dep}
flui-widgets = {widgets_dep}
{types_package} = {types_dep}
"#
    );
    fs::write(logic_dir.join("Cargo.toml"), cargo).context("Failed to create logic/Cargo.toml")?;

    let lib = LOGIC_LIB.replace("__TYPES_CRATE__", &types_crate);
    fs::write(src.join("lib.rs"), lib).context("Failed to create logic/lib.rs")?;
    Ok(())
}

fn generate_host(
    dir: &Path,
    name: &str,
    types_package: &str,
    host_package: &str,
    worker_package: &str,
    worker_lib: &str,
    local: bool,
) -> CliResult<()> {
    let host_dir = dir.join(host_package);
    let src = host_dir.join("src");
    fs::create_dir_all(&src)?;

    let app_dep = with_features(&workspace_dep("flui-app", local, 3), &["hot-reload"]);
    let hot_dep = with_features(&workspace_dep("flui-hot-reload", local, 3), &["app-plugin"]);
    let types_dep = member_dep(types_package);
    let types_crate = types_package.replace('-', "_");

    let cargo = format!(
        r#"[package]
name = "{host_package}"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
description = "Host binary — owns the element tree and loads the worker"

[[bin]]
name = "{host_package}"
path = "src/main.rs"

[dependencies]
flui-app = {app_dep}
flui-hot-reload = {hot_dep}
{types_package} = {types_dep}
tracing = {{ workspace = true }}
"#
    );
    fs::write(host_dir.join("Cargo.toml"), cargo).context("Failed to create host/Cargo.toml")?;

    let main = HOST_MAIN
        .replace("__NAME__", name)
        .replace("__HOST_PACKAGE__", host_package)
        .replace("__WORKER_PACKAGE__", worker_package)
        .replace("__WORKER_LIB__", worker_lib)
        .replace("__TYPES_CRATE__", &types_crate);
    fs::write(src.join("main.rs"), main).context("Failed to create host/main.rs")?;
    Ok(())
}

fn generate_readme(
    dir: &Path,
    name: &str,
    types_package: &str,
    worker_package: &str,
    host_package: &str,
) -> CliResult<()> {
    let content = format!(
        r"# {name}

A FLUI application with Flutter-parity **hot reload** (state preserved).

## Layout

| Crate | Role |
|-------|------|
| `{types_package}/` | Shared types + persistent `State` (linked into host and worker) |
| `{worker_package}/` | Reloadable `build()` code — the reload target |
| `{host_package}/` | Window, GPU, element tree; loads the worker |

## Run

```bash
flui run
```

Edit `{worker_package}/src/lib.rs` (the `INCREMENT_LABEL`) and save: the CLI
rebuilds the worker, the host reloads it in-process, and the counter value is
preserved.

Editing `{types_package}/src/` changes the shared type layout, so the CLI
restarts the host instead (hot restart) — bump `TYPE_FINGERPRINT` there.

## Build

```bash
flui build desktop --package {host_package} --release
```
"
    );
    fs::write(dir.join("README.md"), content).context("Failed to create README.md")?;
    Ok(())
}

const TYPES_LIB: &str = r#"//! Shared types for the hot-reload app.
//!
//! Linked into BOTH the host binary and the reloadable worker dylib, so its
//! memory layout must stay stable across a hot reload. Bump `TYPE_FINGERPRINT`
//! whenever `CounterState` or `CounterApp` changes layout — `flui run` then
//! knows to restart the host (hot restart) instead of reloading the worker
//! against stale host state.

use std::sync::{
    Arc,
    atomic::{AtomicI32, Ordering},
};

use flui_hot_reload::{WorkerBuildEnv, get_worker_build_ptr};
use flui_view::prelude::*;

/// Stable-layout fingerprint. Bump when the shared types change shape.
pub const TYPE_FINGERPRINT: u64 = 0xF10A_0001;

/// The reloadable build function's signature: worker-side code fills a view
/// given the persistent state and the widget configuration.
pub type CounterBuildFn = fn(WorkerBuildEnv<'_>, &CounterState, &CounterApp) -> BoxedView;

/// Resolve the worker's build function for `TYPE_FINGERPRINT`.
///
/// `None` is a clean "worker unavailable" signal — the registry is pruned
/// before an image unmaps, and a fingerprint change after a reload registers
/// under a different key — so this panics loudly rather than jumping into
/// unmapped code.
#[expect(unsafe_code)]
pub fn counter_build_fn() -> CounterBuildFn {
    let ptr = get_worker_build_ptr(TYPE_FINGERPRINT).expect(
        "counter worker unavailable — build the logic crate, set \
         FLUI_WORKER_PLUGIN, and restart the host if the shared types layout \
         changed (fingerprint mismatch)",
    );
    // SAFETY: the worker registers this pointer via `hot_reload_worker!` with
    // the same `CounterBuildFn` signature, both compiled from this workspace.
    unsafe { std::mem::transmute(ptr) }
}

/// Root stateful widget. Its `State` lives in the host element tree and
/// survives a worker reload.
#[derive(Clone, Debug, StatefulView)]
pub struct CounterApp {
    /// Initial value (used only when state is first created).
    pub initial: i32,
    /// Live counter storage, shared with the worker's tap handlers.
    pub count: Arc<AtomicI32>,
}

/// Persistent state owned by the host element tree.
#[derive(Debug)]
pub struct CounterState {
    count: Arc<AtomicI32>,
}

impl CounterState {
    /// Shared counter storage, readable from worker UI code.
    pub fn count(&self) -> &Arc<AtomicI32> {
        &self.count
    }
}

impl StatefulView for CounterApp {
    type State = CounterState;

    fn create_state(&self) -> Self::State {
        self.count.store(self.initial, Ordering::Relaxed);
        CounterState {
            count: Arc::clone(&self.count),
        }
    }
}

impl ViewState<CounterApp> for CounterState {
    fn build(&self, view: &CounterApp, ctx: &dyn BuildContext) -> impl IntoView {
        let build = counter_build_fn();
        build(WorkerBuildEnv::new(ctx), self, view)
    }
}

/// Stateless shell so `run_app` can mount a stateful subtree.
#[derive(Clone, Debug, StatelessView)]
pub struct CounterShell {
    /// Stateful counter mounted as the sole child.
    pub app: CounterApp,
}

impl StatelessView for CounterShell {
    fn build(&self, _ctx: &dyn BuildContext) -> impl IntoView {
        self.app.clone()
    }
}
"#;

const LOGIC_LIB: &str = r#"//! Reloadable UI logic for the hot-reload app.
//!
//! **Edit `INCREMENT_LABEL` below and save** — `flui run` rebuilds this crate,
//! the host reloads the dylib in-process, and the counter value is preserved.

use std::sync::{
    Arc,
    atomic::{AtomicI32, Ordering},
};

use flui_hot_reload::{WorkerBuildEnv, hot_reload_worker, request_rebuild};
use flui_types::Color;
use flui_view::prelude::*;
use flui_widgets::{ColoredBox, Column, GestureDetector, Padding, Text};
use __TYPES_CRATE__::{CounterApp, CounterState, TYPE_FINGERPRINT};

/// **Edit this string and rebuild to see hot reload.**
const INCREMENT_LABEL: &str = "Increment (+1)";

fn build_counter_ui(
    _env: WorkerBuildEnv<'_>,
    state: &CounterState,
    _view: &CounterApp,
) -> BoxedView {
    let count = state.count().load(Ordering::Relaxed);
    let count_for_tap: Arc<AtomicI32> = Arc::clone(state.count());

    Column::new(vec![
        Text::new(format!("Count: {count}")).boxed(),
        GestureDetector::new()
            .on_tap(move || {
                count_for_tap.fetch_add(1, Ordering::Relaxed);
                request_rebuild();
            })
            .child(
                Padding::all(12.0).child(
                    ColoredBox::new(Color::rgb(40, 100, 200)).child(Text::new(INCREMENT_LABEL)),
                ),
            )
            .boxed(),
    ])
    .boxed()
}

fn init_counter_worker(register: flui_hot_reload::RegisterWorkerBuildFn) {
    register(TYPE_FINGERPRINT, build_counter_ui as *const ());
}

hot_reload_worker!(init_counter_worker, fingerprint: TYPE_FINGERPRINT);
"#;

const HOST_MAIN: &str = r#"//! Host binary for the hot-reload app.
//!
//! Run it with `flui run`: the CLI builds the worker (`__WORKER_PACKAGE__`) and
//! this host, starts this process with the worker dylib path, then rebuilds
//! (and reloads) only the worker on each save. The counter's `State` lives in
//! this process's element tree, so it survives a reload.

use std::sync::{Arc, atomic::AtomicI32};

use __TYPES_CRATE__::{CounterApp, CounterShell};
use flui_app::{AppConfig, run_app_with_config};
use flui_hot_reload::engine::env;

/// Default worker dylib path, used when `FLUI_WORKER_PLUGIN` is unset (a bare
/// `cargo run -p __HOST_PACKAGE__` without `flui run`).
fn default_worker_path() -> std::path::PathBuf {
    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "debug".into());
    let mut path = std::path::PathBuf::from("target");
    path.push(&profile);

    #[cfg(windows)]
    {
        path.push("__WORKER_LIB__.dll");
    }
    #[cfg(all(unix, not(target_os = "macos")))]
    {
        path.push("lib__WORKER_LIB__.so");
    }
    #[cfg(target_os = "macos")]
    {
        path.push("lib__WORKER_LIB__.dylib");
    }

    path
}

fn main() {
    let worker_path = std::env::var(env::WORKER_PLUGIN)
        .map_or_else(|_| default_worker_path(), std::path::PathBuf::from);

    tracing::info!(
        worker = %worker_path.display(),
        "Hot-reload host — edit the logic crate and save to reload"
    );

    let count = Arc::new(AtomicI32::new(0));
    let root = CounterShell {
        app: CounterApp {
            initial: 0,
            count: Arc::clone(&count),
        },
    };

    let config = AppConfig::new()
        .with_title("__NAME__")
        .with_size(480, 320)
        .with_worker_plugin_path(worker_path);

    run_app_with_config(root, config);

    tracing::info!(
        final_count = count.load(std::sync::atomic::Ordering::Relaxed),
        "Application exited"
    );
}
"#;
