[package]
name = "flui_foundation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Foundation layer for Flui framework - keys, change notification, diagnostics"

[dependencies]
parking_lot.workspace = true
serde.workspace = true
thiserror.workspace = true
