#!/usr/bin/env python3
"""Offline font inventory, provenance, notice, and deterministic fixture checks."""
import argparse
import hashlib
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import tomllib

ASSETS = Path('crates/flui-painting/assets/fonts')
RESTRICTED_SHA256 = '74d696e666f696e93db685a85c94bfbfcc0796dfcf8a2e2e2c908a54e82949'
FONT_SUFFIXES = {'.ttf', '.otf', '.woff', '.woff2'}


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def check(root):
    root = Path(root)
    assets = root / ASSETS
    errors = []
    discovered = {path.relative_to(assets).as_posix(): path for path in assets.rglob('*')
                  if path.is_file() and path.suffix.lower() in FONT_SUFFIXES}
    for name, path in discovered.items():
        if name.lower() == 'arial.ttf' or digest(path) == RESTRICTED_SHA256:
            errors.append(f'{name}: restricted Arial fixture must not be distributed')
    for directory in ('crates', 'examples', 'tools', 'assets'):
        for current, children, files in os.walk(root / directory):
            children[:] = [name for name in children if name not in {'target', '.git', '.claude'}]
            for name in files:
                path = Path(current) / name
                if path.suffix.lower() in FONT_SUFFIXES and not path.is_relative_to(assets):
                    errors.append(f'{path.relative_to(root)}: unlisted font outside the inventory owner')
    inventory_path = assets / 'inventory.toml'
    if not inventory_path.exists():
        return errors + ['font provenance inventory and license notice records are missing']
    inventory = tomllib.loads(inventory_path.read_text())
    notices = {}
    for notice in inventory.get('notice', []):
        name = notice['file']
        if name in notices:
            errors.append(f'{name}: duplicate notice record')
        notices[name] = notice
        path = assets / name
        if not path.is_file():
            errors.append(f'{name}: missing license/notice file')
        elif digest(path) != notice.get('sha256'):
            errors.append(f'{name}: notice hash mismatch')
        if not notice.get('source'):
            errors.append(f'{name}: missing notice provenance')
    records = {}
    for font in inventory.get('font', []):
        name = font['file']
        if name in records:
            errors.append(f'{name}: duplicate font record')
        records[name] = font
        if name not in discovered:
            errors.append(f'{name}: recorded font is missing')
        elif digest(discovered[name]) != font.get('sha256'):
            errors.append(f'{name}: font hash mismatch')
        if not font.get('source') or not font.get('license'):
            errors.append(f'{name}: missing source or license provenance')
        if font.get('kind') not in {'generated', 'upstream'}:
            errors.append(f'{name}: invalid provenance kind')
        if not font.get('notices') or any(notice not in notices for notice in font['notices']):
            errors.append(f'{name}: missing recorded license/notice association')
        if font.get('kind') == 'upstream' and not (font.get('revision') or font.get('archive_sha256')):
            errors.append(f'{name}: upstream source must pin revision or archive checksum')
        if font.get('kind') == 'generated' and not (root / font.get('generator', '')).is_file():
            errors.append(f'{name}: missing first-party generator')
    for name in sorted(discovered.keys() - records.keys()):
        errors.append(f'{name}: unlisted font asset')
    return errors


def reproduce(root):
    root = Path(root)
    errors = []
    inventory = tomllib.loads((root / ASSETS / 'inventory.toml').read_text())
    generated = {font['file'] for font in inventory['font'] if font['kind'] == 'generated'}
    with tempfile.TemporaryDirectory() as directory:
        result = subprocess.run([sys.executable, '-B', str(root / 'tools/decoy-face/generate.py'),
                                 '--output-dir', directory], capture_output=True, text=True)
        if result.returncode:
            return [f'fixture generation failed: {result.stderr}']
        outputs = {path.name for path in Path(directory).glob('*.ttf')}
        if outputs != generated:
            errors.append(f'generated inventory differs from generator outputs: {outputs ^ generated}')
        for name in outputs & generated:
            if (Path(directory) / name).read_bytes() != (root / ASSETS / name).read_bytes():
                errors.append(f'{name}: generated bytes are not reproducible')
    return errors


def package_listing(root):
    """Evidence about file selection only, not a successful Cargo archive/build."""
    root = Path(root)
    inventory = tomllib.loads((root / ASSETS / 'inventory.toml').read_text())
    output = subprocess.run(['cargo', 'package', '-p', 'flui-painting', '--list', '--offline', '--allow-dirty'],
                            cwd=root, capture_output=True, text=True)
    if output.returncode:
        return [f'Cargo package listing failed: {output.stderr}']
    included = set(output.stdout.splitlines())
    required = {'assets/fonts/inventory.toml'}
    required.update('assets/fonts/' + entry['file'] for entry in inventory['font'])
    required.update('assets/fonts/' + entry['file'] for entry in inventory['notice'])
    errors = [f'package listing excludes {name}' for name in sorted(required - included)]
    if any(Path(name).name.lower() == 'arial.ttf' for name in included):
        errors.append('package listing includes restricted Arial fixture')
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--package-list', action='store_true', help='also check Cargo file selection, without creating archives')
    args = parser.parse_args()
    errors = check(args.root)
    if not errors:
        errors.extend(reproduce(args.root))
    if not errors and args.package_list:
        errors.extend(package_listing(args.root))
    for error in errors:
        print(f'font-assets: {error}', file=sys.stderr)
    if errors:
        return 1
    print('font-assets: inventory, provenance, notices and generated bytes verified' +
          ('; Cargo package listing verified (not archive/build evidence)' if args.package_list else ''))
    return 0


if __name__ == '__main__':
    sys.exit(main())
