#!/usr/bin/env python3
"""Build a fresh consumer application against the release ARCHIVES, offline.

`release_policy.py --package` proves the 29 product/support packages can be
archived with normalized manifests. This script proves the other half of
distribution: that a consumer which knows nothing about this checkout can
create, build and test an application from those archives alone, through the
same dependency declaration the CLI writes for a registry consumer
(`flui = "<version>"`).

How the registry is stood in for, without a network or an upload:

1. Every third-party dependency the workspace resolves is vendored with
   `cargo vendor --versioned-dirs` — Cargo's own directory-source format,
   including per-file checksums.
2. Every FLUI archive is extracted into that same directory under
   `<name>-<version>` with a `.cargo-checksum.json` carrying the archive's
   SHA-256 and no file list (a directory source verifies listed files only, so
   an empty list means "trust the package checksum"), which is exactly what
   Cargo accepts for a crate it would otherwise download.
3. The consumer's `.cargo/config.toml` replaces `crates-io` with that
   directory, so `flui = "<version>"` resolves to the archive and nothing
   else — a path back into this checkout would be a resolution error, not a
   silent fallback.

The consumer is generated by the CLI built from this checkout (`flui create`
without `--local`). Until the framework is on crates.io that branch of the
template pins the `flui` dependency to the release git tag (which is what a
user gets today); this check rewrites that one dependency to the registry
form `flui = { version = "=<version>" }` so the archives, not the tag, are
what gets built — the tag is the past, the archives are what publication
would ship. A `path` dependency is refused outright.

Exit 0 on a green consumer build and test run; 1 on any failure, with Cargo's
own diagnostics left on stderr. Nothing is uploaded and no credentials are
read.
"""
import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tarfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run(command, cwd, env=None):
    print('+', ' '.join(str(part) for part in command), flush=True)
    completed = subprocess.run(command, cwd=cwd, env=env)
    if completed.returncode:
        sys.exit(f'release-consumer-check: `{command[0]} {command[1]}` failed with {completed.returncode}')


def workspace_version():
    manifest = tomllib.loads((ROOT / 'Cargo.toml').read_text())
    return manifest['workspace']['package']['version']


def package_archives(preview_dirty):
    command = [sys.executable, '-B', str(ROOT / 'scripts/release_policy.py'), '--package']
    if preview_dirty:
        command.append('--preview-dirty')
    run(command, ROOT)
    archives = sorted((ROOT / 'target/release-policy/package').glob('*.crate'))
    if not archives:
        sys.exit('release-consumer-check: release_policy.py produced no archives')
    return archives


def vendor_third_party(vendor):
    if vendor.exists():
        shutil.rmtree(vendor)
    vendor.parent.mkdir(parents=True, exist_ok=True)
    # `cargo vendor` prints the config snippet a caller would paste; it is
    # regenerated below for the consumer, so stdout is discarded here.
    with open(os.devnull, 'w') as sink:
        completed = subprocess.run(
            ['cargo', 'vendor', '--locked', '--versioned-dirs', str(vendor)],
            cwd=ROOT, stdout=sink)
    if completed.returncode:
        sys.exit('release-consumer-check: cargo vendor failed')


def install_archives(archives, vendor):
    """Extract each FLUI archive next to the vendored third-party crates."""
    installed = []
    for archive in archives:
        digest = hashlib.sha256(archive.read_bytes()).hexdigest()
        with tarfile.open(archive) as package:
            members = package.getmembers()
            top = {member.name.split('/', 1)[0] for member in members}
            if len(top) != 1:
                sys.exit(f'release-consumer-check: {archive.name} has no single top-level directory')
            (name_version,) = top
            destination = vendor / name_version
            if destination.exists():
                shutil.rmtree(destination)
            package.extractall(vendor, filter='data')
        (destination / '.cargo-checksum.json').write_text(
            json.dumps({'files': {}, 'package': digest}))
        installed.append(name_version)
    return installed


def build_cli(target_dir):
    run(['cargo', 'build', '--locked', '-p', 'flui-cli', '--target-dir', str(target_dir)], ROOT)
    binary = target_dir / 'debug' / 'flui'
    if not binary.exists():
        sys.exit(f'release-consumer-check: CLI binary missing at {binary}')
    return binary


def create_consumer(cli, consumer, template, version):
    if consumer.exists():
        shutil.rmtree(consumer)
    consumer.parent.mkdir(parents=True, exist_ok=True)
    # No `--local`: the template's non-local branch — the git tag today,
    # `flui = "<version>"` once the framework is published.
    run([str(cli), 'create', consumer.name, '--template', template], consumer.parent)
    manifest_path = consumer / 'Cargo.toml'
    manifest = manifest_path.read_text()
    if 'path' in manifest:
        sys.exit('release-consumer-check: the generated manifest carries a path dependency; '
                 'a registry consumer must not know this checkout')
    manifest, rewritten = registry_form(manifest, version)
    if rewritten:
        manifest_path.write_text(manifest)
        print(f'release-consumer-check: rewrote {rewritten} git-tag flui dependency(ies) to '
              f'the registry form `version = "={version}"` so the archives are what builds')
    # `flui create` may leave a lockfile resolved against the live registry
    # (whatever was newest when it ran); the offline build below must
    # resolve against the vendor set instead, so the resolution starts
    # from the manifest. The lockfile the build writes is what the
    # checksum comparison later reads.
    lockfile = consumer / 'Cargo.lock'
    if lockfile.exists():
        lockfile.unlink()
        print('release-consumer-check: dropped the generated Cargo.lock so resolution comes '
              'from the vendor set')
    return manifest


def registry_form(manifest, version):
    """Replace every `flui = { git = ..., tag = ... }` dependency with the
    registry form at the exact packaged version, keeping any `features`;
    returns the manifest and how many were rewritten."""
    import re
    count = 0

    def rewrite(match):
        nonlocal count
        count += 1
        body = match.group(1)
        features = re.search(r'features\s*=\s*(\[[^\]]*\])', body)
        fields = [f'version = "={version}"']
        if features:
            fields.append(f'features = {features.group(1)}')
        return 'flui = { ' + ', '.join(fields) + ' }'

    manifest = re.sub(r'^flui\s*=\s*\{([^}]*\bgit\s*=[^}]*)\}', rewrite, manifest, flags=re.M)
    return manifest, count


def point_consumer_at_vendor(consumer, vendor):
    config_dir = consumer / '.cargo'
    config_dir.mkdir(exist_ok=True)
    (config_dir / 'config.toml').write_text(
        '[source.crates-io]\n'
        'replace-with = "flui-release-archives"\n\n'
        '[source.flui-release-archives]\n'
        f'directory = "{vendor}"\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, default=ROOT / 'target/release-consumer',
                        help='scratch directory for the vendor set, the CLI build and the consumer')
    parser.add_argument('--template', default='counter',
                        help='CLI template to generate (counter has generated tests)')
    parser.add_argument('--preview-dirty', action='store_true',
                        help='package a dirty tree (forwarded to release_policy.py)')
    parser.add_argument('--keep-vendor', action='store_true',
                        help='reuse an existing vendor directory instead of rebuilding it')
    args = parser.parse_args()

    version = workspace_version()
    out = args.out.resolve()
    vendor = out / 'vendor'
    consumer = out / 'consumer' / 'beta_consumer'

    archives = package_archives(args.preview_dirty)
    print(f'release-consumer-check: {len(archives)} archives at version {version}')
    if not (args.keep_vendor and vendor.exists()):
        vendor_third_party(vendor)
    installed = install_archives(archives, vendor)
    print(f'release-consumer-check: installed {len(installed)} FLUI archives into {vendor}')

    cli = build_cli(out / 'cli-target')
    manifest = create_consumer(cli, consumer, args.template, version)
    if f'"{version}"' not in manifest:
        sys.exit(f'release-consumer-check: the generated manifest does not depend on flui {version}:\n{manifest}')
    point_consumer_at_vendor(consumer, vendor)

    # A separate target directory: the consumer must compile the archives,
    # not reuse this checkout's artifacts.
    env = dict(os.environ, CARGO_TARGET_DIR=str(out / 'consumer-target'))
    env.pop('CARGO_HOME_OVERRIDE', None)
    run(['cargo', 'build', '--offline'], consumer, env)
    run(['cargo', 'test', '--offline'], consumer, env)
    # The proof that resolution went through the archives: every flui-*
    # package in the consumer's lockfile must record the directory source's
    # checksum, i.e. one of the archive digests.
    lock = tomllib.loads((consumer / 'Cargo.lock').read_text())
    digests = {hashlib.sha256(archive.read_bytes()).hexdigest() for archive in archives}
    flui_packages = [entry for entry in lock['package'] if entry['name'].startswith('flui')]
    unmatched = [entry['name'] for entry in flui_packages if entry.get('checksum') not in digests]
    if not flui_packages or unmatched:
        sys.exit(f'release-consumer-check: consumer lockfile does not resolve FLUI to the archives: {unmatched}')
    print(f'release-consumer-check: PASS — consumer built and tested against {len(flui_packages)} '
          f'archived FLUI packages at {version}, offline, from {consumer}')


if __name__ == '__main__':
    main()
