// @generated by `cargo xtask key-vocabulary --write` from keyboard-types 0.8.3
// (src/code.rs, MIT OR Apache-2.0). Edit the generator, not this file.

//! [`Code`], generated from the W3C value list.

#![allow(
    clippy::doc_markdown,
    reason = "the variant descriptions are the specification's prose"
)]

/// The physical key, independent of the keyboard layout: the W3C `code` value.
///
/// The variants are the [UI Events `code` values](https://w3c.github.io/uievents-code/).
/// A value the specification adds before FLUI regenerates this table arrives as
/// [`Code::Unidentified`].
///
/// # Examples
///
/// ```
/// use flui_platform_api::keyboard::Code;
///
/// assert_eq!(Code::KeyA.as_str(), "KeyA");
/// assert_eq!(Code::from_w3c("KeyA"), Some(Code::KeyA));
/// assert_eq!(Code::from_w3c("NoSuchValue"), None);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum Code {
    /// <kbd>`~</kbd> on a US keyboard. This is the <kbd>半角/全角/漢字</kbd> (<span class="unicode">hankaku/zenkaku/kanji</span>) key on Japanese keyboards
    /// This is also called a backtick or grave.
    #[doc(alias = "Backtick")]
    #[doc(alias = "Grave")]
    Backquote,
    /// Used for both the US <kbd>\|</kbd> (on the 101-key layout) and also for the key
    /// located between the <kbd>"</kbd> and <kbd>Enter</kbd> keys on row C of the 102-,
    /// 104- and 106-key layouts.
    /// Labelled <kbd>#~</kbd> on a UK (102) keyboard.
    Backslash,
    /// <kbd>[{</kbd> on a US keyboard.
    BracketLeft,
    /// <kbd>]}</kbd> on a US keyboard.
    BracketRight,
    /// <kbd>,&lt;</kbd> on a US keyboard.
    Comma,
    /// <kbd>0)</kbd> on a US keyboard.
    Digit0,
    /// <kbd>1!</kbd> on a US keyboard.
    Digit1,
    /// <kbd>2@</kbd> on a US keyboard.
    Digit2,
    /// <kbd>3#</kbd> on a US keyboard.
    Digit3,
    /// <kbd>4$</kbd> on a US keyboard.
    Digit4,
    /// <kbd>5%</kbd> on a US keyboard.
    Digit5,
    /// <kbd>6^</kbd> on a US keyboard.
    Digit6,
    /// <kbd>7&amp;</kbd> on a US keyboard.
    Digit7,
    /// <kbd>8*</kbd> on a US keyboard.
    Digit8,
    /// <kbd>9(</kbd> on a US keyboard.
    Digit9,
    /// <kbd>=+</kbd> on a US keyboard.
    Equal,
    /// Located between the left <kbd>Shift</kbd> and <kbd>Z</kbd> keys.
    /// Labelled <kbd>\|</kbd> on a UK keyboard.
    IntlBackslash,
    /// Located between the <kbd>/</kbd> and right <kbd>Shift</kbd> keys.
    /// Labelled <kbd>\ろ</kbd> (<span class="unicode">ro</span>) on a Japanese keyboard.
    IntlRo,
    /// Located between the <kbd>=</kbd> and <kbd>Backspace</kbd> keys.
    /// Labelled <kbd>¥</kbd> (<span class="unicode">yen</span>) on a Japanese keyboard. <kbd>\/</kbd> on a
    /// Russian keyboard.
    IntlYen,
    /// <kbd>a</kbd> on a US keyboard.
    /// Labelled <kbd>q</kbd> on an AZERTY (e.g., French) keyboard.
    KeyA,
    /// <kbd>b</kbd> on a US keyboard.
    KeyB,
    /// <kbd>c</kbd> on a US keyboard.
    KeyC,
    /// <kbd>d</kbd> on a US keyboard.
    KeyD,
    /// <kbd>e</kbd> on a US keyboard.
    KeyE,
    /// <kbd>f</kbd> on a US keyboard.
    KeyF,
    /// <kbd>g</kbd> on a US keyboard.
    KeyG,
    /// <kbd>h</kbd> on a US keyboard.
    KeyH,
    /// <kbd>i</kbd> on a US keyboard.
    KeyI,
    /// <kbd>j</kbd> on a US keyboard.
    KeyJ,
    /// <kbd>k</kbd> on a US keyboard.
    KeyK,
    /// <kbd>l</kbd> on a US keyboard.
    KeyL,
    /// <kbd>m</kbd> on a US keyboard.
    KeyM,
    /// <kbd>n</kbd> on a US keyboard.
    KeyN,
    /// <kbd>o</kbd> on a US keyboard.
    KeyO,
    /// <kbd>p</kbd> on a US keyboard.
    KeyP,
    /// <kbd>q</kbd> on a US keyboard.
    /// Labelled <kbd>a</kbd> on an AZERTY (e.g., French) keyboard.
    KeyQ,
    /// <kbd>r</kbd> on a US keyboard.
    KeyR,
    /// <kbd>s</kbd> on a US keyboard.
    KeyS,
    /// <kbd>t</kbd> on a US keyboard.
    KeyT,
    /// <kbd>u</kbd> on a US keyboard.
    KeyU,
    /// <kbd>v</kbd> on a US keyboard.
    KeyV,
    /// <kbd>w</kbd> on a US keyboard.
    /// Labelled <kbd>z</kbd> on an AZERTY (e.g., French) keyboard.
    KeyW,
    /// <kbd>x</kbd> on a US keyboard.
    KeyX,
    /// <kbd>y</kbd> on a US keyboard.
    /// Labelled <kbd>z</kbd> on a QWERTZ (e.g., German) keyboard.
    KeyY,
    /// <kbd>z</kbd> on a US keyboard.
    /// Labelled <kbd>w</kbd> on an AZERTY (e.g., French) keyboard, and <kbd>y</kbd> on a
    /// QWERTZ (e.g., German) keyboard.
    KeyZ,
    /// <kbd>-_</kbd> on a US keyboard.
    Minus,
    /// <kbd>.&gt;</kbd> on a US keyboard.
    Period,
    /// <kbd>'"</kbd> on a US keyboard.
    /// This is also called an apostrophe.
    #[doc(alias = "Apostrophe")]
    Quote,
    /// <kbd>;:</kbd> on a US keyboard.
    Semicolon,
    /// <kbd>/?</kbd> on a US keyboard.
    Slash,
    /// <kbd>Alt</kbd>, <kbd>Option</kbd> or <kbd>⌥</kbd>.
    AltLeft,
    /// <kbd>Alt</kbd>, <kbd>Option</kbd> or <kbd>⌥</kbd>.
    /// This is labelled <kbd>AltGr</kbd> key on many keyboard layouts.
    AltRight,
    /// <kbd>Backspace</kbd> or <kbd>⌫</kbd>.
    /// Labelled <kbd>Delete</kbd> on Apple keyboards.
    Backspace,
    /// <kbd>CapsLock</kbd> or <kbd>⇪</kbd>
    CapsLock,
    /// The application context menu key, which is typically found between the right <kbd>Meta</kbd> key and the right <kbd>Control</kbd> key.
    ContextMenu,
    /// <kbd>Control</kbd> or <kbd>⌃</kbd>
    ControlLeft,
    /// <kbd>Control</kbd> or <kbd>⌃</kbd>
    ControlRight,
    /// <kbd>Enter</kbd> or <kbd>↵</kbd>. Labelled <kbd>Return</kbd> on Apple keyboards.
    #[doc(alias = "Return")]
    Enter,
    /// The Windows, <kbd>⌘</kbd>, <kbd>Command</kbd> or other OS symbol key.
    /// In Linux (XKB) terminology, this is often referred to as the left "Super".
    #[doc(alias = "SuperLeft")]
    #[doc(alias = "OSLeft")]
    MetaLeft,
    /// The Windows, <kbd>⌘</kbd>, <kbd>Command</kbd> or other OS symbol key.
    /// In Linux (XKB) terminology, this is often referred to as the right "Super".
    #[doc(alias = "SuperRight")]
    #[doc(alias = "OSRight")]
    MetaRight,
    /// <kbd>Shift</kbd> or <kbd>⇧</kbd>
    ShiftLeft,
    /// <kbd>Shift</kbd> or <kbd>⇧</kbd>
    ShiftRight,
    /// <kbd> </kbd> (space)
    Space,
    /// <kbd>Tab</kbd> or <kbd>⇥</kbd>
    Tab,
    /// Japanese: <kbd>変換</kbd> (<span class="unicode">henkan</span>)
    Convert,
    /// Japanese: <kbd>カタカナ/ひらがな/ローマ字</kbd> (<span class="unicode">katakana/hiragana/romaji</span>)
    KanaMode,
    /// Korean: HangulMode <kbd>한/영</kbd> (<span class="unicode">han/yeong</span>)<br/>Japanese (Mac keyboard): <kbd>かな</kbd> (<span class="unicode">kana</span>)
    Lang1,
    /// Korean: Hanja <kbd>한자</kbd> (<span class="unicode">hanja</span>)<br/>Japanese (Mac keyboard): <kbd>英数</kbd> (<span class="unicode">eisu</span>)
    Lang2,
    /// Japanese (word-processing keyboard): Katakana
    Lang3,
    /// Japanese (word-processing keyboard): Hiragana
    Lang4,
    /// Japanese (word-processing keyboard): Zenkaku/Hankaku
    Lang5,
    /// Japanese: <kbd>無変換</kbd> (<span class="unicode">muhenkan</span>)
    NonConvert,
    /// <kbd>⌦</kbd>. The forward delete key.
    /// Note that on Apple keyboards, the key labelled <kbd>Delete</kbd> on the main part of
    /// the keyboard should be encoded as [`Backspace`][Code::Backspace].
    Delete,
    /// <kbd>End</kbd> or <kbd>↘</kbd>
    End,
    /// <kbd>Help</kbd>. Not present on standard PC keyboards.
    Help,
    /// <kbd>Home</kbd> or <kbd>↖</kbd>
    Home,
    /// <kbd>Insert</kbd> or <kbd>Ins</kbd>. Not present on Apple keyboards.
    Insert,
    /// <kbd>Page Down</kbd>, <kbd>PgDn</kbd> or <kbd>⇟</kbd>
    PageDown,
    /// <kbd>Page Up</kbd>, <kbd>PgUp</kbd> or <kbd>⇞</kbd>
    PageUp,
    /// <kbd>↓</kbd>
    ArrowDown,
    /// <kbd>←</kbd>
    ArrowLeft,
    /// <kbd>→</kbd>
    ArrowRight,
    /// <kbd>↑</kbd>
    ArrowUp,
    /// On the Mac, the [`NumLock`][Code::NumLock] code should be used for the numpad <kbd>Clear</kbd> key.
    NumLock,
    /// <kbd>0 Ins</kbd> on a keyboard<br/><kbd>0</kbd> on a phone or remote control
    Numpad0,
    /// <kbd>1 End</kbd> on a keyboard<br/><kbd>1</kbd> or <kbd>1 QZ</kbd> on a phone or
    /// remote control
    Numpad1,
    /// <kbd>2 ↓</kbd> on a keyboard<br/><kbd>2 ABC</kbd> on a phone or remote control
    Numpad2,
    /// <kbd>3 PgDn</kbd> on a keyboard<br/><kbd>3 DEF</kbd> on a phone or remote control
    Numpad3,
    /// <kbd>4 ←</kbd> on a keyboard<br/><kbd>4 GHI</kbd> on a phone or remote control
    Numpad4,
    /// <kbd>5</kbd> on a keyboard<br/><kbd>5 JKL</kbd> on a phone or remote control
    Numpad5,
    /// <kbd>6 →</kbd> on a keyboard<br/><kbd>6 MNO</kbd> on a phone or remote control
    Numpad6,
    /// <kbd>7 Home</kbd> on a keyboard<br/><kbd>7 PQRS</kbd> or <kbd>7 PRS</kbd> on a phone
    /// or remote control
    Numpad7,
    /// <kbd>8 ↑</kbd> on a keyboard<br/><kbd>8 TUV</kbd> on a phone or remote control
    Numpad8,
    /// <kbd>9 PgUp</kbd> on a keyboard<br/><kbd>9 WXYZ</kbd> or <kbd>9 WXY</kbd> on a phone
    /// or remote control
    Numpad9,
    /// <kbd>+</kbd>
    NumpadAdd,
    /// Found on the Microsoft Natural Keyboard.
    NumpadBackspace,
    /// <kbd>C</kbd> or <kbd>AC</kbd> (All Clear). Also for use with numpads that have a <kbd>Clear</kbd> key that is separate from the <kbd>NumLock</kbd> key. On the Mac, the numpad <kbd>Clear</kbd> key should always
    /// be encoded as [`NumLock`][Code::NumLock].
    NumpadClear,
    /// <kbd>CE</kbd> (Clear Entry)
    NumpadClearEntry,
    /// <kbd>,</kbd> (thousands separator). For locales where the thousands separator
    /// is a "." (e.g., Brazil), this key may generate a <kbd>.</kbd>.
    NumpadComma,
    /// <kbd>. Del</kbd>. For locales where the decimal separator is "," (e.g.,
    /// Brazil), this key may generate a <kbd>,</kbd>.
    NumpadDecimal,
    /// <kbd>/</kbd>
    NumpadDivide,
    /// The W3C `NumpadEnter` value.
    NumpadEnter,
    /// <kbd>=</kbd>
    NumpadEqual,
    /// <kbd>#</kbd> on a phone or remote control device. This key is typically found
    /// below the <kbd>9</kbd> key and to the right of the <kbd>0</kbd> key.
    NumpadHash,
    /// <kbd>M+</kbd> Add current entry to the value stored in memory.
    NumpadMemoryAdd,
    /// <kbd>MC</kbd> Clear the value stored in memory.
    NumpadMemoryClear,
    /// <kbd>MR</kbd> Replace the current entry with the value stored in memory.
    NumpadMemoryRecall,
    /// <kbd>MS</kbd> Replace the value stored in memory with the current entry.
    NumpadMemoryStore,
    /// <kbd>M-</kbd> Subtract current entry from the value stored in memory.
    NumpadMemorySubtract,
    /// <kbd>*</kbd> on a keyboard. For use with numpads that provide mathematical
    /// operations (<kbd>+</kbd>, <kbd>-</kbd>, <kbd>*</kbd> and <kbd>/</kbd>).<br/>Use [`NumpadStar`][Code::NumpadStar] for the <kbd>*</kbd> key on phones and remote controls.
    NumpadMultiply,
    /// <kbd>(</kbd> Found on the Microsoft Natural Keyboard.
    NumpadParenLeft,
    /// <kbd>)</kbd> Found on the Microsoft Natural Keyboard.
    NumpadParenRight,
    /// <kbd>*</kbd> on a phone or remote control device.
    /// This key is typically found below the <kbd>7</kbd> key and to the left of
    /// the <kbd>0</kbd> key.<br/>Use [`NumpadMultiply`][Code::NumpadMultiply] for the <kbd>*</kbd> key on
    /// numeric keypads.
    NumpadStar,
    /// <kbd>-</kbd>
    NumpadSubtract,
    /// <kbd>Esc</kbd> or <kbd>⎋</kbd>
    Escape,
    /// <kbd>Fn</kbd> This is typically a hardware key that does not generate a separate
    /// code. Most keyboards do not place this key in the function section, but it is
    /// included here to keep it with related keys.
    Fn,
    /// <kbd>FLock</kbd> or <kbd>FnLock</kbd>. Function Lock key. Found on the Microsoft
    /// Natural Keyboard.
    FnLock,
    /// <kbd>PrtScr SysRq</kbd> or <kbd>Print Screen</kbd>
    PrintScreen,
    /// <kbd>Scroll Lock</kbd>
    ScrollLock,
    /// <kbd>Pause Break</kbd>
    Pause,
    /// Some laptops place this key to the left of the <kbd>↑</kbd> key.
    BrowserBack,
    /// The W3C `BrowserFavorites` value.
    BrowserFavorites,
    /// Some laptops place this key to the right of the <kbd>↑</kbd> key.
    BrowserForward,
    /// The W3C `BrowserHome` value.
    BrowserHome,
    /// The W3C `BrowserRefresh` value.
    BrowserRefresh,
    /// The W3C `BrowserSearch` value.
    BrowserSearch,
    /// The W3C `BrowserStop` value.
    BrowserStop,
    /// <kbd>Eject</kbd> or <kbd>⏏</kbd>. This key is placed in the function
    /// section on some Apple keyboards.
    Eject,
    /// Sometimes labelled <kbd>My Computer</kbd> on the keyboard
    LaunchApp1,
    /// Sometimes labelled <kbd>Calculator</kbd> on the keyboard
    LaunchApp2,
    /// The W3C `LaunchMail` value.
    LaunchMail,
    /// The W3C `MediaPlayPause` value.
    MediaPlayPause,
    /// The W3C `MediaSelect` value.
    #[doc(alias = "LaunchMediaPlayer")]
    MediaSelect,
    /// The W3C `MediaStop` value.
    MediaStop,
    /// The W3C `MediaTrackNext` value.
    MediaTrackNext,
    /// The W3C `MediaTrackPrevious` value.
    MediaTrackPrevious,
    /// This key is placed in the function section on some Apple keyboards,
    /// replacing the <kbd>Eject</kbd> key.
    Power,
    /// The W3C `Sleep` value.
    Sleep,
    /// The W3C `AudioVolumeDown` value.
    #[doc(alias = "VolumeDown")]
    AudioVolumeDown,
    /// The W3C `AudioVolumeMute` value.
    #[doc(alias = "VolumeMute")]
    AudioVolumeMute,
    /// The W3C `AudioVolumeUp` value.
    #[doc(alias = "VolumeUp")]
    AudioVolumeUp,
    /// The W3C `WakeUp` value.
    WakeUp,
    /// The W3C `Abort` value.
    Abort,
    /// The W3C `Resume` value.
    Resume,
    /// The W3C `Suspend` value.
    Suspend,
    /// Found on Sun’s USB keyboard.
    Again,
    /// Found on Sun’s USB keyboard.
    Copy,
    /// Found on Sun’s USB keyboard.
    Cut,
    /// Found on Sun’s USB keyboard.
    Find,
    /// Found on Sun’s USB keyboard.
    Open,
    /// Found on Sun’s USB keyboard.
    Paste,
    /// Found on Sun’s USB keyboard.
    Props,
    /// Found on Sun’s USB keyboard.
    Select,
    /// Found on Sun’s USB keyboard.
    Undo,
    /// Use for dedicated <kbd>ひらがな</kbd> key found on some Japanese word processing keyboards.
    Hiragana,
    /// Use for dedicated <kbd>カタカナ</kbd> key found on some Japanese word processing keyboards.
    Katakana,
    /// This value code should be used when no other
    /// value given in this specification is appropriate.
    Unidentified,
    /// <kbd>F1</kbd>
    F1,
    /// <kbd>F2</kbd>
    F2,
    /// <kbd>F3</kbd>
    F3,
    /// <kbd>F4</kbd>
    F4,
    /// <kbd>F5</kbd>
    F5,
    /// <kbd>F6</kbd>
    F6,
    /// <kbd>F7</kbd>
    F7,
    /// <kbd>F8</kbd>
    F8,
    /// <kbd>F9</kbd>
    F9,
    /// <kbd>F10</kbd>
    F10,
    /// <kbd>F11</kbd>
    F11,
    /// <kbd>F12</kbd>
    F12,
    /// <kbd>F13</kbd>
    F13,
    /// <kbd>F14</kbd>
    F14,
    /// <kbd>F15</kbd>
    F15,
    /// <kbd>F16</kbd>
    F16,
    /// <kbd>F17</kbd>
    F17,
    /// <kbd>F18</kbd>
    F18,
    /// <kbd>F19</kbd>
    F19,
    /// <kbd>F20</kbd>
    F20,
    /// <kbd>F21</kbd>
    F21,
    /// <kbd>F22</kbd>
    F22,
    /// <kbd>F23</kbd>
    F23,
    /// <kbd>F24</kbd>
    F24,
    /// <kbd>F25</kbd>
    F25,
    /// <kbd>F26</kbd>
    F26,
    /// <kbd>F27</kbd>
    F27,
    /// <kbd>F28</kbd>
    F28,
    /// <kbd>F29</kbd>
    F29,
    /// <kbd>F30</kbd>
    F30,
    /// <kbd>F31</kbd>
    F31,
    /// <kbd>F32</kbd>
    F32,
    /// <kbd>F33</kbd>
    F33,
    /// <kbd>F34</kbd>
    F34,
    /// <kbd>F35</kbd>
    F35,
    /// Non-standard code value supported by Chromium.
    BrightnessDown,
    /// Non-standard code value supported by Chromium.
    BrightnessUp,
    /// Non-standard code value supported by Chromium.
    DisplayToggleIntExt,
    /// Non-standard code value supported by Chromium.
    KeyboardLayoutSelect,
    /// Non-standard code value supported by Chromium.
    LaunchAssistant,
    /// Non-standard code value supported by Chromium.
    LaunchControlPanel,
    /// Non-standard code value supported by Chromium.
    LaunchScreenSaver,
    /// Non-standard code value supported by Chromium.
    MailForward,
    /// Non-standard code value supported by Chromium.
    MailReply,
    /// Non-standard code value supported by Chromium.
    MailSend,
    /// Non-standard code value supported by Chromium.
    MediaFastForward,
    /// Non-standard code value supported by Chromium.
    MediaPause,
    /// Non-standard code value supported by Chromium.
    MediaPlay,
    /// Non-standard code value supported by Chromium.
    MediaRecord,
    /// Non-standard code value supported by Chromium.
    MediaRewind,
    /// Non-standard code value supported by Chromium.
    MicrophoneMuteToggle,
    /// Non-standard code value supported by Chromium.
    PrivacyScreenToggle,
    /// Non-standard code value supported by Chromium.
    KeyboardBacklightToggle,
    /// Non-standard code value supported by Chromium.
    SelectTask,
    /// Non-standard code value supported by Chromium.
    ShowAllWindows,
    /// Non-standard code value supported by Chromium.
    ZoomToggle,
}

impl Code {
    /// Every variant, in the order the specification lists them.
    pub const ALL: &[Self] = &[
        Self::Backquote,
        Self::Backslash,
        Self::BracketLeft,
        Self::BracketRight,
        Self::Comma,
        Self::Digit0,
        Self::Digit1,
        Self::Digit2,
        Self::Digit3,
        Self::Digit4,
        Self::Digit5,
        Self::Digit6,
        Self::Digit7,
        Self::Digit8,
        Self::Digit9,
        Self::Equal,
        Self::IntlBackslash,
        Self::IntlRo,
        Self::IntlYen,
        Self::KeyA,
        Self::KeyB,
        Self::KeyC,
        Self::KeyD,
        Self::KeyE,
        Self::KeyF,
        Self::KeyG,
        Self::KeyH,
        Self::KeyI,
        Self::KeyJ,
        Self::KeyK,
        Self::KeyL,
        Self::KeyM,
        Self::KeyN,
        Self::KeyO,
        Self::KeyP,
        Self::KeyQ,
        Self::KeyR,
        Self::KeyS,
        Self::KeyT,
        Self::KeyU,
        Self::KeyV,
        Self::KeyW,
        Self::KeyX,
        Self::KeyY,
        Self::KeyZ,
        Self::Minus,
        Self::Period,
        Self::Quote,
        Self::Semicolon,
        Self::Slash,
        Self::AltLeft,
        Self::AltRight,
        Self::Backspace,
        Self::CapsLock,
        Self::ContextMenu,
        Self::ControlLeft,
        Self::ControlRight,
        Self::Enter,
        Self::MetaLeft,
        Self::MetaRight,
        Self::ShiftLeft,
        Self::ShiftRight,
        Self::Space,
        Self::Tab,
        Self::Convert,
        Self::KanaMode,
        Self::Lang1,
        Self::Lang2,
        Self::Lang3,
        Self::Lang4,
        Self::Lang5,
        Self::NonConvert,
        Self::Delete,
        Self::End,
        Self::Help,
        Self::Home,
        Self::Insert,
        Self::PageDown,
        Self::PageUp,
        Self::ArrowDown,
        Self::ArrowLeft,
        Self::ArrowRight,
        Self::ArrowUp,
        Self::NumLock,
        Self::Numpad0,
        Self::Numpad1,
        Self::Numpad2,
        Self::Numpad3,
        Self::Numpad4,
        Self::Numpad5,
        Self::Numpad6,
        Self::Numpad7,
        Self::Numpad8,
        Self::Numpad9,
        Self::NumpadAdd,
        Self::NumpadBackspace,
        Self::NumpadClear,
        Self::NumpadClearEntry,
        Self::NumpadComma,
        Self::NumpadDecimal,
        Self::NumpadDivide,
        Self::NumpadEnter,
        Self::NumpadEqual,
        Self::NumpadHash,
        Self::NumpadMemoryAdd,
        Self::NumpadMemoryClear,
        Self::NumpadMemoryRecall,
        Self::NumpadMemoryStore,
        Self::NumpadMemorySubtract,
        Self::NumpadMultiply,
        Self::NumpadParenLeft,
        Self::NumpadParenRight,
        Self::NumpadStar,
        Self::NumpadSubtract,
        Self::Escape,
        Self::Fn,
        Self::FnLock,
        Self::PrintScreen,
        Self::ScrollLock,
        Self::Pause,
        Self::BrowserBack,
        Self::BrowserFavorites,
        Self::BrowserForward,
        Self::BrowserHome,
        Self::BrowserRefresh,
        Self::BrowserSearch,
        Self::BrowserStop,
        Self::Eject,
        Self::LaunchApp1,
        Self::LaunchApp2,
        Self::LaunchMail,
        Self::MediaPlayPause,
        Self::MediaSelect,
        Self::MediaStop,
        Self::MediaTrackNext,
        Self::MediaTrackPrevious,
        Self::Power,
        Self::Sleep,
        Self::AudioVolumeDown,
        Self::AudioVolumeMute,
        Self::AudioVolumeUp,
        Self::WakeUp,
        Self::Abort,
        Self::Resume,
        Self::Suspend,
        Self::Again,
        Self::Copy,
        Self::Cut,
        Self::Find,
        Self::Open,
        Self::Paste,
        Self::Props,
        Self::Select,
        Self::Undo,
        Self::Hiragana,
        Self::Katakana,
        Self::Unidentified,
        Self::F1,
        Self::F2,
        Self::F3,
        Self::F4,
        Self::F5,
        Self::F6,
        Self::F7,
        Self::F8,
        Self::F9,
        Self::F10,
        Self::F11,
        Self::F12,
        Self::F13,
        Self::F14,
        Self::F15,
        Self::F16,
        Self::F17,
        Self::F18,
        Self::F19,
        Self::F20,
        Self::F21,
        Self::F22,
        Self::F23,
        Self::F24,
        Self::F25,
        Self::F26,
        Self::F27,
        Self::F28,
        Self::F29,
        Self::F30,
        Self::F31,
        Self::F32,
        Self::F33,
        Self::F34,
        Self::F35,
        Self::BrightnessDown,
        Self::BrightnessUp,
        Self::DisplayToggleIntExt,
        Self::KeyboardLayoutSelect,
        Self::LaunchAssistant,
        Self::LaunchControlPanel,
        Self::LaunchScreenSaver,
        Self::MailForward,
        Self::MailReply,
        Self::MailSend,
        Self::MediaFastForward,
        Self::MediaPause,
        Self::MediaPlay,
        Self::MediaRecord,
        Self::MediaRewind,
        Self::MicrophoneMuteToggle,
        Self::PrivacyScreenToggle,
        Self::KeyboardBacklightToggle,
        Self::SelectTask,
        Self::ShowAllWindows,
        Self::ZoomToggle,
    ];

    /// The W3C spelling of this value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Backquote => "Backquote",
            Self::Backslash => "Backslash",
            Self::BracketLeft => "BracketLeft",
            Self::BracketRight => "BracketRight",
            Self::Comma => "Comma",
            Self::Digit0 => "Digit0",
            Self::Digit1 => "Digit1",
            Self::Digit2 => "Digit2",
            Self::Digit3 => "Digit3",
            Self::Digit4 => "Digit4",
            Self::Digit5 => "Digit5",
            Self::Digit6 => "Digit6",
            Self::Digit7 => "Digit7",
            Self::Digit8 => "Digit8",
            Self::Digit9 => "Digit9",
            Self::Equal => "Equal",
            Self::IntlBackslash => "IntlBackslash",
            Self::IntlRo => "IntlRo",
            Self::IntlYen => "IntlYen",
            Self::KeyA => "KeyA",
            Self::KeyB => "KeyB",
            Self::KeyC => "KeyC",
            Self::KeyD => "KeyD",
            Self::KeyE => "KeyE",
            Self::KeyF => "KeyF",
            Self::KeyG => "KeyG",
            Self::KeyH => "KeyH",
            Self::KeyI => "KeyI",
            Self::KeyJ => "KeyJ",
            Self::KeyK => "KeyK",
            Self::KeyL => "KeyL",
            Self::KeyM => "KeyM",
            Self::KeyN => "KeyN",
            Self::KeyO => "KeyO",
            Self::KeyP => "KeyP",
            Self::KeyQ => "KeyQ",
            Self::KeyR => "KeyR",
            Self::KeyS => "KeyS",
            Self::KeyT => "KeyT",
            Self::KeyU => "KeyU",
            Self::KeyV => "KeyV",
            Self::KeyW => "KeyW",
            Self::KeyX => "KeyX",
            Self::KeyY => "KeyY",
            Self::KeyZ => "KeyZ",
            Self::Minus => "Minus",
            Self::Period => "Period",
            Self::Quote => "Quote",
            Self::Semicolon => "Semicolon",
            Self::Slash => "Slash",
            Self::AltLeft => "AltLeft",
            Self::AltRight => "AltRight",
            Self::Backspace => "Backspace",
            Self::CapsLock => "CapsLock",
            Self::ContextMenu => "ContextMenu",
            Self::ControlLeft => "ControlLeft",
            Self::ControlRight => "ControlRight",
            Self::Enter => "Enter",
            Self::MetaLeft => "MetaLeft",
            Self::MetaRight => "MetaRight",
            Self::ShiftLeft => "ShiftLeft",
            Self::ShiftRight => "ShiftRight",
            Self::Space => "Space",
            Self::Tab => "Tab",
            Self::Convert => "Convert",
            Self::KanaMode => "KanaMode",
            Self::Lang1 => "Lang1",
            Self::Lang2 => "Lang2",
            Self::Lang3 => "Lang3",
            Self::Lang4 => "Lang4",
            Self::Lang5 => "Lang5",
            Self::NonConvert => "NonConvert",
            Self::Delete => "Delete",
            Self::End => "End",
            Self::Help => "Help",
            Self::Home => "Home",
            Self::Insert => "Insert",
            Self::PageDown => "PageDown",
            Self::PageUp => "PageUp",
            Self::ArrowDown => "ArrowDown",
            Self::ArrowLeft => "ArrowLeft",
            Self::ArrowRight => "ArrowRight",
            Self::ArrowUp => "ArrowUp",
            Self::NumLock => "NumLock",
            Self::Numpad0 => "Numpad0",
            Self::Numpad1 => "Numpad1",
            Self::Numpad2 => "Numpad2",
            Self::Numpad3 => "Numpad3",
            Self::Numpad4 => "Numpad4",
            Self::Numpad5 => "Numpad5",
            Self::Numpad6 => "Numpad6",
            Self::Numpad7 => "Numpad7",
            Self::Numpad8 => "Numpad8",
            Self::Numpad9 => "Numpad9",
            Self::NumpadAdd => "NumpadAdd",
            Self::NumpadBackspace => "NumpadBackspace",
            Self::NumpadClear => "NumpadClear",
            Self::NumpadClearEntry => "NumpadClearEntry",
            Self::NumpadComma => "NumpadComma",
            Self::NumpadDecimal => "NumpadDecimal",
            Self::NumpadDivide => "NumpadDivide",
            Self::NumpadEnter => "NumpadEnter",
            Self::NumpadEqual => "NumpadEqual",
            Self::NumpadHash => "NumpadHash",
            Self::NumpadMemoryAdd => "NumpadMemoryAdd",
            Self::NumpadMemoryClear => "NumpadMemoryClear",
            Self::NumpadMemoryRecall => "NumpadMemoryRecall",
            Self::NumpadMemoryStore => "NumpadMemoryStore",
            Self::NumpadMemorySubtract => "NumpadMemorySubtract",
            Self::NumpadMultiply => "NumpadMultiply",
            Self::NumpadParenLeft => "NumpadParenLeft",
            Self::NumpadParenRight => "NumpadParenRight",
            Self::NumpadStar => "NumpadStar",
            Self::NumpadSubtract => "NumpadSubtract",
            Self::Escape => "Escape",
            Self::Fn => "Fn",
            Self::FnLock => "FnLock",
            Self::PrintScreen => "PrintScreen",
            Self::ScrollLock => "ScrollLock",
            Self::Pause => "Pause",
            Self::BrowserBack => "BrowserBack",
            Self::BrowserFavorites => "BrowserFavorites",
            Self::BrowserForward => "BrowserForward",
            Self::BrowserHome => "BrowserHome",
            Self::BrowserRefresh => "BrowserRefresh",
            Self::BrowserSearch => "BrowserSearch",
            Self::BrowserStop => "BrowserStop",
            Self::Eject => "Eject",
            Self::LaunchApp1 => "LaunchApp1",
            Self::LaunchApp2 => "LaunchApp2",
            Self::LaunchMail => "LaunchMail",
            Self::MediaPlayPause => "MediaPlayPause",
            Self::MediaSelect => "MediaSelect",
            Self::MediaStop => "MediaStop",
            Self::MediaTrackNext => "MediaTrackNext",
            Self::MediaTrackPrevious => "MediaTrackPrevious",
            Self::Power => "Power",
            Self::Sleep => "Sleep",
            Self::AudioVolumeDown => "AudioVolumeDown",
            Self::AudioVolumeMute => "AudioVolumeMute",
            Self::AudioVolumeUp => "AudioVolumeUp",
            Self::WakeUp => "WakeUp",
            Self::Abort => "Abort",
            Self::Resume => "Resume",
            Self::Suspend => "Suspend",
            Self::Again => "Again",
            Self::Copy => "Copy",
            Self::Cut => "Cut",
            Self::Find => "Find",
            Self::Open => "Open",
            Self::Paste => "Paste",
            Self::Props => "Props",
            Self::Select => "Select",
            Self::Undo => "Undo",
            Self::Hiragana => "Hiragana",
            Self::Katakana => "Katakana",
            Self::Unidentified => "Unidentified",
            Self::F1 => "F1",
            Self::F2 => "F2",
            Self::F3 => "F3",
            Self::F4 => "F4",
            Self::F5 => "F5",
            Self::F6 => "F6",
            Self::F7 => "F7",
            Self::F8 => "F8",
            Self::F9 => "F9",
            Self::F10 => "F10",
            Self::F11 => "F11",
            Self::F12 => "F12",
            Self::F13 => "F13",
            Self::F14 => "F14",
            Self::F15 => "F15",
            Self::F16 => "F16",
            Self::F17 => "F17",
            Self::F18 => "F18",
            Self::F19 => "F19",
            Self::F20 => "F20",
            Self::F21 => "F21",
            Self::F22 => "F22",
            Self::F23 => "F23",
            Self::F24 => "F24",
            Self::F25 => "F25",
            Self::F26 => "F26",
            Self::F27 => "F27",
            Self::F28 => "F28",
            Self::F29 => "F29",
            Self::F30 => "F30",
            Self::F31 => "F31",
            Self::F32 => "F32",
            Self::F33 => "F33",
            Self::F34 => "F34",
            Self::F35 => "F35",
            Self::BrightnessDown => "BrightnessDown",
            Self::BrightnessUp => "BrightnessUp",
            Self::DisplayToggleIntExt => "DisplayToggleIntExt",
            Self::KeyboardLayoutSelect => "KeyboardLayoutSelect",
            Self::LaunchAssistant => "LaunchAssistant",
            Self::LaunchControlPanel => "LaunchControlPanel",
            Self::LaunchScreenSaver => "LaunchScreenSaver",
            Self::MailForward => "MailForward",
            Self::MailReply => "MailReply",
            Self::MailSend => "MailSend",
            Self::MediaFastForward => "MediaFastForward",
            Self::MediaPause => "MediaPause",
            Self::MediaPlay => "MediaPlay",
            Self::MediaRecord => "MediaRecord",
            Self::MediaRewind => "MediaRewind",
            Self::MicrophoneMuteToggle => "MicrophoneMuteToggle",
            Self::PrivacyScreenToggle => "PrivacyScreenToggle",
            Self::KeyboardBacklightToggle => "KeyboardBacklightToggle",
            Self::SelectTask => "SelectTask",
            Self::ShowAllWindows => "ShowAllWindows",
            Self::ZoomToggle => "ZoomToggle",
        }
    }

    /// The value the W3C spells `name`, or `None` for a spelling this table does not list.
    #[must_use]
    pub fn from_w3c(name: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|value| value.as_str() == name)
    }
}

impl core::fmt::Display for Code {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}
