// @generated by `cargo xtask key-vocabulary --write` from keyboard-types 0.8.3
// (src/named_key.rs, MIT OR Apache-2.0). Edit the generator, not this file.

//! [`NamedKey`], generated from the W3C value list.

#![allow(
    clippy::doc_markdown,
    reason = "the variant descriptions are the specification's prose"
)]

/// A key the W3C names: the `key` value of a key that produces no character.
///
/// The variants are the [UI Events `key` values](https://w3c.github.io/uievents-key/).
/// A value the specification adds before FLUI regenerates this table arrives as
/// [`NamedKey::Unidentified`].
///
/// # Examples
///
/// ```
/// use flui_platform_api::keyboard::NamedKey;
///
/// assert_eq!(NamedKey::Enter.as_str(), "Enter");
/// assert_eq!(NamedKey::from_w3c("Enter"), Some(NamedKey::Enter));
/// assert_eq!(NamedKey::from_w3c("NoSuchValue"), None);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum NamedKey {
    /// This key value is used when an implementation is unable to
    /// identify another key value, due to either hardware,
    /// platform, or software constraints.
    Unidentified,
    /// The <kbd>Alt</kbd> (Alternative) key.<br/> This key enables the alternate modifier function for interpreting concurrent or subsequent keyboard input.<br/> This key value is also used for the Apple <kbd>Option</kbd> key.
    Alt,
    /// The Alternate Graphics (<kbd>AltGr</kbd> or <kbd>AltGraph</kbd>) key.
    /// This key is used enable the ISO Level 3 shift modifier (the standard <kbd>Shift</kbd> key is the level 2 modifier).
    /// See [ISO9995-1].
    AltGraph,
    /// The <kbd>Caps Lock</kbd> (Capital) key.
    /// Toggle capital character lock function for interpreting subsequent keyboard input event.
    CapsLock,
    /// The <kbd>Control</kbd> or <kbd>Ctrl</kbd> key, to enable control modifier function for interpreting concurrent or subsequent keyboard input.
    Control,
    /// The Function switch <kbd>Fn</kbd> key.<br/> Activating this key simultaneously with another key changes that key’s value to an alternate character or function.
    /// This key is often handled directly in the keyboard hardware and does not usually generate key events.
    Fn,
    /// The Function-Lock (<kbd>FnLock</kbd> or <kbd>F-Lock</kbd>) key.
    /// Activating this key switches the mode of the keyboard to changes some keys' values to an alternate character or function.
    /// This key is often handled directly in the keyboard hardware and does not usually generate key events.
    FnLock,
    /// The <kbd>Meta</kbd> key, to enable meta modifier function for interpreting concurrent or subsequent keyboard input.
    /// This key value is used for the <q>Windows Logo</q> key and the Apple <kbd>Command</kbd> or <kbd>⌘</kbd> key.
    /// In Linux (XKB) terminology, this is often referred to as "Super".
    #[doc(alias = "Super")]
    Meta,
    /// The <kbd>NumLock</kbd> or Number Lock key, to toggle numpad mode function for interpreting subsequent keyboard input.
    NumLock,
    /// The <kbd>Scroll Lock</kbd> key, to toggle between scrolling and cursor movement modes.
    ScrollLock,
    /// The <kbd>Shift</kbd> key, to enable shift modifier function for interpreting concurrent or subsequent keyboard input.
    Shift,
    /// The Symbol modifier key (used on some virtual keyboards).
    Symbol,
    /// The Symbol Lock key.
    SymbolLock,
    /// The <kbd>Enter</kbd> or <kbd>↵</kbd> key, to activate current selection or accept current input.<br/> This key value is also used for the <kbd>Return</kbd> (Macintosh numpad) key.<br/> This key value is also used for the Android <code class="android">KEYCODE_DPAD_CENTER</code>.
    #[doc(alias = "Return")]
    Enter,
    /// The Horizontal Tabulation <kbd>Tab</kbd> key.
    Tab,
    /// The down arrow key, to navigate or traverse downward. (<code class="android">KEYCODE_DPAD_DOWN</code>)
    ArrowDown,
    /// The left arrow key, to navigate or traverse leftward. (<code class="android">KEYCODE_DPAD_LEFT</code>)
    ArrowLeft,
    /// The right arrow key, to navigate or traverse rightward. (<code class="android">KEYCODE_DPAD_RIGHT</code>)
    ArrowRight,
    /// The up arrow key, to navigate or traverse upward. (<code class="android">KEYCODE_DPAD_UP</code>)
    ArrowUp,
    /// The End key, used with keyboard entry to go to the end of content (<code class="android">KEYCODE_MOVE_END</code>).
    End,
    /// The Home key, used with keyboard entry, to go to start of content (<code class="android">KEYCODE_MOVE_HOME</code>).<br/> For the mobile phone <kbd>Home</kbd> key (which goes to the phone’s main screen), use [`GoHome`][NamedKey::GoHome].
    Home,
    /// The Page Down key, to scroll down or display next page of content.
    PageDown,
    /// The Page Up key, to scroll up or display previous page of content.
    PageUp,
    /// The Backspace key. This key value is also used for the key labeled <kbd>Delete</kbd> on MacOS keyboards.
    Backspace,
    /// Remove the currently selected input.
    Clear,
    /// Copy the current selection. (<code class="appcommand">APPCOMMAND_COPY</code>)
    Copy,
    /// The Cursor Select (Crsel) key.
    CrSel,
    /// Cut the current selection. (<code class="appcommand">APPCOMMAND_CUT</code>)
    Cut,
    /// The Delete (Del) Key.
    /// This key value is also used for the key labeled <kbd>Delete</kbd> on MacOS keyboards when modified by the <kbd>Fn</kbd> key.
    Delete,
    /// The Erase to End of Field key.
    /// This key deletes all characters from the current cursor position to the end of the current field.
    EraseEof,
    /// The Extend Selection (Exsel) key.
    ExSel,
    /// The Insert (Ins) key, to toggle between text modes for insertion or overtyping. (<code class="android">KEYCODE_INSERT</code>)
    Insert,
    /// The Paste key. (<code class="appcommand">APPCOMMAND_PASTE</code>)
    Paste,
    /// Redo the last action. (<code class="appcommand">APPCOMMAND_REDO</code>)
    Redo,
    /// Undo the last action. (<code class="appcommand">APPCOMMAND_UNDO</code>)
    Undo,
    /// The Accept (Commit, OK) key. Accept current option or input method sequence conversion.
    Accept,
    /// The Again key, to redo or repeat an action.
    Again,
    /// The Attention (Attn) key.
    Attn,
    /// The Cancel key.
    Cancel,
    /// Show the application’s context menu.
    /// This key is commonly found between the right <kbd>Meta</kbd> key and the right <kbd>Control</kbd> key.
    ContextMenu,
    /// The <kbd>Esc</kbd> key. This key was originally used to initiate an escape sequence, but is
    /// now more generally used to exit or "escape" the current context, such as closing a dialog
    /// or exiting full screen mode.
    Escape,
    /// The Execute key.
    Execute,
    /// Open the Find dialog. (<code class="appcommand">APPCOMMAND_FIND</code>)
    Find,
    /// Open a help dialog or toggle display of help information. (<code class="appcommand"><code class="appcommand">APPCOMMAND_HELP</code></code>, <code class="android"><code class="android">KEYCODE_HELP</code></code>)
    Help,
    /// Pause the current state or application (as appropriate).
    /// <p class="note" role="note">Do not use this value for the <kbd>Pause</kbd> button on media controllers. Use [`MediaPause`][NamedKey::MediaPause] instead.</p>
    Pause,
    /// Play or resume the current state or application (as appropriate).
    /// <p class="note" role="note">Do not use this value for the <kbd>Play</kbd> button on media controllers. Use [`MediaPlay`][NamedKey::MediaPlay] instead.</p>
    Play,
    /// The properties (Props) key.
    Props,
    /// The Select key.
    Select,
    /// The ZoomIn key. (<code class="android">KEYCODE_ZOOM_IN</code>)
    ZoomIn,
    /// The ZoomOut key. (<code class="android">KEYCODE_ZOOM_OUT</code>)
    ZoomOut,
    /// The Brightness Down key. Typically controls the display brightness. (<code class="android">KEYCODE_BRIGHTNESS_DOWN</code>)
    BrightnessDown,
    /// The Brightness Up key. Typically controls the display brightness. (<code class="android">KEYCODE_BRIGHTNESS_UP</code>)
    BrightnessUp,
    /// Toggle removable media to eject (open) and insert (close) state. (<code class="android">KEYCODE_MEDIA_EJECT</code>)
    Eject,
    /// The LogOff key.
    LogOff,
    /// Toggle power state. (<code class="android">KEYCODE_POWER</code>)
    /// <p class="note" role="note">Note: Some devices might not expose this key to the operating environment.</p>
    Power,
    /// The <kbd>PowerOff</kbd> key. Sometime called <kbd>PowerDown</kbd>.
    PowerOff,
    /// The <kbd>Print Screen</kbd> or <kbd>SnapShot</kbd> key, to initiate print-screen function.
    PrintScreen,
    /// The Hibernate key.
    /// This key saves the current state of the computer to disk so that it can be restored. The computer will then shutdown.
    Hibernate,
    /// The Standby key.
    /// This key turns off the display and places the computer into a low-power mode without completely shutting down.
    /// It is sometimes labelled <kbd>Suspend</kbd> or <kbd>Sleep</kbd> key. (<code class="android"><code class="android">KEYCODE_SLEEP</code></code>)
    Standby,
    /// The WakeUp key. (<code class="android">KEYCODE_WAKEUP</code>)
    WakeUp,
    /// The All Candidates key, to initiate the multi-candidate mode.
    AllCandidates,
    /// The Alphanumeric key.
    Alphanumeric,
    /// The Code Input key, to initiate the Code Input mode to allow characters to be entered by their code points.
    CodeInput,
    /// The Compose key, also known as <em>Multi_key</em> on the X Window System.
    /// This key acts in a manner similar to a
    /// dead key, triggering a mode where subsequent key presses are combined to produce a different character.
    Compose,
    /// The Convert key, to convert the current input method sequence.
    Convert,
    /// A dead key combining key. It may be any combining key from any keyboard layout. For example, on a
    /// PC/AT French keyboard, using a French mapping and without any modifier activated, this is the key value <code class="unicode">U+0302</code> COMBINING CIRCUMFLEX ACCENT. In another layout this might be a different unicode combining key.<br/> For applications that need to differentiate between specific combining characters, the associated compositionupdate event’s data attribute provides the specific key value.
    Dead,
    /// The Final Mode <kbd>Final</kbd> key used on some Asian keyboards, to enable the final mode for IMEs.
    FinalMode,
    /// Switch to the first character group. (ISO/IEC 9995)
    GroupFirst,
    /// Switch to the last character group. (ISO/IEC 9995)
    GroupLast,
    /// Switch to the next character group. (ISO/IEC 9995)
    GroupNext,
    /// Switch to the previous character group. (ISO/IEC 9995)
    GroupPrevious,
    /// The Mode Change key, to toggle between or cycle through input modes of IMEs.
    ModeChange,
    /// The Next Candidate function key.
    NextCandidate,
    /// The NonConvert ("Don’t Convert") key, to accept current input method sequence without conversion in IMEs.
    NonConvert,
    /// The Previous Candidate function key.
    PreviousCandidate,
    /// The Process key.
    Process,
    /// The Single Candidate function key.
    SingleCandidate,
    /// The Hangul (Korean characters) Mode key, to toggle between Hangul and English modes.
    HangulMode,
    /// The Hanja (Korean characters) Mode key.
    HanjaMode,
    /// The Junja (Korean characters) Mode key.
    JunjaMode,
    /// The Eisu key. This key may close the IME, but its purpose
    /// is defined by the current IME. (<code class="android">KEYCODE_EISU</code>)
    Eisu,
    /// The (Half-Width) Characters key.
    Hankaku,
    /// The Hiragana (Japanese Kana characters) key.
    Hiragana,
    /// The Hiragana/Katakana toggle key. (<code class="android">KEYCODE_KATAKANA_HIRAGANA</code>)
    HiraganaKatakana,
    /// The Kana Mode (Kana Lock) key. This key is used to enter
    /// hiragana mode (typically from romaji mode).
    KanaMode,
    /// The Kanji (Japanese name for ideographic characters of Chinese origin) Mode key.
    /// This key is typically used to switch to a hiragana keyboard for
    /// the purpose of converting input into kanji. (<code class="android">KEYCODE_KANA</code>)
    KanjiMode,
    /// The Katakana (Japanese Kana characters) key.
    Katakana,
    /// The Roman characters function key.
    Romaji,
    /// The Zenkaku (Full-Width) Characters key.
    Zenkaku,
    /// The Zenkaku/Hankaku (full-width/half-width) toggle key. (<code class="android">KEYCODE_ZENKAKU_HANKAKU</code>)
    ZenkakuHankaku,
    /// General purpose virtual function key, as index 1.
    Soft1,
    /// General purpose virtual function key, as index 2.
    Soft2,
    /// General purpose virtual function key, as index 3.
    Soft3,
    /// General purpose virtual function key, as index 4.
    Soft4,
    /// Select next (numerically or logically) lower channel. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MEDIA_CHANNEL_DOWN</code></code>, <code class="android"><code class="android">KEYCODE_CHANNEL_DOWN</code></code>)
    ChannelDown,
    /// Select next (numerically or logically) higher channel. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MEDIA_CHANNEL_UP</code></code>, <code class="android"><code class="android">KEYCODE_CHANNEL_UP</code></code>)
    ChannelUp,
    /// Close the current document or message (Note: This doesn’t close the application). (<code class="appcommand">APPCOMMAND_CLOSE</code>)
    Close,
    /// Open an editor to forward the current message. (<code class="appcommand">APPCOMMAND_FORWARD_MAIL</code>)
    MailForward,
    /// Open an editor to reply to the current message. (<code class="appcommand">APPCOMMAND_REPLY_TO_MAIL</code>)
    MailReply,
    /// Send the current message. (<code class="appcommand">APPCOMMAND_SEND_MAIL</code>)
    MailSend,
    /// Close the current media, for example to close a CD or DVD tray. (<code class="android">KEYCODE_MEDIA_CLOSE</code>)
    MediaClose,
    /// Initiate or continue forward playback at faster than normal speed, or increase speed if already fast forwarding. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MEDIA_FAST_FORWARD</code></code>, <code class="android"><code class="android">KEYCODE_MEDIA_FAST_FORWARD</code></code>)
    MediaFastForward,
    /// Pause the currently playing media. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MEDIA_PAUSE</code></code>, <code class="android"><code class="android">KEYCODE_MEDIA_PAUSE</code></code>)
    /// <p class="note" role="note">Media controller devices should use this value rather than [`Pause`][NamedKey::Pause] for their pause keys.</p>
    MediaPause,
    /// Initiate or continue media playback at normal speed, if not currently playing at normal speed. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MEDIA_PLAY</code></code>, <code class="android"><code class="android">KEYCODE_MEDIA_PLAY</code></code>)
    MediaPlay,
    /// Toggle media between play and pause states. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MEDIA_PLAY_PAUSE</code></code>, <code class="android"><code class="android">KEYCODE_MEDIA_PLAY_PAUSE</code></code>)
    MediaPlayPause,
    /// Initiate or resume recording of currently selected media. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MEDIA_RECORD</code></code>, <code class="android"><code class="android">KEYCODE_MEDIA_RECORD</code></code>)
    MediaRecord,
    /// Initiate or continue reverse playback at faster than normal speed, or increase speed if already rewinding. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MEDIA_REWIND</code></code>, <code class="android"><code class="android">KEYCODE_MEDIA_REWIND</code></code>)
    MediaRewind,
    /// Stop media playing, pausing, forwarding, rewinding, or recording, if not already stopped. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MEDIA_STOP</code></code>, <code class="android"><code class="android">KEYCODE_MEDIA_STOP</code></code>)
    MediaStop,
    /// Seek to next media or program track. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MEDIA_NEXTTRACK</code></code>, <code class="android"><code class="android">KEYCODE_MEDIA_NEXT</code></code>)
    MediaTrackNext,
    /// Seek to previous media or program track. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MEDIA_PREVIOUSTRACK</code></code>, <code class="android"><code class="android">KEYCODE_MEDIA_PREVIOUS</code></code>)
    MediaTrackPrevious,
    /// Open a new document or message. (<code class="appcommand">APPCOMMAND_NEW</code>)
    New,
    /// Open an existing document or message. (<code class="appcommand">APPCOMMAND_OPEN</code>)
    Open,
    /// Print the current document or message. (<code class="appcommand">APPCOMMAND_PRINT</code>)
    Print,
    /// Save the current document or message. (<code class="appcommand">APPCOMMAND_SAVE</code>)
    Save,
    /// Spellcheck the current document or selection. (<code class="appcommand">APPCOMMAND_SPELL_CHECK</code>)
    SpellCheck,
    /// The <kbd>11</kbd> key found on media numpads that
    /// have buttons from <kbd>1</kbd> ... <kbd>12</kbd>.
    Key11,
    /// The <kbd>12</kbd> key found on media numpads that
    /// have buttons from <kbd>1</kbd> ... <kbd>12</kbd>.
    Key12,
    /// Adjust audio balance leftward. (<code class="vk">VK_AUDIO_BALANCE_LEFT</code>)
    AudioBalanceLeft,
    /// Adjust audio balance rightward. (<code class="vk">VK_AUDIO_BALANCE_RIGHT</code>)
    AudioBalanceRight,
    /// Decrease audio bass boost or cycle down through bass boost states. (<code class="appcommand"><code class="appcommand">APPCOMMAND_BASS_DOWN</code></code>, <code class="vk"><code class="vk">VK_BASS_BOOST_DOWN</code></code>)
    AudioBassBoostDown,
    /// Toggle bass boost on/off. (<code class="appcommand">APPCOMMAND_BASS_BOOST</code>)
    AudioBassBoostToggle,
    /// Increase audio bass boost or cycle up through bass boost states. (<code class="appcommand"><code class="appcommand">APPCOMMAND_BASS_UP</code></code>, <code class="vk"><code class="vk">VK_BASS_BOOST_UP</code></code>)
    AudioBassBoostUp,
    /// Adjust audio fader towards front. (<code class="vk">VK_FADER_FRONT</code>)
    AudioFaderFront,
    /// Adjust audio fader towards rear. (<code class="vk">VK_FADER_REAR</code>)
    AudioFaderRear,
    /// Advance surround audio mode to next available mode. (<code class="vk">VK_SURROUND_MODE_NEXT</code>)
    AudioSurroundModeNext,
    /// Decrease treble. (<code class="appcommand">APPCOMMAND_TREBLE_DOWN</code>)
    AudioTrebleDown,
    /// Increase treble. (<code class="appcommand">APPCOMMAND_TREBLE_UP</code>)
    AudioTrebleUp,
    /// Decrease audio volume. (<code class="appcommand"><code class="appcommand">APPCOMMAND_VOLUME_DOWN</code></code>, <code class="android"><code class="android">KEYCODE_VOLUME_DOWN</code></code>)
    AudioVolumeDown,
    /// Increase audio volume. (<code class="appcommand"><code class="appcommand">APPCOMMAND_VOLUME_UP</code></code>, <code class="android"><code class="android">KEYCODE_VOLUME_UP</code></code>)
    AudioVolumeUp,
    /// Toggle between muted state and prior volume level. (<code class="appcommand"><code class="appcommand">APPCOMMAND_VOLUME_MUTE</code></code>, <code class="android"><code class="android">KEYCODE_VOLUME_MUTE</code></code>)
    AudioVolumeMute,
    /// Toggle the microphone on/off. (<code class="appcommand">APPCOMMAND_MIC_ON_OFF_TOGGLE</code>)
    MicrophoneToggle,
    /// Decrease microphone volume. (<code class="appcommand">APPCOMMAND_MICROPHONE_VOLUME_DOWN</code>)
    MicrophoneVolumeDown,
    /// Increase microphone volume. (<code class="appcommand">APPCOMMAND_MICROPHONE_VOLUME_UP</code>)
    MicrophoneVolumeUp,
    /// Mute the microphone. (<code class="appcommand"><code class="appcommand">APPCOMMAND_MICROPHONE_VOLUME_MUTE</code></code>, <code class="android"><code class="android">KEYCODE_MUTE</code></code>)
    MicrophoneVolumeMute,
    /// Show correction list when a word is incorrectly identified. (<code class="appcommand">APPCOMMAND_CORRECTION_LIST</code>)
    SpeechCorrectionList,
    /// Toggle between dictation mode and command/control mode. (<code class="appcommand">APPCOMMAND_DICTATE_OR_COMMAND_CONTROL_TOGGLE</code>)
    SpeechInputToggle,
    /// The first generic "LaunchApplication" key. This is commonly associated with launching "My Computer", and may have a computer symbol on the key. (<code class="appcommand">APPCOMMAND_LAUNCH_APP1</code>)
    LaunchApplication1,
    /// The second generic "LaunchApplication" key. This is commonly associated with launching "Calculator", and may have a calculator symbol on the key. (<code class="appcommand"><code class="appcommand">APPCOMMAND_LAUNCH_APP2</code></code>, <code class="android"><code class="android">KEYCODE_CALCULATOR</code></code>)
    LaunchApplication2,
    /// The "Calendar" key. (<code class="android">KEYCODE_CALENDAR</code>)
    LaunchCalendar,
    /// The "Contacts" key. (<code class="android">KEYCODE_CONTACTS</code>)
    LaunchContacts,
    /// The "Mail" key. (<code class="appcommand">APPCOMMAND_LAUNCH_MAIL</code>)
    LaunchMail,
    /// The "Media Player" key. (<code class="appcommand">APPCOMMAND_LAUNCH_MEDIA_SELECT</code>)
    LaunchMediaPlayer,
    /// The "Music Player" key.
    LaunchMusicPlayer,
    /// The "Phone" key.
    LaunchPhone,
    /// The "Screen Saver" key.
    LaunchScreenSaver,
    /// The "Spreadsheet" key.
    LaunchSpreadsheet,
    /// The "Web Browser" key.
    LaunchWebBrowser,
    /// The "WebCam" key.
    LaunchWebCam,
    /// The "Word Processor" key.
    LaunchWordProcessor,
    /// Navigate to previous content or page in current history. (<code class="appcommand">APPCOMMAND_BROWSER_BACKWARD</code>)
    BrowserBack,
    /// Open the list of browser favorites. (<code class="appcommand">APPCOMMAND_BROWSER_FAVORITES</code>)
    BrowserFavorites,
    /// Navigate to next content or page in current history. (<code class="appcommand">APPCOMMAND_BROWSER_FORWARD</code>)
    BrowserForward,
    /// Go to the user’s preferred home page. (<code class="appcommand">APPCOMMAND_BROWSER_HOME</code>)
    BrowserHome,
    /// Refresh the current page or content. (<code class="appcommand">APPCOMMAND_BROWSER_REFRESH</code>)
    BrowserRefresh,
    /// Call up the user’s preferred search page. (<code class="appcommand">APPCOMMAND_BROWSER_SEARCH</code>)
    BrowserSearch,
    /// Stop loading the current page or content. (<code class="appcommand">APPCOMMAND_BROWSER_STOP</code>)
    BrowserStop,
    /// The Application switch key, which provides a list of recent apps to switch between. (<code class="android">KEYCODE_APP_SWITCH</code>)
    AppSwitch,
    /// The Call key. (<code class="android">KEYCODE_CALL</code>)
    Call,
    /// The Camera key. (<code class="android">KEYCODE_CAMERA</code>)
    Camera,
    /// The Camera focus key. (<code class="android">KEYCODE_FOCUS</code>)
    CameraFocus,
    /// The End Call key. (<code class="android">KEYCODE_ENDCALL</code>)
    EndCall,
    /// The Back key. (<code class="android">KEYCODE_BACK</code>)
    GoBack,
    /// The Home key, which goes to the phone’s main screen. (<code class="android">KEYCODE_HOME</code>)
    GoHome,
    /// The Headset Hook key. (<code class="android">KEYCODE_HEADSETHOOK</code>)
    HeadsetHook,
    /// The Last Number Redial key.
    LastNumberRedial,
    /// The Notification key. (<code class="android">KEYCODE_NOTIFICATION</code>)
    Notification,
    /// Toggle between manner mode state: silent, vibrate, ring, ... (<code class="android">KEYCODE_MANNER_MODE</code>)
    MannerMode,
    /// The Voice Dial key.
    VoiceDial,
    /// Switch to viewing TV. (<code class="android">KEYCODE_TV</code>)
    TV,
    /// TV 3D Mode. (<code class="android">KEYCODE_3D_MODE</code>)
    TV3DMode,
    /// Toggle between antenna and cable input. (<code class="android">KEYCODE_TV_ANTENNA_CABLE</code>)
    TVAntennaCable,
    /// Audio description. (<code class="android">KEYCODE_TV_AUDIO_DESCRIPTION</code>)
    TVAudioDescription,
    /// Audio description mixing volume down. (<code class="android">KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN</code>)
    TVAudioDescriptionMixDown,
    /// Audio description mixing volume up. (<code class="android">KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP</code>)
    TVAudioDescriptionMixUp,
    /// Contents menu. (<code class="android">KEYCODE_TV_CONTENTS_MENU</code>)
    TVContentsMenu,
    /// Contents menu. (<code class="android">KEYCODE_TV_DATA_SERVICE</code>)
    TVDataService,
    /// Switch the input mode on an external TV. (<code class="android">KEYCODE_TV_INPUT</code>)
    TVInput,
    /// Switch to component input #1. (<code class="android">KEYCODE_TV_INPUT_COMPONENT_1</code>)
    TVInputComponent1,
    /// Switch to component input #2. (<code class="android">KEYCODE_TV_INPUT_COMPONENT_2</code>)
    TVInputComponent2,
    /// Switch to composite input #1. (<code class="android">KEYCODE_TV_INPUT_COMPOSITE_1</code>)
    TVInputComposite1,
    /// Switch to composite input #2. (<code class="android">KEYCODE_TV_INPUT_COMPOSITE_2</code>)
    TVInputComposite2,
    /// Switch to HDMI input #1. (<code class="android">KEYCODE_TV_INPUT_HDMI_1</code>)
    TVInputHDMI1,
    /// Switch to HDMI input #2. (<code class="android">KEYCODE_TV_INPUT_HDMI_2</code>)
    TVInputHDMI2,
    /// Switch to HDMI input #3. (<code class="android">KEYCODE_TV_INPUT_HDMI_3</code>)
    TVInputHDMI3,
    /// Switch to HDMI input #4. (<code class="android">KEYCODE_TV_INPUT_HDMI_4</code>)
    TVInputHDMI4,
    /// Switch to VGA input #1. (<code class="android">KEYCODE_TV_INPUT_VGA_1</code>)
    TVInputVGA1,
    /// Media context menu. (<code class="android">KEYCODE_TV_MEDIA_CONTEXT_MENU</code>)
    TVMediaContext,
    /// Toggle network. (<code class="android">KEYCODE_TV_NETWORK</code>)
    TVNetwork,
    /// Number entry. (<code class="android">KEYCODE_TV_NUMBER_ENTRY</code>)
    TVNumberEntry,
    /// Toggle the power on an external TV. (<code class="android">KEYCODE_TV_POWER</code>)
    TVPower,
    /// Radio. (<code class="android">KEYCODE_TV_RADIO_SERVICE</code>)
    TVRadioService,
    /// Satellite. (<code class="android">KEYCODE_TV_SATELLITE</code>)
    TVSatellite,
    /// Broadcast Satellite. (<code class="android">KEYCODE_TV_SATELLITE_BS</code>)
    TVSatelliteBS,
    /// Communication Satellite. (<code class="android">KEYCODE_TV_SATELLITE_CS</code>)
    TVSatelliteCS,
    /// Toggle between available satellites. (<code class="android">KEYCODE_TV_SATELLITE_SERVICE</code>)
    TVSatelliteToggle,
    /// Analog Terrestrial. (<code class="android">KEYCODE_TV_TERRESTRIAL_ANALOG</code>)
    TVTerrestrialAnalog,
    /// Digital Terrestrial. (<code class="android">KEYCODE_TV_TERRESTRIAL_DIGITAL</code>)
    TVTerrestrialDigital,
    /// Timer programming. (<code class="android">KEYCODE_TV_TIMER_PROGRAMMING</code>)
    TVTimer,
    /// Switch the input mode on an external AVR (audio/video receiver). (<code class="android">KEYCODE_AVR_INPUT</code>)
    AVRInput,
    /// Toggle the power on an external AVR (audio/video receiver). (<code class="android">KEYCODE_AVR_POWER</code>)
    AVRPower,
    /// General purpose color-coded media function key, as index 0 (red). (<code class="vk"><code class="vk">VK_COLORED_KEY_0</code></code>, <code class="android"><code class="android">KEYCODE_PROG_RED</code></code>)
    ColorF0Red,
    /// General purpose color-coded media function key, as index 1 (green). (<code class="vk"><code class="vk">VK_COLORED_KEY_1</code></code>, <code class="android"><code class="android">KEYCODE_PROG_GREEN</code></code>)
    ColorF1Green,
    /// General purpose color-coded media function key, as index 2 (yellow). (<code class="vk"><code class="vk">VK_COLORED_KEY_2</code></code>, <code class="android"><code class="android">KEYCODE_PROG_YELLOW</code></code>)
    ColorF2Yellow,
    /// General purpose color-coded media function key, as index 3 (blue). (<code class="vk"><code class="vk">VK_COLORED_KEY_3</code></code>, <code class="android"><code class="android">KEYCODE_PROG_BLUE</code></code>)
    ColorF3Blue,
    /// General purpose color-coded media function key, as index 4 (grey). (<code class="vk">VK_COLORED_KEY_4</code>)
    ColorF4Grey,
    /// General purpose color-coded media function key, as index 5 (brown). (<code class="vk">VK_COLORED_KEY_5</code>)
    ColorF5Brown,
    /// Toggle the display of Closed Captions. (<code class="vk"><code class="vk">VK_CC</code></code>, <code class="android"><code class="android">KEYCODE_CAPTIONS</code></code>)
    ClosedCaptionToggle,
    /// Adjust brightness of device, by toggling between or cycling through states. (<code class="vk">VK_DIMMER</code>)
    Dimmer,
    /// Swap video sources. (<code class="vk">VK_DISPLAY_SWAP</code>)
    DisplaySwap,
    /// Select Digital Video Rrecorder. (<code class="android">KEYCODE_DVR</code>)
    DVR,
    /// Exit the current application. (<code class="vk">VK_EXIT</code>)
    Exit,
    /// Clear program or content stored as favorite 0. (<code class="vk">VK_CLEAR_FAVORITE_0</code>)
    FavoriteClear0,
    /// Clear program or content stored as favorite 1. (<code class="vk">VK_CLEAR_FAVORITE_1</code>)
    FavoriteClear1,
    /// Clear program or content stored as favorite 2. (<code class="vk">VK_CLEAR_FAVORITE_2</code>)
    FavoriteClear2,
    /// Clear program or content stored as favorite 3. (<code class="vk">VK_CLEAR_FAVORITE_3</code>)
    FavoriteClear3,
    /// Select (recall) program or content stored as favorite 0. (<code class="vk">VK_RECALL_FAVORITE_0</code>)
    FavoriteRecall0,
    /// Select (recall) program or content stored as favorite 1. (<code class="vk">VK_RECALL_FAVORITE_1</code>)
    FavoriteRecall1,
    /// Select (recall) program or content stored as favorite 2. (<code class="vk">VK_RECALL_FAVORITE_2</code>)
    FavoriteRecall2,
    /// Select (recall) program or content stored as favorite 3. (<code class="vk">VK_RECALL_FAVORITE_3</code>)
    FavoriteRecall3,
    /// Store current program or content as favorite 0. (<code class="vk">VK_STORE_FAVORITE_0</code>)
    FavoriteStore0,
    /// Store current program or content as favorite 1. (<code class="vk">VK_STORE_FAVORITE_1</code>)
    FavoriteStore1,
    /// Store current program or content as favorite 2. (<code class="vk">VK_STORE_FAVORITE_2</code>)
    FavoriteStore2,
    /// Store current program or content as favorite 3. (<code class="vk">VK_STORE_FAVORITE_3</code>)
    FavoriteStore3,
    /// Toggle display of program or content guide. (<code class="vk"><code class="vk">VK_GUIDE</code></code>, <code class="android"><code class="android">KEYCODE_GUIDE</code></code>)
    Guide,
    /// If guide is active and displayed, then display next day’s content. (<code class="vk">VK_NEXT_DAY</code>)
    GuideNextDay,
    /// If guide is active and displayed, then display previous day’s content. (<code class="vk">VK_PREV_DAY</code>)
    GuidePreviousDay,
    /// Toggle display of information about currently selected context or media. (<code class="vk"><code class="vk">VK_INFO</code></code>, <code class="android"><code class="android">KEYCODE_INFO</code></code>)
    Info,
    /// Toggle instant replay. (<code class="vk">VK_INSTANT_REPLAY</code>)
    InstantReplay,
    /// Launch linked content, if available and appropriate. (<code class="vk">VK_LINK</code>)
    Link,
    /// List the current program. (<code class="vk">VK_LIST</code>)
    ListProgram,
    /// Toggle display listing of currently available live content or programs. (<code class="vk">VK_LIVE</code>)
    LiveContent,
    /// Lock or unlock current content or program. (<code class="vk">VK_LOCK</code>)
    Lock,
    /// Show a list of media applications: audio/video players and image viewers. (<code class="vk">VK_APPS</code>)
    /// <p class="note" role="note">Do not confuse this key value with the Windows' <code class="vk"><code class="vk">VK_APPS</code></code> / <code class="vk"><code class="vk">VK_CONTEXT_MENU</code></code> key, which is encoded as [`ContextMenu`][NamedKey::ContextMenu].</p>
    MediaApps,
    /// Audio track key. (<code class="android">KEYCODE_MEDIA_AUDIO_TRACK</code>)
    MediaAudioTrack,
    /// Select previously selected channel or media. (<code class="vk"><code class="vk">VK_LAST</code></code>, <code class="android"><code class="android">KEYCODE_LAST_CHANNEL</code></code>)
    MediaLast,
    /// Skip backward to next content or program. (<code class="android">KEYCODE_MEDIA_SKIP_BACKWARD</code>)
    MediaSkipBackward,
    /// Skip forward to next content or program. (<code class="vk"><code class="vk">VK_SKIP</code></code>, <code class="android"><code class="android">KEYCODE_MEDIA_SKIP_FORWARD</code></code>)
    MediaSkipForward,
    /// Step backward to next content or program. (<code class="android">KEYCODE_MEDIA_STEP_BACKWARD</code>)
    MediaStepBackward,
    /// Step forward to next content or program. (<code class="android">KEYCODE_MEDIA_STEP_FORWARD</code>)
    MediaStepForward,
    /// Media top menu. (<code class="android">KEYCODE_MEDIA_TOP_MENU</code>)
    MediaTopMenu,
    /// Navigate in. (<code class="android">KEYCODE_NAVIGATE_IN</code>)
    NavigateIn,
    /// Navigate to next key. (<code class="android">KEYCODE_NAVIGATE_NEXT</code>)
    NavigateNext,
    /// Navigate out. (<code class="android">KEYCODE_NAVIGATE_OUT</code>)
    NavigateOut,
    /// Navigate to previous key. (<code class="android">KEYCODE_NAVIGATE_PREVIOUS</code>)
    NavigatePrevious,
    /// Cycle to next favorite channel (in favorites list). (<code class="vk">VK_NEXT_FAVORITE_CHANNEL</code>)
    NextFavoriteChannel,
    /// Cycle to next user profile (if there are multiple user profiles). (<code class="vk">VK_USER</code>)
    NextUserProfile,
    /// Access on-demand content or programs. (<code class="vk">VK_ON_DEMAND</code>)
    OnDemand,
    /// Pairing key to pair devices. (<code class="android">KEYCODE_PAIRING</code>)
    Pairing,
    /// Move picture-in-picture window down. (<code class="vk">VK_PINP_DOWN</code>)
    PinPDown,
    /// Move picture-in-picture window. (<code class="vk">VK_PINP_MOVE</code>)
    PinPMove,
    /// Toggle display of picture-in-picture window. (<code class="vk">VK_PINP_TOGGLE</code>)
    PinPToggle,
    /// Move picture-in-picture window up. (<code class="vk">VK_PINP_UP</code>)
    PinPUp,
    /// Decrease media playback speed. (<code class="vk">VK_PLAY_SPEED_DOWN</code>)
    PlaySpeedDown,
    /// Reset playback to normal speed. (<code class="vk">VK_PLAY_SPEED_RESET</code>)
    PlaySpeedReset,
    /// Increase media playback speed. (<code class="vk">VK_PLAY_SPEED_UP</code>)
    PlaySpeedUp,
    /// Toggle random media or content shuffle mode. (<code class="vk">VK_RANDOM_TOGGLE</code>)
    RandomToggle,
    /// Not a physical key, but this key code is sent when the remote control battery is low. (<code class="vk">VK_RC_LOW_BATTERY</code>)
    RcLowBattery,
    /// Toggle or cycle between media recording speeds. (<code class="vk">VK_RECORD_SPEED_NEXT</code>)
    RecordSpeedNext,
    /// Toggle RF (radio frequency) input bypass mode (pass RF input directly to the RF output). (<code class="vk">VK_RF_BYPASS</code>)
    RfBypass,
    /// Toggle scan channels mode. (<code class="vk">VK_SCAN_CHANNELS_TOGGLE</code>)
    ScanChannelsToggle,
    /// Advance display screen mode to next available mode. (<code class="vk">VK_SCREEN_MODE_NEXT</code>)
    ScreenModeNext,
    /// Toggle display of device settings screen. (<code class="vk"><code class="vk">VK_SETTINGS</code></code>, <code class="android"><code class="android">KEYCODE_SETTINGS</code></code>)
    Settings,
    /// Toggle split screen mode. (<code class="vk">VK_SPLIT_SCREEN_TOGGLE</code>)
    SplitScreenToggle,
    /// Switch the input mode on an external STB (set top box). (<code class="android">KEYCODE_STB_INPUT</code>)
    STBInput,
    /// Toggle the power on an external STB (set top box). (<code class="android">KEYCODE_STB_POWER</code>)
    STBPower,
    /// Toggle display of subtitles, if available. (<code class="vk">VK_SUBTITLE</code>)
    Subtitle,
    /// Toggle display of teletext, if available (<code class="vk"><code class="vk">VK_TELETEXT</code></code>, <code class="android"><code class="android">KEYCODE_TV_TELETEXT</code></code>).
    Teletext,
    /// Advance video mode to next available mode. (<code class="vk">VK_VIDEO_MODE_NEXT</code>)
    VideoModeNext,
    /// Cause device to identify itself in some manner, e.g., audibly or visibly. (<code class="vk">VK_WINK</code>)
    Wink,
    /// Toggle between full-screen and scaled content, or alter magnification level. (<code class="vk"><code class="vk">VK_ZOOM</code></code>, <code class="android"><code class="android">KEYCODE_TV_ZOOM_MODE</code></code>)
    ZoomToggle,
    /// The F1 key, a general purpose function key, as index 1.
    F1,
    /// The F2 key, a general purpose function key, as index 2.
    F2,
    /// The F3 key, a general purpose function key, as index 3.
    F3,
    /// The F4 key, a general purpose function key, as index 4.
    F4,
    /// The F5 key, a general purpose function key, as index 5.
    F5,
    /// The F6 key, a general purpose function key, as index 6.
    F6,
    /// The F7 key, a general purpose function key, as index 7.
    F7,
    /// The F8 key, a general purpose function key, as index 8.
    F8,
    /// The F9 key, a general purpose function key, as index 9.
    F9,
    /// The F10 key, a general purpose function key, as index 10.
    F10,
    /// The F11 key, a general purpose function key, as index 11.
    F11,
    /// The F12 key, a general purpose function key, as index 12.
    F12,
    /// The F13 key, a general purpose function key, as index 13.
    F13,
    /// The F14 key, a general purpose function key, as index 14.
    F14,
    /// The F15 key, a general purpose function key, as index 15.
    F15,
    /// The F16 key, a general purpose function key, as index 16.
    F16,
    /// The F17 key, a general purpose function key, as index 17.
    F17,
    /// The F18 key, a general purpose function key, as index 18.
    F18,
    /// The F19 key, a general purpose function key, as index 19.
    F19,
    /// The F20 key, a general purpose function key, as index 20.
    F20,
    /// The F21 key, a general purpose function key, as index 21.
    F21,
    /// The F22 key, a general purpose function key, as index 22.
    F22,
    /// The F23 key, a general purpose function key, as index 23.
    F23,
    /// The F24 key, a general purpose function key, as index 24.
    F24,
    /// The F25 key, a general purpose function key, as index 25.
    F25,
    /// The F26 key, a general purpose function key, as index 26.
    F26,
    /// The F27 key, a general purpose function key, as index 27.
    F27,
    /// The F28 key, a general purpose function key, as index 28.
    F28,
    /// The F29 key, a general purpose function key, as index 29.
    F29,
    /// The F30 key, a general purpose function key, as index 30.
    F30,
    /// The F31 key, a general purpose function key, as index 31.
    F31,
    /// The F32 key, a general purpose function key, as index 32.
    F32,
    /// The F33 key, a general purpose function key, as index 33.
    F33,
    /// The F34 key, a general purpose function key, as index 34.
    F34,
    /// The F35 key, a general purpose function key, as index 35.
    F35,
}

impl NamedKey {
    /// Every variant, in the order the specification lists them.
    pub const ALL: &[Self] = &[
        Self::Unidentified,
        Self::Alt,
        Self::AltGraph,
        Self::CapsLock,
        Self::Control,
        Self::Fn,
        Self::FnLock,
        Self::Meta,
        Self::NumLock,
        Self::ScrollLock,
        Self::Shift,
        Self::Symbol,
        Self::SymbolLock,
        Self::Enter,
        Self::Tab,
        Self::ArrowDown,
        Self::ArrowLeft,
        Self::ArrowRight,
        Self::ArrowUp,
        Self::End,
        Self::Home,
        Self::PageDown,
        Self::PageUp,
        Self::Backspace,
        Self::Clear,
        Self::Copy,
        Self::CrSel,
        Self::Cut,
        Self::Delete,
        Self::EraseEof,
        Self::ExSel,
        Self::Insert,
        Self::Paste,
        Self::Redo,
        Self::Undo,
        Self::Accept,
        Self::Again,
        Self::Attn,
        Self::Cancel,
        Self::ContextMenu,
        Self::Escape,
        Self::Execute,
        Self::Find,
        Self::Help,
        Self::Pause,
        Self::Play,
        Self::Props,
        Self::Select,
        Self::ZoomIn,
        Self::ZoomOut,
        Self::BrightnessDown,
        Self::BrightnessUp,
        Self::Eject,
        Self::LogOff,
        Self::Power,
        Self::PowerOff,
        Self::PrintScreen,
        Self::Hibernate,
        Self::Standby,
        Self::WakeUp,
        Self::AllCandidates,
        Self::Alphanumeric,
        Self::CodeInput,
        Self::Compose,
        Self::Convert,
        Self::Dead,
        Self::FinalMode,
        Self::GroupFirst,
        Self::GroupLast,
        Self::GroupNext,
        Self::GroupPrevious,
        Self::ModeChange,
        Self::NextCandidate,
        Self::NonConvert,
        Self::PreviousCandidate,
        Self::Process,
        Self::SingleCandidate,
        Self::HangulMode,
        Self::HanjaMode,
        Self::JunjaMode,
        Self::Eisu,
        Self::Hankaku,
        Self::Hiragana,
        Self::HiraganaKatakana,
        Self::KanaMode,
        Self::KanjiMode,
        Self::Katakana,
        Self::Romaji,
        Self::Zenkaku,
        Self::ZenkakuHankaku,
        Self::Soft1,
        Self::Soft2,
        Self::Soft3,
        Self::Soft4,
        Self::ChannelDown,
        Self::ChannelUp,
        Self::Close,
        Self::MailForward,
        Self::MailReply,
        Self::MailSend,
        Self::MediaClose,
        Self::MediaFastForward,
        Self::MediaPause,
        Self::MediaPlay,
        Self::MediaPlayPause,
        Self::MediaRecord,
        Self::MediaRewind,
        Self::MediaStop,
        Self::MediaTrackNext,
        Self::MediaTrackPrevious,
        Self::New,
        Self::Open,
        Self::Print,
        Self::Save,
        Self::SpellCheck,
        Self::Key11,
        Self::Key12,
        Self::AudioBalanceLeft,
        Self::AudioBalanceRight,
        Self::AudioBassBoostDown,
        Self::AudioBassBoostToggle,
        Self::AudioBassBoostUp,
        Self::AudioFaderFront,
        Self::AudioFaderRear,
        Self::AudioSurroundModeNext,
        Self::AudioTrebleDown,
        Self::AudioTrebleUp,
        Self::AudioVolumeDown,
        Self::AudioVolumeUp,
        Self::AudioVolumeMute,
        Self::MicrophoneToggle,
        Self::MicrophoneVolumeDown,
        Self::MicrophoneVolumeUp,
        Self::MicrophoneVolumeMute,
        Self::SpeechCorrectionList,
        Self::SpeechInputToggle,
        Self::LaunchApplication1,
        Self::LaunchApplication2,
        Self::LaunchCalendar,
        Self::LaunchContacts,
        Self::LaunchMail,
        Self::LaunchMediaPlayer,
        Self::LaunchMusicPlayer,
        Self::LaunchPhone,
        Self::LaunchScreenSaver,
        Self::LaunchSpreadsheet,
        Self::LaunchWebBrowser,
        Self::LaunchWebCam,
        Self::LaunchWordProcessor,
        Self::BrowserBack,
        Self::BrowserFavorites,
        Self::BrowserForward,
        Self::BrowserHome,
        Self::BrowserRefresh,
        Self::BrowserSearch,
        Self::BrowserStop,
        Self::AppSwitch,
        Self::Call,
        Self::Camera,
        Self::CameraFocus,
        Self::EndCall,
        Self::GoBack,
        Self::GoHome,
        Self::HeadsetHook,
        Self::LastNumberRedial,
        Self::Notification,
        Self::MannerMode,
        Self::VoiceDial,
        Self::TV,
        Self::TV3DMode,
        Self::TVAntennaCable,
        Self::TVAudioDescription,
        Self::TVAudioDescriptionMixDown,
        Self::TVAudioDescriptionMixUp,
        Self::TVContentsMenu,
        Self::TVDataService,
        Self::TVInput,
        Self::TVInputComponent1,
        Self::TVInputComponent2,
        Self::TVInputComposite1,
        Self::TVInputComposite2,
        Self::TVInputHDMI1,
        Self::TVInputHDMI2,
        Self::TVInputHDMI3,
        Self::TVInputHDMI4,
        Self::TVInputVGA1,
        Self::TVMediaContext,
        Self::TVNetwork,
        Self::TVNumberEntry,
        Self::TVPower,
        Self::TVRadioService,
        Self::TVSatellite,
        Self::TVSatelliteBS,
        Self::TVSatelliteCS,
        Self::TVSatelliteToggle,
        Self::TVTerrestrialAnalog,
        Self::TVTerrestrialDigital,
        Self::TVTimer,
        Self::AVRInput,
        Self::AVRPower,
        Self::ColorF0Red,
        Self::ColorF1Green,
        Self::ColorF2Yellow,
        Self::ColorF3Blue,
        Self::ColorF4Grey,
        Self::ColorF5Brown,
        Self::ClosedCaptionToggle,
        Self::Dimmer,
        Self::DisplaySwap,
        Self::DVR,
        Self::Exit,
        Self::FavoriteClear0,
        Self::FavoriteClear1,
        Self::FavoriteClear2,
        Self::FavoriteClear3,
        Self::FavoriteRecall0,
        Self::FavoriteRecall1,
        Self::FavoriteRecall2,
        Self::FavoriteRecall3,
        Self::FavoriteStore0,
        Self::FavoriteStore1,
        Self::FavoriteStore2,
        Self::FavoriteStore3,
        Self::Guide,
        Self::GuideNextDay,
        Self::GuidePreviousDay,
        Self::Info,
        Self::InstantReplay,
        Self::Link,
        Self::ListProgram,
        Self::LiveContent,
        Self::Lock,
        Self::MediaApps,
        Self::MediaAudioTrack,
        Self::MediaLast,
        Self::MediaSkipBackward,
        Self::MediaSkipForward,
        Self::MediaStepBackward,
        Self::MediaStepForward,
        Self::MediaTopMenu,
        Self::NavigateIn,
        Self::NavigateNext,
        Self::NavigateOut,
        Self::NavigatePrevious,
        Self::NextFavoriteChannel,
        Self::NextUserProfile,
        Self::OnDemand,
        Self::Pairing,
        Self::PinPDown,
        Self::PinPMove,
        Self::PinPToggle,
        Self::PinPUp,
        Self::PlaySpeedDown,
        Self::PlaySpeedReset,
        Self::PlaySpeedUp,
        Self::RandomToggle,
        Self::RcLowBattery,
        Self::RecordSpeedNext,
        Self::RfBypass,
        Self::ScanChannelsToggle,
        Self::ScreenModeNext,
        Self::Settings,
        Self::SplitScreenToggle,
        Self::STBInput,
        Self::STBPower,
        Self::Subtitle,
        Self::Teletext,
        Self::VideoModeNext,
        Self::Wink,
        Self::ZoomToggle,
        Self::F1,
        Self::F2,
        Self::F3,
        Self::F4,
        Self::F5,
        Self::F6,
        Self::F7,
        Self::F8,
        Self::F9,
        Self::F10,
        Self::F11,
        Self::F12,
        Self::F13,
        Self::F14,
        Self::F15,
        Self::F16,
        Self::F17,
        Self::F18,
        Self::F19,
        Self::F20,
        Self::F21,
        Self::F22,
        Self::F23,
        Self::F24,
        Self::F25,
        Self::F26,
        Self::F27,
        Self::F28,
        Self::F29,
        Self::F30,
        Self::F31,
        Self::F32,
        Self::F33,
        Self::F34,
        Self::F35,
    ];

    /// The W3C spelling of this value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Unidentified => "Unidentified",
            Self::Alt => "Alt",
            Self::AltGraph => "AltGraph",
            Self::CapsLock => "CapsLock",
            Self::Control => "Control",
            Self::Fn => "Fn",
            Self::FnLock => "FnLock",
            Self::Meta => "Meta",
            Self::NumLock => "NumLock",
            Self::ScrollLock => "ScrollLock",
            Self::Shift => "Shift",
            Self::Symbol => "Symbol",
            Self::SymbolLock => "SymbolLock",
            Self::Enter => "Enter",
            Self::Tab => "Tab",
            Self::ArrowDown => "ArrowDown",
            Self::ArrowLeft => "ArrowLeft",
            Self::ArrowRight => "ArrowRight",
            Self::ArrowUp => "ArrowUp",
            Self::End => "End",
            Self::Home => "Home",
            Self::PageDown => "PageDown",
            Self::PageUp => "PageUp",
            Self::Backspace => "Backspace",
            Self::Clear => "Clear",
            Self::Copy => "Copy",
            Self::CrSel => "CrSel",
            Self::Cut => "Cut",
            Self::Delete => "Delete",
            Self::EraseEof => "EraseEof",
            Self::ExSel => "ExSel",
            Self::Insert => "Insert",
            Self::Paste => "Paste",
            Self::Redo => "Redo",
            Self::Undo => "Undo",
            Self::Accept => "Accept",
            Self::Again => "Again",
            Self::Attn => "Attn",
            Self::Cancel => "Cancel",
            Self::ContextMenu => "ContextMenu",
            Self::Escape => "Escape",
            Self::Execute => "Execute",
            Self::Find => "Find",
            Self::Help => "Help",
            Self::Pause => "Pause",
            Self::Play => "Play",
            Self::Props => "Props",
            Self::Select => "Select",
            Self::ZoomIn => "ZoomIn",
            Self::ZoomOut => "ZoomOut",
            Self::BrightnessDown => "BrightnessDown",
            Self::BrightnessUp => "BrightnessUp",
            Self::Eject => "Eject",
            Self::LogOff => "LogOff",
            Self::Power => "Power",
            Self::PowerOff => "PowerOff",
            Self::PrintScreen => "PrintScreen",
            Self::Hibernate => "Hibernate",
            Self::Standby => "Standby",
            Self::WakeUp => "WakeUp",
            Self::AllCandidates => "AllCandidates",
            Self::Alphanumeric => "Alphanumeric",
            Self::CodeInput => "CodeInput",
            Self::Compose => "Compose",
            Self::Convert => "Convert",
            Self::Dead => "Dead",
            Self::FinalMode => "FinalMode",
            Self::GroupFirst => "GroupFirst",
            Self::GroupLast => "GroupLast",
            Self::GroupNext => "GroupNext",
            Self::GroupPrevious => "GroupPrevious",
            Self::ModeChange => "ModeChange",
            Self::NextCandidate => "NextCandidate",
            Self::NonConvert => "NonConvert",
            Self::PreviousCandidate => "PreviousCandidate",
            Self::Process => "Process",
            Self::SingleCandidate => "SingleCandidate",
            Self::HangulMode => "HangulMode",
            Self::HanjaMode => "HanjaMode",
            Self::JunjaMode => "JunjaMode",
            Self::Eisu => "Eisu",
            Self::Hankaku => "Hankaku",
            Self::Hiragana => "Hiragana",
            Self::HiraganaKatakana => "HiraganaKatakana",
            Self::KanaMode => "KanaMode",
            Self::KanjiMode => "KanjiMode",
            Self::Katakana => "Katakana",
            Self::Romaji => "Romaji",
            Self::Zenkaku => "Zenkaku",
            Self::ZenkakuHankaku => "ZenkakuHankaku",
            Self::Soft1 => "Soft1",
            Self::Soft2 => "Soft2",
            Self::Soft3 => "Soft3",
            Self::Soft4 => "Soft4",
            Self::ChannelDown => "ChannelDown",
            Self::ChannelUp => "ChannelUp",
            Self::Close => "Close",
            Self::MailForward => "MailForward",
            Self::MailReply => "MailReply",
            Self::MailSend => "MailSend",
            Self::MediaClose => "MediaClose",
            Self::MediaFastForward => "MediaFastForward",
            Self::MediaPause => "MediaPause",
            Self::MediaPlay => "MediaPlay",
            Self::MediaPlayPause => "MediaPlayPause",
            Self::MediaRecord => "MediaRecord",
            Self::MediaRewind => "MediaRewind",
            Self::MediaStop => "MediaStop",
            Self::MediaTrackNext => "MediaTrackNext",
            Self::MediaTrackPrevious => "MediaTrackPrevious",
            Self::New => "New",
            Self::Open => "Open",
            Self::Print => "Print",
            Self::Save => "Save",
            Self::SpellCheck => "SpellCheck",
            Self::Key11 => "Key11",
            Self::Key12 => "Key12",
            Self::AudioBalanceLeft => "AudioBalanceLeft",
            Self::AudioBalanceRight => "AudioBalanceRight",
            Self::AudioBassBoostDown => "AudioBassBoostDown",
            Self::AudioBassBoostToggle => "AudioBassBoostToggle",
            Self::AudioBassBoostUp => "AudioBassBoostUp",
            Self::AudioFaderFront => "AudioFaderFront",
            Self::AudioFaderRear => "AudioFaderRear",
            Self::AudioSurroundModeNext => "AudioSurroundModeNext",
            Self::AudioTrebleDown => "AudioTrebleDown",
            Self::AudioTrebleUp => "AudioTrebleUp",
            Self::AudioVolumeDown => "AudioVolumeDown",
            Self::AudioVolumeUp => "AudioVolumeUp",
            Self::AudioVolumeMute => "AudioVolumeMute",
            Self::MicrophoneToggle => "MicrophoneToggle",
            Self::MicrophoneVolumeDown => "MicrophoneVolumeDown",
            Self::MicrophoneVolumeUp => "MicrophoneVolumeUp",
            Self::MicrophoneVolumeMute => "MicrophoneVolumeMute",
            Self::SpeechCorrectionList => "SpeechCorrectionList",
            Self::SpeechInputToggle => "SpeechInputToggle",
            Self::LaunchApplication1 => "LaunchApplication1",
            Self::LaunchApplication2 => "LaunchApplication2",
            Self::LaunchCalendar => "LaunchCalendar",
            Self::LaunchContacts => "LaunchContacts",
            Self::LaunchMail => "LaunchMail",
            Self::LaunchMediaPlayer => "LaunchMediaPlayer",
            Self::LaunchMusicPlayer => "LaunchMusicPlayer",
            Self::LaunchPhone => "LaunchPhone",
            Self::LaunchScreenSaver => "LaunchScreenSaver",
            Self::LaunchSpreadsheet => "LaunchSpreadsheet",
            Self::LaunchWebBrowser => "LaunchWebBrowser",
            Self::LaunchWebCam => "LaunchWebCam",
            Self::LaunchWordProcessor => "LaunchWordProcessor",
            Self::BrowserBack => "BrowserBack",
            Self::BrowserFavorites => "BrowserFavorites",
            Self::BrowserForward => "BrowserForward",
            Self::BrowserHome => "BrowserHome",
            Self::BrowserRefresh => "BrowserRefresh",
            Self::BrowserSearch => "BrowserSearch",
            Self::BrowserStop => "BrowserStop",
            Self::AppSwitch => "AppSwitch",
            Self::Call => "Call",
            Self::Camera => "Camera",
            Self::CameraFocus => "CameraFocus",
            Self::EndCall => "EndCall",
            Self::GoBack => "GoBack",
            Self::GoHome => "GoHome",
            Self::HeadsetHook => "HeadsetHook",
            Self::LastNumberRedial => "LastNumberRedial",
            Self::Notification => "Notification",
            Self::MannerMode => "MannerMode",
            Self::VoiceDial => "VoiceDial",
            Self::TV => "TV",
            Self::TV3DMode => "TV3DMode",
            Self::TVAntennaCable => "TVAntennaCable",
            Self::TVAudioDescription => "TVAudioDescription",
            Self::TVAudioDescriptionMixDown => "TVAudioDescriptionMixDown",
            Self::TVAudioDescriptionMixUp => "TVAudioDescriptionMixUp",
            Self::TVContentsMenu => "TVContentsMenu",
            Self::TVDataService => "TVDataService",
            Self::TVInput => "TVInput",
            Self::TVInputComponent1 => "TVInputComponent1",
            Self::TVInputComponent2 => "TVInputComponent2",
            Self::TVInputComposite1 => "TVInputComposite1",
            Self::TVInputComposite2 => "TVInputComposite2",
            Self::TVInputHDMI1 => "TVInputHDMI1",
            Self::TVInputHDMI2 => "TVInputHDMI2",
            Self::TVInputHDMI3 => "TVInputHDMI3",
            Self::TVInputHDMI4 => "TVInputHDMI4",
            Self::TVInputVGA1 => "TVInputVGA1",
            Self::TVMediaContext => "TVMediaContext",
            Self::TVNetwork => "TVNetwork",
            Self::TVNumberEntry => "TVNumberEntry",
            Self::TVPower => "TVPower",
            Self::TVRadioService => "TVRadioService",
            Self::TVSatellite => "TVSatellite",
            Self::TVSatelliteBS => "TVSatelliteBS",
            Self::TVSatelliteCS => "TVSatelliteCS",
            Self::TVSatelliteToggle => "TVSatelliteToggle",
            Self::TVTerrestrialAnalog => "TVTerrestrialAnalog",
            Self::TVTerrestrialDigital => "TVTerrestrialDigital",
            Self::TVTimer => "TVTimer",
            Self::AVRInput => "AVRInput",
            Self::AVRPower => "AVRPower",
            Self::ColorF0Red => "ColorF0Red",
            Self::ColorF1Green => "ColorF1Green",
            Self::ColorF2Yellow => "ColorF2Yellow",
            Self::ColorF3Blue => "ColorF3Blue",
            Self::ColorF4Grey => "ColorF4Grey",
            Self::ColorF5Brown => "ColorF5Brown",
            Self::ClosedCaptionToggle => "ClosedCaptionToggle",
            Self::Dimmer => "Dimmer",
            Self::DisplaySwap => "DisplaySwap",
            Self::DVR => "DVR",
            Self::Exit => "Exit",
            Self::FavoriteClear0 => "FavoriteClear0",
            Self::FavoriteClear1 => "FavoriteClear1",
            Self::FavoriteClear2 => "FavoriteClear2",
            Self::FavoriteClear3 => "FavoriteClear3",
            Self::FavoriteRecall0 => "FavoriteRecall0",
            Self::FavoriteRecall1 => "FavoriteRecall1",
            Self::FavoriteRecall2 => "FavoriteRecall2",
            Self::FavoriteRecall3 => "FavoriteRecall3",
            Self::FavoriteStore0 => "FavoriteStore0",
            Self::FavoriteStore1 => "FavoriteStore1",
            Self::FavoriteStore2 => "FavoriteStore2",
            Self::FavoriteStore3 => "FavoriteStore3",
            Self::Guide => "Guide",
            Self::GuideNextDay => "GuideNextDay",
            Self::GuidePreviousDay => "GuidePreviousDay",
            Self::Info => "Info",
            Self::InstantReplay => "InstantReplay",
            Self::Link => "Link",
            Self::ListProgram => "ListProgram",
            Self::LiveContent => "LiveContent",
            Self::Lock => "Lock",
            Self::MediaApps => "MediaApps",
            Self::MediaAudioTrack => "MediaAudioTrack",
            Self::MediaLast => "MediaLast",
            Self::MediaSkipBackward => "MediaSkipBackward",
            Self::MediaSkipForward => "MediaSkipForward",
            Self::MediaStepBackward => "MediaStepBackward",
            Self::MediaStepForward => "MediaStepForward",
            Self::MediaTopMenu => "MediaTopMenu",
            Self::NavigateIn => "NavigateIn",
            Self::NavigateNext => "NavigateNext",
            Self::NavigateOut => "NavigateOut",
            Self::NavigatePrevious => "NavigatePrevious",
            Self::NextFavoriteChannel => "NextFavoriteChannel",
            Self::NextUserProfile => "NextUserProfile",
            Self::OnDemand => "OnDemand",
            Self::Pairing => "Pairing",
            Self::PinPDown => "PinPDown",
            Self::PinPMove => "PinPMove",
            Self::PinPToggle => "PinPToggle",
            Self::PinPUp => "PinPUp",
            Self::PlaySpeedDown => "PlaySpeedDown",
            Self::PlaySpeedReset => "PlaySpeedReset",
            Self::PlaySpeedUp => "PlaySpeedUp",
            Self::RandomToggle => "RandomToggle",
            Self::RcLowBattery => "RcLowBattery",
            Self::RecordSpeedNext => "RecordSpeedNext",
            Self::RfBypass => "RfBypass",
            Self::ScanChannelsToggle => "ScanChannelsToggle",
            Self::ScreenModeNext => "ScreenModeNext",
            Self::Settings => "Settings",
            Self::SplitScreenToggle => "SplitScreenToggle",
            Self::STBInput => "STBInput",
            Self::STBPower => "STBPower",
            Self::Subtitle => "Subtitle",
            Self::Teletext => "Teletext",
            Self::VideoModeNext => "VideoModeNext",
            Self::Wink => "Wink",
            Self::ZoomToggle => "ZoomToggle",
            Self::F1 => "F1",
            Self::F2 => "F2",
            Self::F3 => "F3",
            Self::F4 => "F4",
            Self::F5 => "F5",
            Self::F6 => "F6",
            Self::F7 => "F7",
            Self::F8 => "F8",
            Self::F9 => "F9",
            Self::F10 => "F10",
            Self::F11 => "F11",
            Self::F12 => "F12",
            Self::F13 => "F13",
            Self::F14 => "F14",
            Self::F15 => "F15",
            Self::F16 => "F16",
            Self::F17 => "F17",
            Self::F18 => "F18",
            Self::F19 => "F19",
            Self::F20 => "F20",
            Self::F21 => "F21",
            Self::F22 => "F22",
            Self::F23 => "F23",
            Self::F24 => "F24",
            Self::F25 => "F25",
            Self::F26 => "F26",
            Self::F27 => "F27",
            Self::F28 => "F28",
            Self::F29 => "F29",
            Self::F30 => "F30",
            Self::F31 => "F31",
            Self::F32 => "F32",
            Self::F33 => "F33",
            Self::F34 => "F34",
            Self::F35 => "F35",
        }
    }

    /// The value the W3C spells `name`, or `None` for a spelling this table does not list.
    #[must_use]
    pub fn from_w3c(name: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|value| value.as_str() == name)
    }
}

impl core::fmt::Display for NamedKey {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}
