//! Pipeline for the separable morphology filter pass.
//!
//! [`MorphologyPipeline`] owns the `wgpu::RenderPipeline` used by
//! [`super::apply_morphology`].  It is format-parametric so the same pipeline
//! serves both the windowed surface format and any pooled offscreen target format.
//!
//! ## Bind-group layout (group 0)
//!
//! Generated by `wgsl_bindgen` from `morphology.wgsl` — see `super::generated`.
//! The layout is auto-verified at build time against the WGSL struct definition.
//!
//! | Binding | Stage  | Type                  | Content                          |
//! |---------|--------|-----------------------|----------------------------------|
//! | 0       | VS+FS  | Uniform buffer        | `MorphUniforms` (48 bytes)       |
//! | 1       | VS+FS  | 2D float texture      | Source (premultiplied RGBA)      |
//! | 2       | VS+FS  | Non-filtering sampler | Nearest + ClampToEdge            |
//!
//! ## Uniform layout
//!
//! `MorphUniforms` (generated) matches `MorphUniforms` in `morphology.wgsl`:
//!
//! | Byte offset | Size | Field              | WGSL member    |
//! |-------------|------|--------------------|----------------|
//! | 0           | 8    | `texture_size`     | `vec2<f32>`    |
//! | 8           | 4    | `radius`           | `f32`          |
//! | 12          | 4    | `direction`        | `f32`          |
//! | 16          | 16   | `content_rect_uv`  | `vec4<f32>`    |
//! | 32          | 4    | `op`               | `f32`          |
//! | 36          | 12   | `_pad0/1/2`        | `[u8; 4] × 3` |
//!
//! Total = 48 bytes (multiple of 16 ✓).

use super::generated::morphology;

// ── Byte-identity gate ────────────────────────────────────────────────────────
//
// These const assertions are the layout gate.  If wgsl_bindgen generates a
// struct whose layout differs from the hand-written `MorphUniform`, this file
// will fail to compile — the layout drift must be fixed, not suppressed.

/// The generated `MorphUniforms` must be exactly 48 bytes — matching the WGSL
/// `MorphUniforms` struct and the former hand-written `MorphUniform`.
const _GENERATED_MORPH_UNIFORMS_SIZE_CHECK: () = {
    assert!(std::mem::size_of::<morphology::MorphUniforms>() == 48);
};

/// `texture_size` must be at byte offset 0.
const _GENERATED_MORPH_TEXTURE_SIZE_OFFSET_CHECK: () = {
    assert!(std::mem::offset_of!(morphology::MorphUniforms, texture_size) == 0);
};

/// `radius` must be at byte offset 8.
const _GENERATED_MORPH_RADIUS_OFFSET_CHECK: () = {
    assert!(std::mem::offset_of!(morphology::MorphUniforms, radius) == 8);
};

/// `direction` must be at byte offset 12.
const _GENERATED_MORPH_DIRECTION_OFFSET_CHECK: () = {
    assert!(std::mem::offset_of!(morphology::MorphUniforms, direction) == 12);
};

/// `content_rect_uv` must be at byte offset 16.
const _GENERATED_MORPH_CONTENT_RECT_UV_OFFSET_CHECK: () = {
    assert!(std::mem::offset_of!(morphology::MorphUniforms, content_rect_uv) == 16);
};

/// `op` must be at byte offset 32.
const _GENERATED_MORPH_OP_OFFSET_CHECK: () = {
    assert!(std::mem::offset_of!(morphology::MorphUniforms, op) == 32);
};

// ── Pipeline ──────────────────────────────────────────────────────────────────

/// Render pipeline for the morphology filter pass.
///
/// The bind-group layout is created from the generated `morphology::WgpuBindGroup0`
/// and is not stored here — callers use `morphology::WgpuBindGroup0::from_bindings`
/// at draw time, which creates a compatible bind group internally.
///
/// ## Blend state
///
/// `REPLACE` (no fixed-function blending): the fragment shader emits the full
/// premultiplied result directly.
pub(crate) struct MorphologyPipeline {
    /// The single render pipeline (format-parametric at construction time).
    pub(crate) pipeline: wgpu::RenderPipeline,
}

impl MorphologyPipeline {
    /// Build the pipeline for `surface_format`.
    ///
    /// WGSL shader compilation happens here; a wgpu validation error surfaces
    /// at this call site, which the GPU construction test exercises.
    pub(crate) fn new(device: &wgpu::Device, surface_format: wgpu::TextureFormat) -> Self {
        // The bind-group layout is sourced from the generated bindings, which derive
        // it directly from the WGSL source — no hand-maintained descriptor.
        let bind_group_layout = morphology::WgpuBindGroup0::get_bind_group_layout(device);
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Morphology Pipeline Layout"),
            bind_group_layouts: &[Some(&bind_group_layout)],
            immediate_size: 0,
        });

        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Morphology Shader"),
            source: wgpu::ShaderSource::Wgsl(
                include_str!("../shaders/effects/morphology.wgsl").into(),
            ),
        });

        let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("Morphology Pipeline"),
            layout: Some(&pipeline_layout),
            vertex: wgpu::VertexState {
                module: &shader,
                entry_point: Some("vs_main"),
                // No vertex buffers: the VS synthesises 6 vertices from
                // `@builtin(vertex_index)`, forming a full-viewport quad.
                buffers: &[],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &shader,
                entry_point: Some("fs_main"),
                targets: &[Some(wgpu::ColorTargetState {
                    format: surface_format,
                    // REPLACE: the shader emits the full premultiplied result.
                    blend: Some(wgpu::BlendState::REPLACE),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
                compilation_options: wgpu::PipelineCompilationOptions::default(),
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                strip_index_format: None,
                front_face: wgpu::FrontFace::Ccw,
                cull_mode: None,
                polygon_mode: wgpu::PolygonMode::Fill,
                unclipped_depth: false,
                conservative: false,
            },
            depth_stencil: None,
            multisample: wgpu::MultisampleState {
                count: 1,
                mask: !0,
                alpha_to_coverage_enabled: false,
            },
            multiview_mask: None,
            cache: None,
        });

        Self { pipeline }
    }
}
