//! cosmic-text 0.19's `PlatformFallback` lists for every platform, recorded
//! from its `font/fallback/{windows,unix,macos,other}.rs` before it left the
//! workspace (ADR-0092 §10 step 6): the common list, then for each locale
//! every script with a list of its own, keyed by ISO 15924 code. A script
//! not named has no list.

/// One platform's lists: its name, its common list, and per locale the
/// script lists.
pub(super) type Recorded = (
    &'static str,
    &'static [&'static str],
    &'static [(
        &'static str,
        &'static [(&'static str, &'static [&'static str])],
    )],
);

pub(super) const RECORDED: [Recorded; 4] = [
    (
        "windows",
        &[
            "Segoe UI",
            "Segoe UI Emoji",
            "Segoe UI Symbol",
            "Segoe UI Historic",
        ],
        &[
            (
                "ja",
                &[
                    ("Adlm", &["Ebrima"]),
                    ("Beng", &["Nirmala UI"]),
                    ("Cakm", &["Nirmala UI"]),
                    ("Cans", &["Gadugi"]),
                    ("Cher", &["Gadugi"]),
                    ("Deva", &["Nirmala UI"]),
                    ("Ethi", &["Ebrima"]),
                    ("Gujr", &["Nirmala UI"]),
                    ("Guru", &["Nirmala UI"]),
                    ("Hang", &["Malgun Gothic"]),
                    ("Hani", &["Yu Gothic"]),
                    ("Hira", &["Yu Gothic"]),
                    ("Java", &["Javanese Text"]),
                    ("Kana", &["Yu Gothic"]),
                    ("Khmr", &["Leelawadee UI"]),
                    ("Knda", &["Nirmala UI"]),
                    ("Laoo", &["Leelawadee UI"]),
                    ("Mlym", &["Nirmala UI"]),
                    ("Mong", &["Mongolian Baiti"]),
                    ("Mymr", &["Myanmar Text"]),
                    ("Orya", &["Nirmala UI"]),
                    ("Sinh", &["Nirmala UI"]),
                    ("Taml", &["Nirmala UI"]),
                    ("Telu", &["Nirmala UI"]),
                    ("Tfng", &["Ebrima"]),
                    ("Thaa", &["MV Boli"]),
                    ("Thai", &["Leelawadee UI"]),
                    ("Tibt", &["Microsoft Himalaya"]),
                    ("Vaii", &["Ebrima"]),
                    ("Yiii", &["Microsoft Yi Baiti"]),
                ],
            ),
            (
                "ko",
                &[
                    ("Adlm", &["Ebrima"]),
                    ("Beng", &["Nirmala UI"]),
                    ("Cakm", &["Nirmala UI"]),
                    ("Cans", &["Gadugi"]),
                    ("Cher", &["Gadugi"]),
                    ("Deva", &["Nirmala UI"]),
                    ("Ethi", &["Ebrima"]),
                    ("Gujr", &["Nirmala UI"]),
                    ("Guru", &["Nirmala UI"]),
                    ("Hang", &["Malgun Gothic"]),
                    ("Hani", &["Malgun Gothic"]),
                    ("Hira", &["Yu Gothic"]),
                    ("Java", &["Javanese Text"]),
                    ("Kana", &["Yu Gothic"]),
                    ("Khmr", &["Leelawadee UI"]),
                    ("Knda", &["Nirmala UI"]),
                    ("Laoo", &["Leelawadee UI"]),
                    ("Mlym", &["Nirmala UI"]),
                    ("Mong", &["Mongolian Baiti"]),
                    ("Mymr", &["Myanmar Text"]),
                    ("Orya", &["Nirmala UI"]),
                    ("Sinh", &["Nirmala UI"]),
                    ("Taml", &["Nirmala UI"]),
                    ("Telu", &["Nirmala UI"]),
                    ("Tfng", &["Ebrima"]),
                    ("Thaa", &["MV Boli"]),
                    ("Thai", &["Leelawadee UI"]),
                    ("Tibt", &["Microsoft Himalaya"]),
                    ("Vaii", &["Ebrima"]),
                    ("Yiii", &["Microsoft Yi Baiti"]),
                ],
            ),
            (
                "zh-HK",
                &[
                    ("Adlm", &["Ebrima"]),
                    ("Beng", &["Nirmala UI"]),
                    ("Cakm", &["Nirmala UI"]),
                    ("Cans", &["Gadugi"]),
                    ("Cher", &["Gadugi"]),
                    ("Deva", &["Nirmala UI"]),
                    ("Ethi", &["Ebrima"]),
                    ("Gujr", &["Nirmala UI"]),
                    ("Guru", &["Nirmala UI"]),
                    ("Hang", &["Malgun Gothic"]),
                    ("Hani", &["MingLiU_HKSCS"]),
                    ("Hira", &["Yu Gothic"]),
                    ("Java", &["Javanese Text"]),
                    ("Kana", &["Yu Gothic"]),
                    ("Khmr", &["Leelawadee UI"]),
                    ("Knda", &["Nirmala UI"]),
                    ("Laoo", &["Leelawadee UI"]),
                    ("Mlym", &["Nirmala UI"]),
                    ("Mong", &["Mongolian Baiti"]),
                    ("Mymr", &["Myanmar Text"]),
                    ("Orya", &["Nirmala UI"]),
                    ("Sinh", &["Nirmala UI"]),
                    ("Taml", &["Nirmala UI"]),
                    ("Telu", &["Nirmala UI"]),
                    ("Tfng", &["Ebrima"]),
                    ("Thaa", &["MV Boli"]),
                    ("Thai", &["Leelawadee UI"]),
                    ("Tibt", &["Microsoft Himalaya"]),
                    ("Vaii", &["Ebrima"]),
                    ("Yiii", &["Microsoft Yi Baiti"]),
                ],
            ),
            (
                "zh-TW",
                &[
                    ("Adlm", &["Ebrima"]),
                    ("Beng", &["Nirmala UI"]),
                    ("Cakm", &["Nirmala UI"]),
                    ("Cans", &["Gadugi"]),
                    ("Cher", &["Gadugi"]),
                    ("Deva", &["Nirmala UI"]),
                    ("Ethi", &["Ebrima"]),
                    ("Gujr", &["Nirmala UI"]),
                    ("Guru", &["Nirmala UI"]),
                    ("Hang", &["Malgun Gothic"]),
                    ("Hani", &["Microsoft JhengHei UI"]),
                    ("Hira", &["Yu Gothic"]),
                    ("Java", &["Javanese Text"]),
                    ("Kana", &["Yu Gothic"]),
                    ("Khmr", &["Leelawadee UI"]),
                    ("Knda", &["Nirmala UI"]),
                    ("Laoo", &["Leelawadee UI"]),
                    ("Mlym", &["Nirmala UI"]),
                    ("Mong", &["Mongolian Baiti"]),
                    ("Mymr", &["Myanmar Text"]),
                    ("Orya", &["Nirmala UI"]),
                    ("Sinh", &["Nirmala UI"]),
                    ("Taml", &["Nirmala UI"]),
                    ("Telu", &["Nirmala UI"]),
                    ("Tfng", &["Ebrima"]),
                    ("Thaa", &["MV Boli"]),
                    ("Thai", &["Leelawadee UI"]),
                    ("Tibt", &["Microsoft Himalaya"]),
                    ("Vaii", &["Ebrima"]),
                    ("Yiii", &["Microsoft Yi Baiti"]),
                ],
            ),
            (
                "en-US",
                &[
                    ("Adlm", &["Ebrima"]),
                    ("Beng", &["Nirmala UI"]),
                    ("Cakm", &["Nirmala UI"]),
                    ("Cans", &["Gadugi"]),
                    ("Cher", &["Gadugi"]),
                    ("Deva", &["Nirmala UI"]),
                    ("Ethi", &["Ebrima"]),
                    ("Gujr", &["Nirmala UI"]),
                    ("Guru", &["Nirmala UI"]),
                    ("Hang", &["Malgun Gothic"]),
                    ("Hani", &["Microsoft YaHei UI"]),
                    ("Hira", &["Yu Gothic"]),
                    ("Java", &["Javanese Text"]),
                    ("Kana", &["Yu Gothic"]),
                    ("Khmr", &["Leelawadee UI"]),
                    ("Knda", &["Nirmala UI"]),
                    ("Laoo", &["Leelawadee UI"]),
                    ("Mlym", &["Nirmala UI"]),
                    ("Mong", &["Mongolian Baiti"]),
                    ("Mymr", &["Myanmar Text"]),
                    ("Orya", &["Nirmala UI"]),
                    ("Sinh", &["Nirmala UI"]),
                    ("Taml", &["Nirmala UI"]),
                    ("Telu", &["Nirmala UI"]),
                    ("Tfng", &["Ebrima"]),
                    ("Thaa", &["MV Boli"]),
                    ("Thai", &["Leelawadee UI"]),
                    ("Tibt", &["Microsoft Himalaya"]),
                    ("Vaii", &["Ebrima"]),
                    ("Yiii", &["Microsoft Yi Baiti"]),
                ],
            ),
            (
                "ja-JP",
                &[
                    ("Adlm", &["Ebrima"]),
                    ("Beng", &["Nirmala UI"]),
                    ("Cakm", &["Nirmala UI"]),
                    ("Cans", &["Gadugi"]),
                    ("Cher", &["Gadugi"]),
                    ("Deva", &["Nirmala UI"]),
                    ("Ethi", &["Ebrima"]),
                    ("Gujr", &["Nirmala UI"]),
                    ("Guru", &["Nirmala UI"]),
                    ("Hang", &["Malgun Gothic"]),
                    ("Hani", &["Microsoft YaHei UI"]),
                    ("Hira", &["Yu Gothic"]),
                    ("Java", &["Javanese Text"]),
                    ("Kana", &["Yu Gothic"]),
                    ("Khmr", &["Leelawadee UI"]),
                    ("Knda", &["Nirmala UI"]),
                    ("Laoo", &["Leelawadee UI"]),
                    ("Mlym", &["Nirmala UI"]),
                    ("Mong", &["Mongolian Baiti"]),
                    ("Mymr", &["Myanmar Text"]),
                    ("Orya", &["Nirmala UI"]),
                    ("Sinh", &["Nirmala UI"]),
                    ("Taml", &["Nirmala UI"]),
                    ("Telu", &["Nirmala UI"]),
                    ("Tfng", &["Ebrima"]),
                    ("Thaa", &["MV Boli"]),
                    ("Thai", &["Leelawadee UI"]),
                    ("Tibt", &["Microsoft Himalaya"]),
                    ("Vaii", &["Ebrima"]),
                    ("Yiii", &["Microsoft Yi Baiti"]),
                ],
            ),
        ],
    ),
    (
        "unix",
        &[
            "Noto Sans",
            "DejaVu Sans",
            "FreeSans",
            "Noto Sans Mono",
            "DejaVu Sans Mono",
            "FreeMono",
            "Noto Sans Symbols",
            "Noto Sans Symbols2",
            "Noto Color Emoji",
        ],
        &[
            (
                "ja",
                &[
                    ("Adlm", &["Noto Sans Adlam", "Noto Sans Adlam Unjoined"]),
                    ("Arab", &["Noto Sans Arabic"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Noto Sans Bengali"]),
                    ("Bopo", &["Noto Sans CJK JP"]),
                    ("Brai", &["FreeMono"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cher", &["Noto Sans Cherokee"]),
                    ("Deva", &["Noto Sans Devanagari"]),
                    ("Dsrt", &["Noto Sans Deseret"]),
                    ("Ethi", &["Noto Sans Ethiopic"]),
                    ("Geor", &["Noto Sans Georgian"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Noto Sans Grantha"]),
                    ("Gujr", &["Noto Sans Gujarati"]),
                    ("Guru", &["Noto Sans Gurmukhi"]),
                    ("Hang", &["Noto Sans CJK KR"]),
                    ("Hani", &["Noto Sans CJK JP"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Noto Sans Hebrew"]),
                    ("Hira", &["Noto Sans CJK JP"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Noto Sans CJK JP"]),
                    ("Khmr", &["Noto Sans Khmer"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Noto Sans Lao"]),
                    ("Mlym", &["Noto Sans Malayalam"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Runr", &["Noto Sans Runic"]),
                    ("Sinh", &["Noto Sans Sinhala"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["Noto Sans Tamil"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Noto Sans Telugu"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Noto Sans Thai"]),
                    ("Tibt", &["Noto Serif Tibetan"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "Noto Sans CJK SC"]),
                ],
            ),
            (
                "ko",
                &[
                    ("Adlm", &["Noto Sans Adlam", "Noto Sans Adlam Unjoined"]),
                    ("Arab", &["Noto Sans Arabic"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Noto Sans Bengali"]),
                    ("Bopo", &["Noto Sans CJK KR"]),
                    ("Brai", &["FreeMono"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cher", &["Noto Sans Cherokee"]),
                    ("Deva", &["Noto Sans Devanagari"]),
                    ("Dsrt", &["Noto Sans Deseret"]),
                    ("Ethi", &["Noto Sans Ethiopic"]),
                    ("Geor", &["Noto Sans Georgian"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Noto Sans Grantha"]),
                    ("Gujr", &["Noto Sans Gujarati"]),
                    ("Guru", &["Noto Sans Gurmukhi"]),
                    ("Hang", &["Noto Sans CJK KR"]),
                    ("Hani", &["Noto Sans CJK KR"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Noto Sans Hebrew"]),
                    ("Hira", &["Noto Sans CJK JP"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Noto Sans CJK JP"]),
                    ("Khmr", &["Noto Sans Khmer"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Noto Sans Lao"]),
                    ("Mlym", &["Noto Sans Malayalam"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Runr", &["Noto Sans Runic"]),
                    ("Sinh", &["Noto Sans Sinhala"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["Noto Sans Tamil"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Noto Sans Telugu"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Noto Sans Thai"]),
                    ("Tibt", &["Noto Serif Tibetan"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "Noto Sans CJK SC"]),
                ],
            ),
            (
                "zh-HK",
                &[
                    ("Adlm", &["Noto Sans Adlam", "Noto Sans Adlam Unjoined"]),
                    ("Arab", &["Noto Sans Arabic"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Noto Sans Bengali"]),
                    ("Bopo", &["Noto Sans CJK HK"]),
                    ("Brai", &["FreeMono"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cher", &["Noto Sans Cherokee"]),
                    ("Deva", &["Noto Sans Devanagari"]),
                    ("Dsrt", &["Noto Sans Deseret"]),
                    ("Ethi", &["Noto Sans Ethiopic"]),
                    ("Geor", &["Noto Sans Georgian"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Noto Sans Grantha"]),
                    ("Gujr", &["Noto Sans Gujarati"]),
                    ("Guru", &["Noto Sans Gurmukhi"]),
                    ("Hang", &["Noto Sans CJK KR"]),
                    ("Hani", &["Noto Sans CJK HK"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Noto Sans Hebrew"]),
                    ("Hira", &["Noto Sans CJK JP"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Noto Sans CJK JP"]),
                    ("Khmr", &["Noto Sans Khmer"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Noto Sans Lao"]),
                    ("Mlym", &["Noto Sans Malayalam"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Runr", &["Noto Sans Runic"]),
                    ("Sinh", &["Noto Sans Sinhala"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["Noto Sans Tamil"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Noto Sans Telugu"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Noto Sans Thai"]),
                    ("Tibt", &["Noto Serif Tibetan"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "Noto Sans CJK SC"]),
                ],
            ),
            (
                "zh-TW",
                &[
                    ("Adlm", &["Noto Sans Adlam", "Noto Sans Adlam Unjoined"]),
                    ("Arab", &["Noto Sans Arabic"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Noto Sans Bengali"]),
                    ("Bopo", &["Noto Sans CJK TC"]),
                    ("Brai", &["FreeMono"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cher", &["Noto Sans Cherokee"]),
                    ("Deva", &["Noto Sans Devanagari"]),
                    ("Dsrt", &["Noto Sans Deseret"]),
                    ("Ethi", &["Noto Sans Ethiopic"]),
                    ("Geor", &["Noto Sans Georgian"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Noto Sans Grantha"]),
                    ("Gujr", &["Noto Sans Gujarati"]),
                    ("Guru", &["Noto Sans Gurmukhi"]),
                    ("Hang", &["Noto Sans CJK KR"]),
                    ("Hani", &["Noto Sans CJK TC"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Noto Sans Hebrew"]),
                    ("Hira", &["Noto Sans CJK JP"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Noto Sans CJK JP"]),
                    ("Khmr", &["Noto Sans Khmer"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Noto Sans Lao"]),
                    ("Mlym", &["Noto Sans Malayalam"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Runr", &["Noto Sans Runic"]),
                    ("Sinh", &["Noto Sans Sinhala"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["Noto Sans Tamil"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Noto Sans Telugu"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Noto Sans Thai"]),
                    ("Tibt", &["Noto Serif Tibetan"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "Noto Sans CJK SC"]),
                ],
            ),
            (
                "en-US",
                &[
                    ("Adlm", &["Noto Sans Adlam", "Noto Sans Adlam Unjoined"]),
                    ("Arab", &["Noto Sans Arabic"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Noto Sans Bengali"]),
                    ("Bopo", &["Noto Sans CJK SC"]),
                    ("Brai", &["FreeMono"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cher", &["Noto Sans Cherokee"]),
                    ("Deva", &["Noto Sans Devanagari"]),
                    ("Dsrt", &["Noto Sans Deseret"]),
                    ("Ethi", &["Noto Sans Ethiopic"]),
                    ("Geor", &["Noto Sans Georgian"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Noto Sans Grantha"]),
                    ("Gujr", &["Noto Sans Gujarati"]),
                    ("Guru", &["Noto Sans Gurmukhi"]),
                    ("Hang", &["Noto Sans CJK KR"]),
                    ("Hani", &["Noto Sans CJK SC"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Noto Sans Hebrew"]),
                    ("Hira", &["Noto Sans CJK JP"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Noto Sans CJK JP"]),
                    ("Khmr", &["Noto Sans Khmer"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Noto Sans Lao"]),
                    ("Mlym", &["Noto Sans Malayalam"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Runr", &["Noto Sans Runic"]),
                    ("Sinh", &["Noto Sans Sinhala"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["Noto Sans Tamil"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Noto Sans Telugu"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Noto Sans Thai"]),
                    ("Tibt", &["Noto Serif Tibetan"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "Noto Sans CJK SC"]),
                ],
            ),
            (
                "ja-JP",
                &[
                    ("Adlm", &["Noto Sans Adlam", "Noto Sans Adlam Unjoined"]),
                    ("Arab", &["Noto Sans Arabic"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Noto Sans Bengali"]),
                    ("Bopo", &["Noto Sans CJK SC"]),
                    ("Brai", &["FreeMono"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cher", &["Noto Sans Cherokee"]),
                    ("Deva", &["Noto Sans Devanagari"]),
                    ("Dsrt", &["Noto Sans Deseret"]),
                    ("Ethi", &["Noto Sans Ethiopic"]),
                    ("Geor", &["Noto Sans Georgian"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Noto Sans Grantha"]),
                    ("Gujr", &["Noto Sans Gujarati"]),
                    ("Guru", &["Noto Sans Gurmukhi"]),
                    ("Hang", &["Noto Sans CJK KR"]),
                    ("Hani", &["Noto Sans CJK SC"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Noto Sans Hebrew"]),
                    ("Hira", &["Noto Sans CJK JP"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Noto Sans CJK JP"]),
                    ("Khmr", &["Noto Sans Khmer"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Noto Sans Lao"]),
                    ("Mlym", &["Noto Sans Malayalam"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Runr", &["Noto Sans Runic"]),
                    ("Sinh", &["Noto Sans Sinhala"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["Noto Sans Tamil"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Noto Sans Telugu"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Noto Sans Thai"]),
                    ("Tibt", &["Noto Serif Tibetan"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "Noto Sans CJK SC"]),
                ],
            ),
        ],
    ),
    (
        "macos",
        &[
            ".SF NS",
            "Menlo",
            "Apple Color Emoji",
            "Geneva",
            "Arial Unicode MS",
        ],
        &[
            (
                "ja",
                &[
                    ("Adlm", &["Noto Sans Adlam"]),
                    ("Arab", &["Geeza Pro"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Bangla Sangam MN"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cans", &["Euphemia UCAS"]),
                    ("Deva", &["Devanagari Sangam MN"]),
                    ("Ethi", &["Kefa"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Grantha Sangam MN"]),
                    ("Gujr", &["Gujarati Sangam MN"]),
                    ("Guru", &["Gurmukhi Sangam MN"]),
                    ("Hang", &["Apple SD Gothic Neo"]),
                    ("Hani", &["Hiragino Sans"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Arial"]),
                    ("Hira", &["Hiragino Sans"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Hiragino Sans"]),
                    ("Khmr", &["Khmer Sangam MN"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Lao Sangam MN"]),
                    ("Mlym", &["Malayalam Sangam MN"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Sinh", &["Sinhala Sangam MN"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["InaiMathi"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Telugu Sangam MN"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Ayuthaya"]),
                    ("Tibt", &["Kailasa"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "PingFang SC"]),
                ],
            ),
            (
                "ko",
                &[
                    ("Adlm", &["Noto Sans Adlam"]),
                    ("Arab", &["Geeza Pro"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Bangla Sangam MN"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cans", &["Euphemia UCAS"]),
                    ("Deva", &["Devanagari Sangam MN"]),
                    ("Ethi", &["Kefa"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Grantha Sangam MN"]),
                    ("Gujr", &["Gujarati Sangam MN"]),
                    ("Guru", &["Gurmukhi Sangam MN"]),
                    ("Hang", &["Apple SD Gothic Neo"]),
                    ("Hani", &["Apple SD Gothic Neo"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Arial"]),
                    ("Hira", &["Hiragino Sans"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Hiragino Sans"]),
                    ("Khmr", &["Khmer Sangam MN"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Lao Sangam MN"]),
                    ("Mlym", &["Malayalam Sangam MN"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Sinh", &["Sinhala Sangam MN"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["InaiMathi"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Telugu Sangam MN"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Ayuthaya"]),
                    ("Tibt", &["Kailasa"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "PingFang SC"]),
                ],
            ),
            (
                "zh-HK",
                &[
                    ("Adlm", &["Noto Sans Adlam"]),
                    ("Arab", &["Geeza Pro"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Bangla Sangam MN"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cans", &["Euphemia UCAS"]),
                    ("Deva", &["Devanagari Sangam MN"]),
                    ("Ethi", &["Kefa"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Grantha Sangam MN"]),
                    ("Gujr", &["Gujarati Sangam MN"]),
                    ("Guru", &["Gurmukhi Sangam MN"]),
                    ("Hang", &["Apple SD Gothic Neo"]),
                    ("Hani", &["PingFang HK"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Arial"]),
                    ("Hira", &["Hiragino Sans"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Hiragino Sans"]),
                    ("Khmr", &["Khmer Sangam MN"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Lao Sangam MN"]),
                    ("Mlym", &["Malayalam Sangam MN"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Sinh", &["Sinhala Sangam MN"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["InaiMathi"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Telugu Sangam MN"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Ayuthaya"]),
                    ("Tibt", &["Kailasa"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "PingFang SC"]),
                ],
            ),
            (
                "zh-TW",
                &[
                    ("Adlm", &["Noto Sans Adlam"]),
                    ("Arab", &["Geeza Pro"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Bangla Sangam MN"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cans", &["Euphemia UCAS"]),
                    ("Deva", &["Devanagari Sangam MN"]),
                    ("Ethi", &["Kefa"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Grantha Sangam MN"]),
                    ("Gujr", &["Gujarati Sangam MN"]),
                    ("Guru", &["Gurmukhi Sangam MN"]),
                    ("Hang", &["Apple SD Gothic Neo"]),
                    ("Hani", &["PingFang TC"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Arial"]),
                    ("Hira", &["Hiragino Sans"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Hiragino Sans"]),
                    ("Khmr", &["Khmer Sangam MN"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Lao Sangam MN"]),
                    ("Mlym", &["Malayalam Sangam MN"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Sinh", &["Sinhala Sangam MN"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["InaiMathi"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Telugu Sangam MN"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Ayuthaya"]),
                    ("Tibt", &["Kailasa"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "PingFang SC"]),
                ],
            ),
            (
                "en-US",
                &[
                    ("Adlm", &["Noto Sans Adlam"]),
                    ("Arab", &["Geeza Pro"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Bangla Sangam MN"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cans", &["Euphemia UCAS"]),
                    ("Deva", &["Devanagari Sangam MN"]),
                    ("Ethi", &["Kefa"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Grantha Sangam MN"]),
                    ("Gujr", &["Gujarati Sangam MN"]),
                    ("Guru", &["Gurmukhi Sangam MN"]),
                    ("Hang", &["Apple SD Gothic Neo"]),
                    ("Hani", &["PingFang SC"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Arial"]),
                    ("Hira", &["Hiragino Sans"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Hiragino Sans"]),
                    ("Khmr", &["Khmer Sangam MN"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Lao Sangam MN"]),
                    ("Mlym", &["Malayalam Sangam MN"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Sinh", &["Sinhala Sangam MN"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["InaiMathi"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Telugu Sangam MN"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Ayuthaya"]),
                    ("Tibt", &["Kailasa"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "PingFang SC"]),
                ],
            ),
            (
                "ja-JP",
                &[
                    ("Adlm", &["Noto Sans Adlam"]),
                    ("Arab", &["Geeza Pro"]),
                    ("Armn", &["Noto Sans Armenian"]),
                    ("Beng", &["Bangla Sangam MN"]),
                    ("Buhd", &["Noto Sans Buhid"]),
                    ("Cakm", &["Noto Sans Chakma"]),
                    ("Cans", &["Euphemia UCAS"]),
                    ("Deva", &["Devanagari Sangam MN"]),
                    ("Ethi", &["Kefa"]),
                    ("Goth", &["Noto Sans Gothic"]),
                    ("Gran", &["Grantha Sangam MN"]),
                    ("Gujr", &["Gujarati Sangam MN"]),
                    ("Guru", &["Gurmukhi Sangam MN"]),
                    ("Hang", &["Apple SD Gothic Neo"]),
                    ("Hani", &["PingFang SC"]),
                    ("Hano", &["Noto Sans Hanunoo"]),
                    ("Hebr", &["Arial"]),
                    ("Hira", &["Hiragino Sans"]),
                    ("Java", &["Noto Sans Javanese"]),
                    ("Kana", &["Hiragino Sans"]),
                    ("Khmr", &["Khmer Sangam MN"]),
                    ("Knda", &["Noto Sans Kannada"]),
                    ("Lana", &["Noto Sans Tai Tham"]),
                    ("Laoo", &["Lao Sangam MN"]),
                    ("Mlym", &["Malayalam Sangam MN"]),
                    ("Mong", &["Noto Sans Mongolian"]),
                    ("Mymr", &["Noto Sans Myanmar"]),
                    ("Orya", &["Noto Sans Oriya"]),
                    ("Sinh", &["Sinhala Sangam MN"]),
                    ("Syrc", &["Noto Sans Syriac"]),
                    ("Tagb", &["Noto Sans Tagbanwa"]),
                    ("Tale", &["Noto Sans Tai Le"]),
                    ("Taml", &["InaiMathi"]),
                    ("Tavt", &["Noto Sans Tai Viet"]),
                    ("Telu", &["Telugu Sangam MN"]),
                    ("Tfng", &["Noto Sans Tifinagh"]),
                    ("Tglg", &["Noto Sans Tagalog"]),
                    ("Thaa", &["Noto Sans Thaana"]),
                    ("Thai", &["Ayuthaya"]),
                    ("Tibt", &["Kailasa"]),
                    ("Vaii", &["Noto Sans Vai"]),
                    ("Yiii", &["Noto Sans Yi", "PingFang SC"]),
                ],
            ),
        ],
    ),
    (
        "other",
        &[],
        &[
            ("ja", &[]),
            ("ko", &[]),
            ("zh-HK", &[]),
            ("zh-TW", &[]),
            ("en-US", &[]),
            ("ja-JP", &[]),
        ],
    ),
];
